### ISSUE TITLE
Remote widget source provider doesn't work if any security required

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10060]
1. Remove the CDN sources (make them blank)
2. Connect to a remote server
3. Run something that needs a widget
4. Widget won't be downloaded

Root cause is the remote cdn provider doesn't do anything except pass the URI up to the webview for downloading. This doesn't work because the webview doesn't have the auth headers (or token) to make a valid request. 

I think the solution here is to refactor the CDN downloading code to support the server as a CDN source, but then it would make the appropriate requests with the correct headers, download from the remote jupyter server, and copy the source files to the same spot it does for CDNs.

Essentially remove this [source provider ](https://github.com/microsoft/vscode-jupyter/blob/9d9ad7d1f4756789ba9374d1a0351a558279ed8b/src/kernels/ipywidgets-message-coordination/remoteWidgetScriptSourceProvider.ts#L14) and have the CDN code also try kernel's baseURL. Meaning the kernel's base URL is always another CDN source.

**Comment by DonJayamanne** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/149868

**Comment by DonJayamanne** [comment]
I believe this is now fixed. marking as closed so it get validated.

**Comment by rchiodo** [comment]
This is not fixed for me at least. Same result as this issue that I just reopened #10510 

I did this:

- Set   ```"jupyter.widgetScriptSources": [],```
- Connected to a remote server
- Ran something with a widget

I get this dialog three times in a row:

![image](https://user-images.githubusercontent.com/19672699/176745641-02a33027-8f52-44dc-8862-eec909c430ab.png)

Then this pops up in the bottom right:

![image](https://user-images.githubusercontent.com/19672699/176745730-456a14f1-54dc-4d84-99f4-8408822d54e6.png)


Restarting the kernel does NOT make the widget appear.

I also thought we weren't supposed to need the CDN on remote? It should be able to pull the js files from the nbextension folder, right?
