### ISSUE TITLE
Can not detect remote jupyter kernel when connected to remote jupyter server after upgrade vscode to 1.70.0

### ISSUE THREAD

**Issue by SophyGao** [microsoft/vscode-jupyter#11119]
## Environment data

-   VS Code version: 1.70.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.6.1201981810
-   Python Extension version (available under the Extensions sidebar): v2022.12.0
-   OS (Windows | Mac | Linux distro) and version: Windows  10
-   Python and/or Anaconda version: 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote 

## Expected behaviour
Can detect remote jupyter kernel when select python kernel to run jupyter. This work when my vscode is 1.69.0. But after vscode update automatically to 1.70.0, it can not work anymore.
<img width="1192" alt="无标题" src="https://user-images.githubusercontent.com/13210779/184583207-fe9c7338-1978-4f15-b1d3-87b04c305e24.png">

## Actual behaviour
Can only find local python kernel even I already connected remote
![image](https://user-images.githubusercontent.com/13210779/184583272-9267d7fd-3728-48df-a09d-b50ed813cb19.png)
<img width="1267" alt="无标题" src="https://user-images.githubusercontent.com/13210779/184583403-fde2bc4f-ce6c-4d75-a6a4-8565052f4c61.png">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Upgrade vscode to 1.70.1
2. Install python and jupyter extension. 
3. Connect remote jupyter server 
4. Select remote kernel

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>
</p>
</details>

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this issue and thanks for filing this with us.

> Jupyter Extension version (available under the Extensions sidebar): v2022.6.1201981810

Please could you update to the latest jupyter extesnion version `2022.7.10...`, this may have been fixed in there.
Let me know if this works.

**Comment by SophyGao** [comment]
@DonJayamanne Thanks for your quick response. Forget to check the github daily. Looks like the issue still the same. Below is the log, thanks!
[jupyter log.txt](https://github.com/microsoft/vscode-jupyter/files/9391898/jupyter.log.txt)

**Comment by SophyGao** [comment]
Looks like it is resolved

**Comment by DonJayamanne** [comment]
Thanks for getting back to us with a confirmation of the fix

**Comment by itsaadish** [comment]
<img width="1512" alt="Screenshot_2023-06-12_at_5 22 54_PM" src="https://github.com/microsoft/vscode-jupyter/assets/68146545/bd8f1aa8-342f-4218-ac2c-d0360dbcd32e">

**Comment by itsaadish** [comment]
kernel is failing please help
