### ISSUE TITLE
Problems with the "Select kernel" dialog which pops up when you run a notebook in VSCode.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#11919]
@rchiodo  the problem seems to be with the "Select kernel" dialog which pops up when you run a notebook in VSCode. 

* The list of venvs is incomplete, or it apparently doesn't see the venv which the current Python interpreter is using in VSCode.
* The list of venvs  cannot be refreshed.
* It doesn't have an affordance to enter a path.

<img width="970" alt="Screen Shot 2022-11-04 at 3 55 41 PM" src="https://user-images.githubusercontent.com/766758/200080893-fe8629d6-1a32-4d3a-b2b2-14ef969c7000.png">

edit:

There seems to be some condition which triggers the current venv to appear in the picklist for 'select kernel'. Cannot quite figure out what that is. Have tried installing ipykernel, have tried running `jupyter notebook` , etc.

_Originally posted by @guidorice in https://github.com/microsoft/vscode-jupyter/issues/5319#issuecomment-1304293783_

**Comment by rchiodo** [comment]
@guidorice I added a new issue for you.

**Comment by mateo-st** [comment]
Same problem for me. Kernel lists only a few virtual environments (and only one created from venv), but in environment list all appear.

**Comment by dat-linux** [comment]
What happened to "enter interpreter path" option in the dropdown???

**Comment by DonJayamanne** [comment]
> happened to "enter interpreter path" option in the dropdown???

such an option never existed

**Comment by DonJayamanne** [comment]
> Same problem for me. Kernel lists only a few virtual environments (and only one created from venv), but in environment list all appear.

This has been fixed in the latest pre-release version of the Juptyer extesnion, Will close this for now,
Please install VS Code insiders and the latest pre-release version of Jupyter & Python extension

> The list of venvs cannot be refreshed.

Same as previous comment.

> It doesn't have an affordance to enter a path.

This isn't supported, you can add a path into Python Interpreters and their environments should now automatically show up in Jupyter extension as well.

Closing this as all have been addressed in the latest pre-release version.

**Comment by kuntojirohan** [comment]
I'm still facing this issue, exactly the same as mentioned by @rchiodo. Any particular fixes gone into the latests releases of the plugins?

**Comment by DonJayamanne** [comment]
> still facing this issue, exactly the same as mentioned b

please could you file a Seagate bug.
or provide more information like the following
* version of extension and vscode
* screenshot
* what exactly is not wishing and what is expected
