### ISSUE TITLE
Duplicate and incorrect completion suggestions

### ISSUE THREAD

**Issue by cdeil** [microsoft/vscode-jupyter#13596]
Type: <b>Bug</b>

Open a new file `spam.ipynb` and type `from math import sin`.

The completion `sinh` is offered twice.

Also the completion `shinyapp` is offered which doesn't make sense at this point.

See screenshot:

<img width="548" alt="Screenshot 2023-05-28 at 14 34 21" src="https://github.com/microsoft/pylance-release/assets/852409/4aa45b81-e32c-42dc-951f-096aead1c220">

Extension version: 2023.5.40
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin arm64 22.5.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|. --crash-reporter-id 1480505a-7fab-484b-83e7-97e0db97f0eb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by cdeil** [comment]
I now no longer see any duplicates.

However, I still see incorrect completion suggestions that should not appear here: `shinyapp`, `shinymod`, `_SupportsCeil`, `_SupportsFloatOrIndex`, ...

Can you make it better please?

<img width="636" alt="Screenshot 2023-12-31 at 16 01 51" src="https://github.com/microsoft/vscode-jupyter/assets/852409/33c42804-29ef-4425-bddb-a59cd9f1ce72">

<img width="573" alt="Screenshot 2023-12-31 at 16 05 37" src="https://github.com/microsoft/vscode-jupyter/assets/852409/2002f8ea-7221-4897-9c7f-64f33e2f7f11">

**Comment by DonJayamanne** [comment]
This should now be fixed in the latest version of Jupyter exetnsion.

**Comment by cdeil** [comment]
@DonJayamanne - which version should contain the fix?

I still see the issue.
