### ISSUE TITLE
Review the new Jupyter API for contributing Jupyter Servers to the Kernel Picker

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14201]
Refs: #13894

- [x] anyOS: @rebornix  
- [x] anyOS: @amunger 

Complexity: 5

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2314201%0A%0A&assignees=DonJayamanne)

---

# Steps
* Create a sample VS Code extension using `yo code` or by any other means
* Consume the Jupyter API as defined here https://github.com/microsoft/vscode-jupyter/blob/main/src/api.proposed.d.ts
* Review the API and contribute a new item for the Kernel Picker 
* [ ] Verify it shows up in the kernel picker along with `Python Environments`, `Jupyter Kernels`, `Existing Jupyter Server`
* [ ] Contribute Jupyter Servers (with ids and lables) and verify they show up in the quick pick upon selecting the newly contributed item
* [ ] Verify the documentation in the API is clear enough.
* [ ] Trigger the `onDidChangeServers` event and verify the new Servers are displayed in the quick pick
* [ ] Create at least two commands and verify they are displayed in the quick pick
    * [ ] Verify selecting each command ends up calling the `handleCommand` with the right arguments.
* Create only one command and ensure there are no servers
    * [ ] Upon selecting your server from the kernel picker, verify the command is automatically selected.

### Note: 
* If there are no servers, and only one command, then the command will not be displayed, instead that will be automatically executed.
* This is done to improve the UX, as there's no point displaying a quick pick with just one option (we do this today with `Existing Juptyer Server`

@rebornix 
* [ ] Verify you are able to select a valid Jupyter Kernel from the extension you build
* [ ] Verify you are able to execute a cell from the kernel selected
* [ ] Reload VS Code and verify the same kernel  is auto selected in the kernel picker
* [ ] Go into the kernel picker and verify the server is now listed with a date/time for the last connection

@amunger Feel free to try to get an extension working with authentication,
* Here are some steps to get an extension up and running 
* Start Jupyter locally
* Keep track of the URL and the token
* In extension when returning the `JupyterServerConnectionInformation` information, 
    * Set the `baseUrl` property to the host, e.g. `http://localhost:8080/`
    * Set the `token` property to the token from the URL
* This should be enough for the extension to work end to end, allowing you to select kernels from your extension and run code against them as well.

FYI - Peng has already has an extension and we discussed offline that he will adopt the new API in his extension and verify this.

**Comment by amunger** [comment]
is `createJupyterServerCollection` the API I'm supposed to test? I do not understand how to use it - all I pass in is a id and label, how does the actual collection get created and registered?

I see an allow list for extensions [here](https://github.com/microsoft/vscode-jupyter/blob/main/src/standalone/api/api.ts#L164), do I need to do something special to use it?

**Comment by amunger** [comment]
Here is the WIP extension https://github.com/amunger/SampleKernelSource/blob/main/src/extension.ts

I haven't actually implemented the server provider, but that code is never called and my new entry does not show up in the list of providers

**Comment by rebornix** [comment]
I'm seeing the same issue, it seems `provideJupyterServers` is never called.

**Comment by DonJayamanne** [comment]
@amunger @rebornix , sorry, yes the problem was with the fact that other publishers were blocked
Have submitted a PR to address that.

**Comment by rebornix** [comment]
visx with the fix is available now https://dev.azure.com/monacotools/Monaco/_build/results?buildId=229659&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by andreamah** [comment]
Is this TPI unblocked now?

> visx with the fix is available now https://dev.azure.com/monacotools/Monaco/_build/results?buildId=229659&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by amunger** [comment]
@rebornix - that should be in pre-release today right? I just tried again and I now see my kernel provider in the list, but the getJupyterServers function still isn't called from what I can see.

**Comment by amunger** [comment]
same story for that published visx

**Comment by amunger** [comment]
ah, the API changed as well since yesterday, didn't notice that - I'll check again
