### ISSUE TITLE
Waiting for connection to be idle

### ISSUE THREAD

**Issue by jaymc-arg** [microsoft/vscode-jupyter#15852]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm connecting to a remote jupyterhub server and after log in I can not execute any cell because it keeps hanging with the notification: "Waiting for Jupyter session to be idle", and after some time "Connectinc to kernel: Ipython3". I've tryed to run the server locally, but the same issue appears.
I've used the extension with this same server in the past and it was working fine, I do also can reach the server with from my browser.
This is the docker-compose.yml i'm using to run the server:
```
version: "3"

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: 4.0.0
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
    ports:
      - "8000:8000"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: caraboy/datascience-sintys:0.1.2 # personal datascience notebook with some ENV vars for oracle drivers and system package instalation (oracledb driver, wget, unzip, etc)
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
      # log level
      LOG_LEVEL: DEBUG
volumes:
  jupyterhub-data:

networks:
 jupyterhub-network:
    name: jupyterhub-network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  # SOME IP RANGE of my organization

```

### VS Code Version

1.90.2 5437499feb04f7a586f677b155b039bc2b3669eb x64

### Jupyter Extension Version

v2024.6.0

### Jupyter logs

Not sure on how i can get the logs, with `jupyter show output` but i've done it with `jupyter notebook --debug`

```shell

[D 2024-07-16 14:43:09.791 ServerApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /usr/etc/jupyter
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /root/.local/etc/jupyter
[D 2024-07-16 14:43:09.792 ServerApp] Looking for jupyter_config in /root/.jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /usr/etc/jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /root/.local/etc/jupyter
[D 2024-07-16 14:43:09.794 ServerApp] Looking for jupyter_server_config in /root/.jupyter
[D 2024-07-16 14:43:09.801 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/etc/jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.802 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/usr/local/etc/jupyter/jupyter_server_config.d/jupyter-lsp-jupyter-server.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/jupyter_server_terminals.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/jupyterlab.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/notebook.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/notebook_shim.json
    	/usr/local/etc/jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.802 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/usr/etc/jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.803 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/root/.local/etc/jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.803 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/root/.jupyter/jupyter_server_config.json
[D 2024-07-16 14:43:09.810 ServerApp] Extension package notebook took 0.0000s to import
[D 2024-07-16 14:43:09.823 ServerApp] Extension package jupyter_lsp took 0.0120s to import
[D 2024-07-16 14:43:09.832 ServerApp] Extension package jupyter_server_terminals took 0.0081s to import
[D 2024-07-16 14:43:09.833 ServerApp] Extension package jupyterlab took 0.0000s to import
[D 2024-07-16 14:43:10.483 ServerApp] Paths used for configuration of page_config: 
    	/usr/etc/jupyter/labconfig/page_config.json
[D 2024-07-16 14:43:10.484 ServerApp] Paths used for configuration of page_config: 
    	
[D 2024-07-16 14:43:10.491 ServerApp] Extension package notebook_shim took 0.0000s to import
[I 2024-07-16 14:43:10.491 ServerApp] jupyter_lsp | extension was successfully linked.
[D 2024-07-16 14:43:10.496 TerminalsExtensionApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2024-07-16 14:43:10.497 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'notebook': True, 'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-07-16 14:43:10.498 ServerApp] jupyter_server_terminals | extension was successfully linked.
[D 2024-07-16 14:43:10.504 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'notebook': True, 'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-07-16 14:43:10.505 ServerApp] jupyterlab | extension was successfully linked.
[D 2024-07-16 14:43:10.510 JupyterNotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'notebook': True, 'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2024-07-16 14:43:10.511 ServerApp] notebook | extension was successfully linked.
[D 2024-07-16 14:43:10.819 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/root/.jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.819 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.819 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.820 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/etc/jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.820 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/root/.local/etc/jupyter/jupyter_notebook_config.json
[D 2024-07-16 14:43:10.820 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/root/.jupyter/jupyter_notebook_config.json
[I 2024-07-16 14:43:10.820 ServerApp] notebook_shim | extension was successfully linked.
[D 2024-07-16 14:43:10.822 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'notebook': True, 'jupyter_lsp': True, 'jupyter_server_terminals': True, 'jupyterlab': True, 'notebook_shim': True}>}}
[I 2024-07-16 14:43:10.842 ServerApp] notebook_shim | extension was successfully loaded.
[D 2024-07-16 14:43:10.844 ServerApp] [lsp] rootUri will be file:///srv/jupyterhub
[D 2024-07-16 14:43:10.844 ServerApp] [lsp] virtualDocumentsUri will be file:///srv/jupyterhub/.virtual_documents
[I 2024-07-16 14:43:10.845 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-07-16 14:43:10.846 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-07-16 14:43:10.847 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/dist-packages/jupyterlab
[I 2024-07-16 14:43:10.847 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2024-07-16 14:43:10.848 LabApp] Extension Manager is 'pypi'.
[D 2024-07-16 14:43:10.848 LabApp] Plugins in PyPIExtensionManager will managed on the sys_prefix level
[D 2024-07-16 14:43:10.913 LabApp] Extensions list will be fetched from https://pypi.org/pypi.
[D 2024-07-16 14:43:10.914 LabApp] Plugins in PluginManager will managed on the sys_prefix level
[D 2024-07-16 14:43:10.915 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.915 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/usr/local/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.916 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/usr/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.916 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/root/.local/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.916 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/root/.jupyter/labconfig/default_setting_overrides.json
[I 2024-07-16 14:43:10.919 ServerApp] jupyterlab | extension was successfully loaded.
[D 2024-07-16 14:43:10.921 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.921 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/usr/local/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.922 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/usr/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.922 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/root/.local/etc/jupyter/labconfig/default_setting_overrides.json
[D 2024-07-16 14:43:10.922 ServerApp] Paths used for configuration of default_setting_overrides: 
    	/root/.jupyter/labconfig/default_setting_overrides.json
[I 2024-07-16 14:43:10.923 ServerApp] notebook | extension was successfully loaded.
[C 2024-07-16 14:43:10.924 ServerApp] Running as root is not recommended. Use --allow-root to bypass.
[D 2024-07-16 14:43:10.924 ServerApp] Exiting application: jupyter-server
```

### Coding Language and Runtime Version

python 3.10

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by jaymc-arg** [comment]
changed the log level to `debug` but the output panel stills don't show any difference, even the notification is the same:
![image](https://github.com/user-attachments/assets/b4f6f959-e402-43c9-ad6c-e771c7669a8a)
Where are the logs stored?

**Comment by DonJayamanne** [comment]
> where are the logs stored


You can use the command `Jupyter: Show Output` to get to that 

![Image](https://github.com/user-attachments/assets/5969736b-cf8d-44e2-8b10-59f4f0373731)

**Comment by jaymc-arg** [comment]
Thanks for the log hint, i was driving crazy looking for it.
```
Visual Studio Code (1.91.1, undefined, desktop)
Jupyter Extension Version: 2024.2.0.
Python Extension Version: 2024.10.0.
Pylance Extension Version: 2024.7.1.
Platform: linux (x64).
Workspace folder /opt/docker, Home = /home/juanc
11:09:14.455 [debug] Get Custom Env Variables, Class name = Rm (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
11:09:14.455 [info] Start refreshing Kernel Picker (1721311754455)
11:09:14.466 [info] Using Pylance
11:09:14.497 [debug] Get Custom Env Variables, Class name = Rm, completed in 42ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
11:09:14.497 [debug] Jupyter Paths /kernels: 
11:09:14.497 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
11:09:14.500 [debug] Search for KernelSpecs in Interpreter /bin/python3
11:09:14.500 [debug] Finding Global Python KernelSpecs
11:09:14.501 [debug] Search for KernelSpecs in Interpreter /usr/bin/python3
11:09:14.501 [debug] Search for KernelSpecs in Interpreter ~/virtualenvs/sintys/bin/python3.10
11:09:14.501 [debug] Full interpreter list is length: 3, /bin/python3::Unknown:/bin/python3, /usr/bin/python3::Unknown:/usr/bin/python3, ~/virtualenvs/sintys/bin/python3.10:sintys:Venv:~/virtualenvs/sintys/bin/python3.10
11:09:14.502 [debug] Getting activated env variables, Class name = yp (started execution), Arg 1: "/opt/docker", Arg 2: "/bin/python3", Arg 3: undefined
11:09:14.502 [debug] Get Custom Env Variables, Class name = Rm (started execution), Arg 1: "/opt/docker", Arg 2: "RunPythonCode"
11:09:14.502 [debug] Get Custom Env Variables, Class name = Rm, completed in 0ms, has a truthy return value, Arg 1: "/opt/docker", Arg 2: "RunPythonCode"
11:09:14.508 [debug] Kernels for interpreter /bin/python3 are .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
11:09:14.508 [debug] Kernels for interpreter /usr/bin/python3 are .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher
11:09:14.510 [debug] Loading kernelspec from ~/.local/share/jupyter/kernels/python3/kernel.json 
11:09:14.510 [debug] Loading kernelspec from ~/virtualenvs/sintys/share/jupyter/kernels/python3/kernel.json for ~/virtualenvs/sintys/bin/python3.10
11:09:14.512 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'python31012jvsc74a57bd0e5fe1b8ca388bd7e85f54b427b3c3c0cad77a9519939f59df88a221b60a4f0c7', /python for interpreter ~/virtualenvs/sintys/bin/python3.10 and spec ~/virtualenvs/sintys/share/jupyter/kernels/python3/kernel.json
11:09:14.512 [debug] Kernels for interpreter ~/virtualenvs/sintys/bin/python3.10 are .jvsc74a57bd0e5fe1b8ca388bd7e85f54b427b3c3c0cad77a9519939f59df88a221b60a4f0c7.~/virtualenvs/sintys/bin/python3.10.~/virtualenvs/sintys/bin/python3.10.-m#ipykernel_launcher
11:09:14.833 [debug] creating new code watcher with matching document file:///opt/docker/conection.py
11:09:14.872 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://127.0.0.1:8888/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8888
11:09:14.873 [error] Failed to validate Password info [D [FetchError]: request to http://127.0.0.1:8888/tree? failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/node-fetch.js:1:306479)
	at ClientRequest.emit (node:events:514:28)
	at Socket.socketErrorListener (node:_http_client:495:9)
	at Socket.emit (node:events:514:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
11:09:14.889 [error] Error fetching kernels from http://127.0.0.1:8888/ (<username>): [FetchError: request to http://127.0.0.1:8888/api/kernels?1721311754883 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/node-fetch.js:1:306479)
	at ClientRequest.emit (node:events:514:28)
	at Socket.socketErrorListener (node:_http_client:495:9)
	at Socket.emit (node:events:514:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
11:09:14.889 [debug] Disposing Jupyter Lab Helper
11:09:14.889 [debug] SessionManager - dispose contents manager
11:09:14.889 [debug] ShutdownSessionAndConnection - dispose session manager
11:09:14.890 [debug] Finished disposing Jupyter Lab Helper
11:09:14.890 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [FetchError: request to http://127.0.0.1:8888/api/kernels?1721311754883 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/node-fetch.js:1:306479)
	at ClientRequest.emit (node:events:514:28)
	at Socket.socketErrorListener (node:_http_client:495:9)
	at Socket.emit (node:events:514:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
11:09:14.890 [debug] UniversalRemoteKernelFinder: Writing 0 remote kernel connection metadata to cache
11:09:14.890 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:198:12579)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async sD.listKernelsFromConnection (~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:308:20060)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/dist/extension.node.js:308:17485]
11:09:14.940 [debug] Conda file returned by Python Extension is conda
11:09:14.965 [warn] Failed to get activated env vars for /bin/python3 in 463ms
11:09:14.966 [debug] Create ProcessService, Class name = Tm (started execution), Arg 1: undefined
11:09:14.966 [debug] Get Custom Env Variables, Class name = Rm (started execution), Arg 1: undefined, Arg 2: "RunNonPythonCode", Arg 3: undefined
11:09:14.968 [debug] Get Custom Env Variables, Class name = Rm, completed in 2ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunNonPythonCode", Arg 3: undefined
11:09:14.968 [debug] Create ProcessService, Class name = Tm, completed in 2ms, has a truthy return value, Arg 1: undefined
11:09:14.974 [info] Process Execution: /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
11:09:14.988 [debug] USER_SITE for /bin/python3 is ~/.local/bin
11:09:14.988 [debug] Prepend PATH with user site path for /bin/python3, user site ~/.local/bin
11:09:14.988 [debug] Prepend PATH with python bin for /bin/python3
11:09:14.988 [debug] Activated Env Variables for /bin/python3, 
    PATH value is /bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin and 
    Path value is undefined
11:09:14.989 [debug] Getting activated env variables, Class name = yp, completed in 487ms, has a truthy return value, Arg 1: "/opt/docker", Arg 2: "/bin/python3", Arg 3: undefined
11:09:14.993 [info] Process Execution: /bin/python3 -m pip list
11:09:15.501 [info] End refreshing Kernel Picker (1721311754455)
11:09:21.822 [info] Start refreshing Interpreter Kernel Picker
11:09:21.822 [info] Start refreshing Kernel Picker (1721311761822)
11:09:21.832 [debug] Preferred Remote kernel for /opt/docker/conn.ipynb is undefined
11:09:21.834 [info] No interpreter for Pylance for Notebook URI "/opt/docker/conn.ipynb"
11:09:21.835 [debug] No controller, hence notebook communications cannot be initialized for editor /opt/docker/conn.ipynb
11:09:22.084 [debug] Python API env change detected, update => '/bin/python3'
11:09:22.085 [debug] Python API env change detected, update => '/usr/bin/python3'
11:09:22.110 [debug] Full interpreter list is length: 3, /bin/python3::Unknown:/bin/python3, /usr/bin/python3::Unknown:/usr/bin/python3, ~/virtualenvs/sintys/bin/python3.10:sintys:Venv:~/virtualenvs/sintys/bin/python3.10
11:09:22.111 [debug] Refreshed Environments
11:09:23.111 [info] End refreshing Kernel Picker (1721311761822)
11:09:31.743 [info] Start refreshing Kernel Picker (1721311771743)
11:09:31.745 [debug] Preferred Remote kernel for /opt/docker/conn.ipynb is undefined
11:09:31.858 [debug] Disposing Jupyter Lab Helper
11:09:31.858 [debug] SessionManager - dispose contents manager
11:09:31.859 [debug] ShutdownSessionAndConnection - dispose session manager
11:09:31.859 [debug] Finished disposing Jupyter Lab Helper
11:09:31.859 [debug] UniversalRemoteKernelFinder: Writing 4 remote kernel connection metadata to cache
11:09:31.874 [info] End refreshing Kernel Picker (1721311771743)
11:09:31.896 [debug] KernelProvider switched kernel to id = c2951cd09ad7c7c34bd06a9c4531276ba3da0b9fccef1e0a1586978837baacd3..python3./opt/conda/python./.-m#ipykernel_launcher
11:09:31.897 [debug] Initialize notebook communications for editor /opt/docker/conn.ipynb
11:09:31.897 [debug] Resolving notebook UI Comms (resolve) for /opt/docker/conn.ipynb
11:09:31.897 [debug] initialize CommonMessageCoordinator
11:09:31.897 [debug] Registering commtarget jupyter.widget
11:09:31.897 [debug] IPyWidgetMessageDispatcher.initialize
11:09:31.897 [debug] Attempting to determine version of IPyWidgets
11:09:31.898 [debug] Controller selection change completed
11:09:31.898 [debug] Waiting for IPyWidgets version
11:09:31.898 [debug] Waiting for IPyWidgets version promise
11:09:42.563 [info] Handle Execution of Cells 0 for /opt/docker/conn.ipynb
11:09:42.564 [debug] start the kernel, options.disableUI=false for /opt/docker/conn.ipynb
11:09:42.564 [info] Starting Kernel startUsingRemoteKernelSpec, c2951cd09ad7c7c34bd06a9c4531276ba3da0b9fccef1e0a1586978837baacd3..python3./opt/conda/python./.-m#ipykernel_launcher  for '/opt/docker/conn.ipynb' (disableUI=false)
11:09:42.583 [debug] createNewKernelSession c2951cd09ad7c7c34bd06a9c4531276ba3da0b9fccef1e0a1586978837baacd3..python3./opt/conda/python./.-m#ipykernel_launcher
11:09:42.614 [info] http://localhost:8000/user/admin/: Kernel started: c903248c-16f9-4c1c-b25e-9dcc6c9d8448
11:09:42.614 [debug] Waiting for idle on (kernel): c903248c-16f9-4c1c-b25e-9dcc6c9d8448 -> unknown
11:10:42.620 [debug] Finished waiting for idle on (kernel): c903248c-16f9-4c1c-b25e-9dcc6c9d8448 -> unknown
11:10:42.620 [error] Shutting down after failing to wait for idle on (kernel): c903248c-16f9-4c1c-b25e-9dcc6c9d8448 -> unknown
11:10:42.621 [info] Started session for kernel startUsingRemoteKernelSpec:c2951cd09ad7c7c34bd06a9c4531276ba3da0b9fccef1e0a1586978837baacd3..python3./opt/conda/python./.-m#ipykernel_launcher
11:10:42.623 [debug] Started running kernel initialization for /opt/docker/conn.ipynb
11:10:42.624 [debug] Executing silently Code (unknown) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy

```

**Comment by DonJayamanne** [comment]
Please can you share the docker file used, so I can try this at my end as well.

**Comment by jaymc-arg** [comment]
> Please can you share the docker file used, so I can try this at my end as well.

I'm using several different Dockerfiles with some some package installations. But i do also tryed locally the one of [this repo](https://github.com/jupyterhub/jupyterhub-deploy-docker) that is pretty vanilla and same issue.

> Looks like you have an old version of the Jupyter extension installed, please can you update it to the latest version.

Yup, tried downgrading because it was working 2 months ago. Now updated to `v2024.6.0` but no changes.

**Comment by DonJayamanne** [comment]
@jaymc-arg 
Please could you
* Download the attached file
* Extract this file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* When prompted to reload VS Code, please do so
* Try to replicate the issue once again


[ms-toolsai-jupyter-insiders.vsix (2).zip](https://github.com/user-attachments/files/16386263/ms-toolsai-jupyter-insiders.vsix.2.zip)

**Comment by jaymc-arg** [comment]
@DonJayamanne it promts the error that the extension is not compatible with vscode 1.91.1. want me to make a downgrade?

**Comment by DonJayamanne** [comment]
Oh sorry, please can you install VS Code insiders and then install that VSIX into vscode insiders and try again.
Let me know if you're unable/unwilling to install VS Code insiders, and i'll create a new VSIX.

**Comment by jaymc-arg** [comment]
Same result, leave you logs here:
```
Visual Studio Code - Insiders (1.92.0-insider, undefined, desktop)
Jupyter Extension Version: 2024.7.0.
Python Extension Version: 2024.10.0.
Pylance Extension Version: 2024.7.1.
Platform: linux (x64).
Workspace folder /opt/docker, Home = /home/juanc
17:18:56.830 [debug] Start refreshing Kernel Picker (1722111536830)
17:18:57.112 [trace] Search for KernelSpecs in Interpreter /bin/python3
17:18:57.113 [trace] Search for KernelSpecs in Interpreter /usr/bin/python3
17:18:57.124 [trace] Kernel Spec for 'Python 3 (ipykernel)' (~/.local/share/jupyter/kernels/python3/kernel.json) is hidden. (isDefaultKernelSpec = true, language = python, registrationInfo = undefined)
17:18:57.125 [debug] Get Custom Env Variables, Class name = Sm, completed in 296ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
17:18:57.126 [debug] Jupyter Paths /kernels: 
17:18:57.126 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
17:18:57.149 [debug] End refreshing Kernel Picker (1722111536830)
17:18:57.455 [trace] No controller, hence notebook communications cannot be initialized for editor /opt/docker/conn.ipynb
17:18:57.457 [debug] Start refreshing Interpreter Kernel Picker
17:18:57.459 [debug] Start refreshing Kernel Picker (1722111537459)
17:18:57.587 [trace] Conda file is conda
17:18:57.596 [trace] Python API env change detected, update => '/bin/python3'
17:18:57.598 [trace] Python API env change detected, update => '/usr/bin/python3'
17:18:57.601 [debug] Refreshed Environments
17:18:58.602 [debug] End refreshing Kernel Picker (1722111537459)
17:18:58.680 [debug] No interpreter for Pylance for Notebook URI "/opt/docker/conn.ipynb"
17:19:07.689 [debug] Start refreshing Kernel Picker (1722111547689)
17:19:07.806 [trace] Disposing Jupyter Lab Helper
17:19:07.806 [trace] SessionManager - dispose contents manager
17:19:07.807 [trace] ShutdownSessionAndConnection - dispose session manager
17:19:07.807 [trace] Finished disposing Jupyter Lab Helper
17:19:07.808 [trace] UniversalRemoteKernelFinder: Writing 1 remote kernel connection metadata to cache
17:19:07.830 [debug] End refreshing Kernel Picker (1722111547689)
17:19:07.843 [debug] KernelProvider switched kernel to id = 57d7c7a601954062906da297b197cd7106dd53fb528bec3de5f3e93f88bea57f..python3./opt/conda/python./.-m#ipykernel_launcher
17:19:07.846 [trace] Registering commtarget jupyter.widget
17:19:07.846 [debug] Controller selection change completed
17:19:13.024 [debug] Handle Execution of Cells 0 for /opt/docker/conn.ipynb
17:19:13.026 [debug] start the kernel, options.disableUI=false for /opt/docker/conn.ipynb
17:19:13.027 [info] Starting Kernel (Python 3 (ipykernel)) for '/opt/docker/conn.ipynb' (disableUI=false)
17:19:13.064 [trace] createNewKernelSession 57d7c7a601954062906da297b197cd7106dd53fb528bec3de5f3e93f88bea57f..python3./opt/conda/python./.-m#ipykernel_launcher
17:19:13.109 [info] http://localhost:8000/user/admin/: Kernel started: 9b2b3dc7-4f05-490b-8e1d-1d47ff831a19
17:19:13.110 [trace] Waiting for idle on (kernel): 9b2b3dc7-4f05-490b-8e1d-1d47ff831a19 -> unknown
17:20:13.112 [trace] Finished waiting for idle on (kernel): 9b2b3dc7-4f05-490b-8e1d-1d47ff831a19 -> unknown
17:20:13.113 [warn] Timeout waiting for kernel to be idle, continuing to use it as Status is Unknown: 9b2b3dc7-4f05-490b-8e1d-1d47ff831a19
17:20:13.115 [info] Started session for kernel startUsingRemoteKernelSpec:57d7c7a601954062906da297b197cd7106dd53fb528bec3de5f3e93f88bea57f..python3./opt/conda/python./.-m#ipykernel_launcher
17:20:13.117 [trace] Started running kernel initialization for /opt/docker/conn.ipynb
17:20:13.118 [trace] Executing silently Code (unknown) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy

```

**Comment by DonJayamanne** [comment]
@jaymc-arg can you confirm it works at this stage
Ie after that message appears you can now run code
I agree it takes a full minute, but after that it should work (ie execution should work)

To reduce the timeout from 60s , you can go into the settings and search for the setting ‘Jupyter Launch Timeout’ to a lower value such a 5000-10000 (the values are in milliseconds)

In the mean time I’ll try to replicate this at my end with the same container

**Comment by DonJayamanne** [comment]
Ok, I've had a look at the container and tried this myself.
I can replicate the issue and I believe this is a configuration issue, as we're getting a 403 error when attempting to connect to the websocket.
I've created an issue here, hopefully someone will have an answer for this
https://discourse.jupyter.org/t/websocket-connection-errors-when-connecting-to-kernel-from-desktop-app-started-in-docker/27244

**Comment by jaymc-arg** [comment]
@DonJayamanne thank's. I confirm it is not working.

**Comment by DonJayamanne** [comment]
Found the reason

**(Below, notes for personal use)**

* The docker container uses `jupyterhub-singleuser` to start the Jupyter Lab server
`customizes that program to change (approximately) one thing: authenticate requests with JupyterHub.`

See here https://jupyterhub.readthedocs.io/en/latest/explanation/singleuser.html

`By default, jupyter-server uses its own cookie to authenticate. If that cookie is not present, the server redirects you a login page and asks you to enter a password or token.`

As a result of this, the WebSocket also needs the headers (in particular the `Cookie`)
Without this, the websocket request is deemed un-authenticated and a 403 error is returned, thus the websocket handshake fails.

**Comment by DonJayamanne** [comment]
@jaymc-arg 
Thank you for your patience
I think i've fixed this issue, I have tested this with the container you provided and it seems to work as expected.
FYI = I would suggest you install the pre-release version of the JupyterHub extension from the VS Code marketplace then select `Existing JupyterHubServer` from the kernel picker to add the Url (note, just include the base Url without the user information).

It should work as expected.
Here's the link to the JupyterHub extension https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-hub
Note: JupyterHub support in Jupyter extension will be removed soon, meaning you will have to use the above extension.
We still support JupyterHub, just moved the functionality into a separate extension.

![Image](https://github.com/user-attachments/assets/550e3fde-b3e0-4341-ae22-603a7ec27afe)

**Comment by DonJayamanne** [comment]
Optionally, please install this VSIX to verify the fix

Please could you
* Download the attached file
* Extract this file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* When prompted to reload VS Code, please do so
* Try to replicate the issue once again


[ms-toolsai-jupyter-insiders.vsix.zip](https://github.com/user-attachments/files/16437698/ms-toolsai-jupyter-insiders.vsix.zip)

**Comment by joseph-siefert** [comment]
I am still facing this issue. I tried the above solution and received the following error:
![image](https://github.com/user-attachments/assets/57c63f2f-7a01-4273-98ed-633e5b48b473)

**Comment by DonJayamanne** [comment]
Can you try installing the pre release version of Jupyterhub extension and select the JupyterHub server option instead

**Comment by joseph-siefert** [comment]
I have installed the pre-release of Jupyterhub and selected the JupyterHub server option, but now I get the error: “Invalid JupyterHub URL specified”

**Comment by jaymc-arg** [comment]
@DonJayamanne I'm still having the same issue.
1) Tried installng the prerelease version --> exact same result
2) Tried installing the vsix in insiders
In the second case it does not shows any notification of waiting connection but it never executes the cells
![image](https://github.com/user-attachments/assets/866a9382-86b7-4086-89ed-ba2a009c5a1b)

```
Visual Studio Code - Insiders (1.92.0-insider, undefined, desktop)
Jupyter Extension Version: 2024.8.0.
Python Extension Version: 2024.12.1.
Pylance Extension Version: 2024.7.1.
Platform: linux (x64).
Workspace folder /opt/docker, Home = /home/juanc
12:29:37.698 [debug] Start refreshing Kernel Picker (1722526177698)
12:29:37.745 [debug] Start refreshing Interpreter Kernel Picker
12:29:37.774 [trace] Search for KernelSpecs in Interpreter /bin/python3
12:29:37.775 [trace] Search for KernelSpecs in Interpreter /usr/bin/python3
12:29:37.777 [trace] Kernel Spec for 'Python 3 (ipykernel)' (~/.local/share/jupyter/kernels/python3/kernel.json) is hidden. (isDefaultKernelSpec = true, language = python, registrationInfo = undefined)
12:29:37.780 [debug] Get Custom Env Variables, Class name = Sm, completed in 82ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
12:29:37.780 [debug] Jupyter Paths /kernels: 
12:29:37.782 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
12:29:37.784 [trace] Preferred Remote kernel for /Interactive-1.interactive is undefined
12:29:38.188 [trace] No controller, hence notebook communications cannot be initialized for editor /Interactive-1.interactive
12:29:38.189 [debug] creating new code watcher with matching document file:///opt/docker/conection.py
12:29:38.267 [trace] UniversalRemoteKernelFinder: Writing 1 remote kernel connection metadata to cache
12:29:38.332 [trace] Preferred Remote kernel for /opt/docker/conn.ipynb is 053a62a8-f25a-4a2d-9557-2504ebc3223c
12:29:38.392 [trace] Conda file is conda
12:29:38.655 [trace] Python API env change detected, update => '/bin/python3'
12:29:38.658 [trace] Python API env change detected, update => '/usr/bin/python3'
12:29:38.664 [debug] Refreshed Environments
12:29:38.955 [debug] Using notebook.selectKernel to force remote kernel for /opt/docker/conn.ipynb to 053a62a8-f25a-4a2d-9557-2504ebc3223c
12:29:39.200 [trace] Disposing Jupyter Lab Helper
12:29:39.200 [trace] SessionManager - dispose contents manager
12:29:39.200 [trace] ShutdownSessionAndConnection - dispose session manager
12:29:39.201 [trace] Finished disposing Jupyter Lab Helper
12:29:39.201 [trace] UniversalRemoteKernelFinder: Writing 4 remote kernel connection metadata to cache
12:29:39.203 [trace] Disposing Jupyter Lab Helper
12:29:39.203 [trace] SessionManager - dispose contents manager
12:29:39.203 [trace] ShutdownSessionAndConnection - dispose session manager
12:29:39.203 [trace] Finished disposing Jupyter Lab Helper
12:29:39.203 [trace] UniversalRemoteKernelFinder: Writing 4 remote kernel connection metadata to cache
12:29:39.665 [debug] End refreshing Kernel Picker (1722526177698)
12:29:39.670 [debug] KernelProvider switched kernel to id = 57d7c7a601954062906da297b197cd7106dd53fb528bec3de5f3e93f88bea57f..python3./opt/conda/python./.-m#ipykernel_launcher
12:29:39.671 [debug] Controller selection change completed
12:29:39.833 [debug] No interpreter for Pylance for Notebook URI "/Interactive-1.interactive"
12:29:41.016 [warn] Failed to switch remote kernel for /opt/docker/conn.ipynb to 053a62a8-f25a-4a2d-9557-2504ebc3223c
12:29:47.097 [trace] No controller, hence notebook communications cannot be initialized for editor /Interactive-1.interactive
12:29:47.099 [trace] Registering commtarget jupyter.widget
12:29:51.053 [trace] Preferred Remote kernel for /opt/docker/conn.ipynb is 053a62a8-f25a-4a2d-9557-2504ebc3223c
12:29:58.672 [debug] Handle Execution of Cells 0 for /opt/docker/conn.ipynb
12:29:58.675 [trace] Execute Notebook /opt/docker/conn.ipynb. Step 1
12:29:58.676 [trace] Connect to Kernel /opt/docker/conn.ipynb. Step 2
12:29:58.676 [debug] start the kernel, options.disableUI=false for /opt/docker/conn.ipynb
12:29:58.680 [info] Starting Kernel (Python 3 (ipykernel)) for '/opt/docker/conn.ipynb' (disableUI=false)
12:29:58.716 [trace] createNewKernelSession 57d7c7a601954062906da297b197cd7106dd53fb528bec3de5f3e93f88bea57f..python3./opt/conda/python./.-m#ipykernel_launcher
12:29:58.755 [info] http://localhost:8000/user/admin/: Kernel started: c1208230-849e-4724-a918-80204421acef
12:29:58.755 [trace] Waiting for idle on (kernel): c1208230-849e-4724-a918-80204421acef -> unknown
12:29:59.276 [trace] Got status busy in waitForIdleOnSession
12:29:59.278 [trace] Got status idle in waitForIdleOnSession
12:29:59.279 [trace] Finished waiting for idle on (kernel): c1208230-849e-4724-a918-80204421acef -> idle
12:29:59.280 [info] Started session for kernel startUsingRemoteKernelSpec:57d7c7a601954062906da297b197cd7106dd53fb528bec3de5f3e93f88bea57f..python3./opt/conda/python./.-m#ipykernel_launcher
12:29:59.280 [trace] Started running kernel initialization for /opt/docker/conn.ipynb
12:29:59.281 [trace] Executing silently Code (busy) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
12:29:59.343 [trace] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 0 output(s)
12:29:59.344 [trace] Determined IPyWidgets Version as undefined
12:29:59.345 [trace] Executing silently Code (idle) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None):
12:29:59.400 [trace] Executing silently Code (completed) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None): with 0 output(s)
12:29:59.401 [debug] Requesting Kernel info
12:29:59.401 [trace] Got Kernel info
12:29:59.402 [trace] End running kernel initialization, now waiting for idle
12:29:59.402 [trace] Waiting for idle on (kernel): c1208230-849e-4724-a918-80204421acef -> idle
12:29:59.402 [trace] Finished waiting for idle on (kernel): c1208230-849e-4724-a918-80204421acef -> idle
12:29:59.403 [trace] End running kernel initialization, session is idle
12:29:59.403 [debug] Updating preferred kernel for remote notebook c1208230-849e-4724-a918-80204421acef
12:29:59.404 [trace] Registering Kernel Completion Provider from kernel Python 3 (ipykernel) for language python
12:29:59.404 [debug] Start refreshing Kernel Picker (1722526199404)
12:29:59.405 [trace] IPyWidgetScriptSource.initialize
12:29:59.406 [info] Kernel successfully started
12:29:59.411 [trace] Storing Preferred remote kernel for /opt/docker/conn.ipynb is c1208230-849e-4724-a918-80204421acef
12:29:59.412 [trace] Connected to Kernel /opt/docker/conn.ipynb. Step 3
12:29:59.414 [trace] executeCell 0. Step 4
12:29:59.419 [trace] Cell Index:0 sent to kernel
12:29:59.427 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.428 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.430 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.433 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.433 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.435 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.436 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.436 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.438 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.438 [trace] Executing silently Code (idle) = # Copyright (c) Microsoft Corporation. All rights reserved.\n# Licensed under the MIT License.\n# Sou
12:29:59.442 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.471 [trace] Disposing Jupyter Lab Helper
12:29:59.471 [trace] SessionManager - dispose contents manager
12:29:59.472 [trace] ShutdownSessionAndConnection - dispose session manager
12:29:59.472 [trace] Finished disposing Jupyter Lab Helper
12:29:59.473 [trace] UniversalRemoteKernelFinder: Writing 5 remote kernel connection metadata to cache
12:29:59.484 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.486 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.487 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.487 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.487 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.549 [debug] End refreshing Kernel Picker (1722526199404)
```

Thank's for your time.

**Comment by DonJayamanne** [comment]
> 12:29:59.427 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.428 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
12:29:59.430 [error] Exception while handling messages: TypeError: First argument to DataView cons

It is working now, however you are now running into another issue.
https://github.com/microsoft/vscode-jupyter-hub/issues/64

**Comment by joseph-siefert** [comment]
That makes sense based on the errors I am seeing. On another server I am able to get it working with JupyterHub, but I need it working with Jupyter lab, as JupyterHub is not installed on this particular server

**Comment by joseph-siefert** [comment]
Any update on this? Issue still persists in the latest prerelease version
