### ISSUE TITLE
Python language server never starts properly the first time the notebook is opened

### ISSUE THREAD

**Issue by guidocioni** [microsoft/vscode-jupyter#16526]
## Environment data

-   VS Code version: 1.98.2
-   Jupyter Extension version: v2025.2.0
-   Python Extension version : 2025.2.0
-   OS (Windows | Mac | Linux distro) and version: MacOS 13.7.4
-   Python and/or Anaconda version: 3.12.8
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Behaviour

I'm quite puzzled as to why never reported this issue because I've been seeing it for months on different machines. 
Basically **EVERY** time I open a Notebook for the first time, the Python Language Server is not initialized correctly and this basically makes the whole IntelliSense part useless. The Notebook functionality is not affected though. 

See as example this video capture. 

https://github.com/user-attachments/assets/d73ff5e2-c51b-44cd-b4ac-ad3107cdfe76

What I'm doing is
- Opening a Notebook where a simple `pandas` import is done to show the package version.
- Even though the `default` environment is activated (and this environment has `pandas` installed), IntelliSense shows a message `Import pandas could not be resolved from source` 
- Switching to `base` environment shows the same message, and this is expected because `pandas` is not installed there
- Switching back to `default` correctly loads the language server, and the message disappears (as expected because `pandas` is installed in this env).

Notes:
- Restarting the extensions host does solve the issue
- Leaving the VsCode window open and re-opening the Notebook does not cause the issue to appear (probably because the Extensions has been already restarted)
- Restarting the Python Language Server does not solve the issue 

My guess is that there is something preventing the Extension to start properly the first time but I do not seem anything particular from the logs... 
What could I look into to understand better where the issue is coming from? 

Here are detailed logs of the python language server

<details>

```
2025-04-02 10:10:31.106 [info] [Info  - 10:10:31 AM] (56418) Starting service instance "<default>"
2025-04-02 10:10:31.211 [info] [Info  - 10:10:31 AM] (56418) Setting environmentName for service "<default>": "3.12.8 (default conda)"
2025-04-02 10:10:31.211 [info] [Info  - 10:10:31 AM] (56418) Setting pythonPath for service "<default>": "/Users/guidocioni/miniforge3/envs/default/bin/python"
2025-04-02 10:10:31.212 [info] [Info  - 10:10:31 AM] (56418) No include entries specified; assuming /<default workspace root>
2025-04-02 10:10:31.212 [info] [Info  - 10:10:31 AM] (56418) Auto-excluding **/node_modules
2025-04-02 10:10:31.212 [info] [Info  - 10:10:31 AM] (56418) Auto-excluding **/__pycache__
2025-04-02 10:10:31.212 [info] [Info  - 10:10:31 AM] (56418) Auto-excluding **/.*
2025-04-02 10:10:31.260 [info] [Info  - 10:10:31 AM] (56418) Assuming Python version 3.12.8.final.0
2025-04-02 10:10:31.332 [info] [Error - 10:10:31 AM] (56418) File or directory "/<default workspace root>" does not exist.
2025-04-02 10:10:31.333 [info] [Info  - 10:10:31 AM] (56418) No source files found.
2025-04-02 10:10:31.346 [info] [Info  - 10:10:31 AM] (56418) Starting service instance "<default>"
2025-04-02 10:10:31.350 [info] [Info  - 10:10:31 AM] (56418) Setting environmentName for service "<default>": "3.12.8 (default conda)"
2025-04-02 10:10:31.350 [info] [Info  - 10:10:31 AM] (56418) Setting pythonPath for service "<default>": "/Users/guidocioni/miniforge3/envs/default/bin/python"
2025-04-02 10:10:31.350 [info] [Info  - 10:10:31 AM] (56418) No include entries specified; assuming /<default workspace root>
2025-04-02 10:10:31.350 [info] [Info  - 10:10:31 AM] (56418) Auto-excluding **/node_modules
2025-04-02 10:10:31.350 [info] [Info  - 10:10:31 AM] (56418) Auto-excluding **/__pycache__
2025-04-02 10:10:31.350 [info] [Info  - 10:10:31 AM] (56418) Auto-excluding **/.*
2025-04-02 10:10:31.375 [info] [Info  - 10:10:31 AM] (56418) Assuming Python version 3.12.8.final.0
2025-04-02 10:10:31.416 [info] [Error - 10:10:31 AM] (56418) File or directory "/<default workspace root>" does not exist.
2025-04-02 10:10:31.416 [info] [Info  - 10:10:31 AM] (56418) No source files found.
2025-04-02 10:10:31.431 [info] [Info  - 10:10:31 AM] (56418) Setting environmentName for service "<default>": "3.12.8 (default conda)"
2025-04-02 10:10:31.431 [info] [Info  - 10:10:31 AM] (56418) Setting pythonPath for service "<default>": "/Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist"
2025-04-02 10:10:31.431 [info] [Info  - 10:10:31 AM] (56418) No include entries specified; assuming /<default workspace root>
2025-04-02 10:10:31.431 [info] [Info  - 10:10:31 AM] (56418) Auto-excluding **/node_modules
2025-04-02 10:10:31.432 [info] [Info  - 10:10:31 AM] (56418) Auto-excluding **/__pycache__
2025-04-02 10:10:31.432 [info] [Info  - 10:10:31 AM] (56418) Auto-excluding **/.*
2025-04-02 10:10:31.457 [info] [Error - 10:10:31 AM] (56418) File or directory "/<default workspace root>" does not exist.
2025-04-02 10:10:31.457 [info] [Info  - 10:10:31 AM] (56418) No source files found.
2025-04-02 10:10:31.755 [info] [Info  - 10:10:31 AM] (56418) Priority queue background worker(2) root directory: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-04-02 10:10:31.755 [info] [Info  - 10:10:31 AM] (56418) Priority queue background worker(2) started
2025-04-02 10:10:31.887 [info] [Info  - 10:10:31 AM] (56418) Priority queue background worker(4) root directory: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-04-02 10:10:31.887 [info] [Info  - 10:10:31 AM] (56418) Priority queue background worker(4) started

```

</details>

**Comment by DonJayamanne** [comment]
@rchiodo Please can you have a look.

**Comment by rchiodo** [comment]
What's your version of Pylance? This could be this issue here:
https://github.com/microsoft/pylance-release/issues/7045

There was a problem with responding to kernel changes which should be fixed in our latest prerelease bits. I can't reproduce this issue with our latest Pylance prerelease bits.

**Comment by guidocioni** [comment]
> What's your version of Pylance? This could be this issue here: [microsoft/pylance-release#7045](https://github.com/microsoft/pylance-release/issues/7045)
> 
> There was a problem with responding to kernel changes which should be fixed in our latest prerelease bits. I can't reproduce this issue with our latest Pylance prerelease bits.

I just installed Pylance 2025.3.105 and I still see the same behaviour. Opening for the first time doesn't properly load the language server. Right now I excluded all python environments but one so when I open the notebook it auto selects default, I don't know if this is another edge case... 
After selecting again default in the kernel picker it starts to work properly. 

https://github.com/user-attachments/assets/7d35bc58-e11f-46ec-9bb1-d218dac6ead8

**Comment by guidocioni** [comment]
> That seems different. Not even sure how you get a 'default' kernel? When I create a notebook, I just get this:
> 
> ![Image](https://github.com/user-attachments/assets/2b11a9f3-9c92-4907-919f-2d0d2316ae67)
> 
> Which would show those pandas errors until we receive a kernel selection event.
> 
> [@DonJayamanne](https://github.com/DonJayamanne) we still use the jupyter extension's API to get the kernel for a notebook on open. Would that return this default kernel?

Default is the name of a conda env, the one that i always use to run Jupyter notebooks 😉
It gets auto selected at start in my case because I disabled all other python environments (see the comment befor about jupyter.kernels.excludePythonEnvironments)

**Comment by rchiodo** [comment]
> Could it be that, in case the kernel is not selected from the user but auto selected by vscode, then no update event is triggered?

That's likely, but I wouldn't expect an update on open. There should just be a value returned when we ask for the 'current' kernel. This works fine on saved notebooks (they don't need an update event after open), so I suspect the API we call in the jupyter extension isn't handling this default case for some reason.

**Comment by guidocioni** [comment]
> > Could it be that, in case the kernel is not selected from the user but auto selected by vscode, then no update event is triggered?
> 
> That's likely, but I wouldn't expect an update on open. There should just be a value returned when we ask for the 'current' kernel. This works fine on saved notebooks (they don't need an update event after open), so I suspect the API we call in the jupyter extension isn't handling this default case for some reason.

Is the kernel picked supposed to be persisted? Because one of the reason why I excluded the other python interpreters is exactly because every time I open the notebook I have to select the kernel again and again...

**Comment by rchiodo** [comment]
Yeah it's supposed to be persisted on save.

**Comment by guidocioni** [comment]
> Yeah it's supposed to be persisted on save.

Ok then it's yet another issue ... Do you know how to understand why that is not happening?
But anyway do you think what I'm seeing is expected behavior or not?

**Comment by rchiodo** [comment]
Kernel save works for me, so not sure what the issue would be. Should probably enter a separate issue.

I wouldn't say the 'default' not working would be by design though. It should work. I need to repro to see if it's a problem in the Jupyter extension or the Pylance extension.

**Comment by rchiodo** [comment]
What exactly do you put for the 'excludePythonEnvironments'? It's very vague about how it matches.

**Comment by guidocioni** [comment]
> Kernel save works for me, so not sure what the issue would be. Should probably enter a separate issue.
> 

> I wouldn't say the 'default' not working would be by design though. It should work. I need to repro to see if it's a problem in the Jupyter extension or the Pylance extension.

I think you should be able te reproduce by just excluding all python interpreters besides the one you want. However, if you don't have any save issue in theory in your case it will automatically load that kernel anwyay so I'm not sure it is useful. 

Just to understand better, once you save a notebook with a kernel and then you reopen it, it then automatically select that kernel and correctly use this as interpreter in pylance? 

The only difference I could think about is that I have multiple conda environments, and the base one is NOT the one I'm using for jupyter. Maybe you only have 1 python installation? Which means it will always load the right one no matters what....

**Comment by guidocioni** [comment]
> What exactly do you put for the 'excludePythonEnvironments'? It's very vague about how it matches.

I agree, the doc is not really clear. You need the full path to the python binary.

**Comment by rchiodo** [comment]
I have about 50 environments, 3.9 to 3.13 so I don't think it's defaulting to the correct one. It is giving back the one I saved when I picked it the first time. I can see it in the Pylance output tab.

**Comment by guidocioni** [comment]
> I have about 50 environments, 3.9 to 3.13 so I don't think it's defaulting to the correct one. It is giving back the one I saved when I picked it the first time. I can see it in the Pylance output tab.

I see the same in the pylance logs, but the fact that it doesn't find pandas made me think it was picking the wrong one. Not sure if that's the case though

**Comment by rchiodo** [comment]
Pylance output should show a 'Could not resolve' message for pandas. That log output then shows what paths it searched. That's how can tell if it's not getting the correct kernel because the sys.paths will be for a different interpreter.

**Comment by rchiodo** [comment]
Here's save working for me:

https://github.com/user-attachments/assets/142738f0-9f4a-4666-9279-c250a8c5e3eb

**Comment by rchiodo** [comment]
Save has been working for as long as I can remember. Are you using a workspace or are these just loose files?

Sorry I think the import resolution errors require this:

```
"python.analysis.logLevel": "Trace"
```

**Comment by guidocioni** [comment]
> Save has been working for as long as I can remember. Are you using a workspace or are these just loose files?
> 
> Sorry I think the import resolution errors require this:
> 
> ```
> "python.analysis.logLevel": "Trace"
> ```

I almost exclusively work with loose files. 

Do you see anything weird in this logs? 

<details>

2025-04-02 21:10:16.450 [info] (Client) Pylance async client (2025.3.105) started with python extension (2025.2.0)
2025-04-02 21:10:16.870 [info] [Info  - 9:10:16 PM] (87541) Server root directory: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist
2025-04-02 21:10:16.876 [info] [Info  - 9:10:16 PM] (87541) Pylance language server 2025.3.105 (pyright version 1.1.398, commit 4f24eccc) starting
2025-04-02 21:10:16.901 [info] [Info  - 9:10:16 PM] (87541) Starting service instance "<default>" for workspace ""
2025-04-02 21:10:16.920 [info] (87541) No pyproject.toml file found.
2025-04-02 21:10:16.920 [info] [Info  - 9:10:16 PM] (87541) Setting environmentName for service "<default>": "3.12.8 (default conda)"
2025-04-02 21:10:16.920 [info] [Info  - 9:10:16 PM] (87541) Setting pythonPath for service "<default>": "/Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist"
2025-04-02 21:10:16.920 [info] [Info  - 9:10:16 PM] (87541) No include entries specified; assuming /<default workspace root>
2025-04-02 21:10:16.920 [info] [Info  - 9:10:16 PM] (87541) Auto-excluding **/node_modules
2025-04-02 21:10:16.920 [info] [Info  - 9:10:16 PM] (87541) Auto-excluding **/__pycache__
2025-04-02 21:10:16.920 [info] [Info  - 9:10:16 PM] (87541) Auto-excluding **/.*
2025-04-02 21:10:16.920 [info] (87541) Assuming Python platform Darwin
2025-04-02 21:10:16.940 [info] [Info  - 9:10:16 PM] (87541) Execution environment: 3.12.8 (default conda)
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)   Extra paths:
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)     (none)
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)   Python version: 3.13
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)   Python platform: Darwin
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)   Search paths:
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)     /Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)     /<default workspace root>
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)     /<default workspace root>/typings
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)     /Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stubs/...
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541)     /Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs
2025-04-02 21:10:16.941 [info] [Info  - 9:10:16 PM] (87541) Adding fs watcher for directories:
 file:///%3Cdefault%20workspace%20root%3E
2025-04-02 21:10:16.941 [info] (87541) Searching for source files
2025-04-02 21:10:16.941 [info] [Error - 9:10:16 PM] (87541) File or directory "/<default workspace root>" does not exist.
2025-04-02 21:10:16.942 [info] [Info  - 9:10:16 PM] (87541) No source files found.
2025-04-02 21:10:16.947 [info] (87541) Adding fs watcher for files:
 file:///%3Cdefault%20workspace%20root%3E/requirements.txt
file:///%3Cdefault%20workspace%20root%3E/pyproject.toml
2025-04-02 21:10:16.948 [info] (87541) pytest configurations: {"message":"script","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2025-04-02 21:10:16.959 [info] (87541) [IDX(FG)] index libraries file:///%3Cdefault%20workspace%20root%3E (index) ...
2025-04-02 21:10:16.959 [info] (87541) [IDX(FG)]   read stdlib indices (8ms)
2025-04-02 21:10:16.960 [info] (87541) [IDX(FG)] index libraries file:///%3Cdefault%20workspace%20root%3E (index) [succeed] (9ms)
2025-04-02 21:10:16.968 [info] (87541) Attempting to resolve using local imports: __builtins__
2025-04-02 21:10:16.968 [info] (87541) Attempting to resolve using root path 'file:///Users/guidocioni/Downloads'
2025-04-02 21:10:16.970 [info] (87541) [FG] parsing: vscode-notebook-cell:/Users/guidocioni/Downloads/test.ipynb#W0sZmlsZQ%3D%3D (9ms)
2025-04-02 21:10:16.970 [info] [Info  - 9:10:16 PM] (87541) Could not resolve source for 'pandas' in file '/Users/guidocioni/Downloads/test.ipynb.py'
2025-04-02 21:10:16.970 [info] [Info  - 9:10:16 PM] (87541)   Looking in root directory of execution environment 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:16.970 [info] [Info  - 9:10:16 PM] (87541)   Attempting to resolve using root path 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:16.970 [info] [Info  - 9:10:16 PM] (87541)   Finding python search paths
2025-04-02 21:10:16.970 [info] [Info  - 9:10:16 PM] (87541)   Executing interpreter: '/Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist'
2025-04-02 21:10:16.970 [info] [Info  - 9:10:16 PM] (87541)   Received 0 paths from interpreter
2025-04-02 21:10:16.970 [info] [Info  - 9:10:16 PM] (87541)   No python interpreter search path
2025-04-02 21:10:16.971 [info] (87541) [FG] parsing: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell (1ms)
2025-04-02 21:10:16.971 [info] [Info  - 9:10:16 PM] (87541) Could not resolve source for 'IPython.display' in file '/Users/guidocioni/Downloads/test.ipynb.py'
2025-04-02 21:10:16.971 [info] [Info  - 9:10:16 PM] (87541)   Looking in root directory of execution environment 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:16.971 [info] [Info  - 9:10:16 PM] (87541)   Attempting to resolve using root path 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:16.971 [info] [Info  - 9:10:16 PM] (87541)   Finding python search paths
2025-04-02 21:10:16.971 [info] [Info  - 9:10:16 PM] (87541)   Executing interpreter: '/Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist'
2025-04-02 21:10:16.971 [info] [Info  - 9:10:16 PM] (87541)   Received 0 paths from interpreter
2025-04-02 21:10:16.971 [info] [Info  - 9:10:16 PM] (87541)   No python interpreter search path
2025-04-02 21:10:17.007 [info] (87541) [FG] parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 1ms] (35ms)
2025-04-02 21:10:17.027 [info] (87541) [FG] binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/builtins.pyi (20ms)
2025-04-02 21:10:17.028 [info] (87541) [FG] binding: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell ...
2025-04-02 21:10:17.028 [info] (87541) [FG]   parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/display.pyi [fs read 0ms] (1ms)
2025-04-02 21:10:17.030 [info] (87541) [FG]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/display.pyi ...
2025-04-02 21:10:17.030 [info] (87541) [FG]     parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/core/display_functions.pyi [fs read 0ms] (2ms)
2025-04-02 21:10:17.030 [info] (87541) [FG]     binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/core/display_functions.pyi (0ms)
2025-04-02 21:10:17.032 [info] (87541) [FG]     parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/lib/display.pyi [fs read 1ms] (2ms)
2025-04-02 21:10:17.033 [info] (87541) [FG]     binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/lib/display.pyi (0ms)
2025-04-02 21:10:17.033 [info] (87541) [FG]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/display.pyi (4ms)
2025-04-02 21:10:17.033 [info] (87541) [FG] binding: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell (6ms)
2025-04-02 21:10:17.033 [info] (87541) [FG] binding: vscode-notebook-cell:/Users/guidocioni/Downloads/test.ipynb#W0sZmlsZQ%3D%3D (0ms)
2025-04-02 21:10:17.035 [info] (87541) pytest configurations: {"message":"spawn /Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist ENOENT","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2025-04-02 21:10:17.263 [info] (87541) [FG] parsing: vscode-notebook-cell:/Users/guidocioni/Downloads/test.ipynb#W0sZmlsZQ%3D%3D (0ms)
2025-04-02 21:10:17.263 [info] [Info  - 9:10:17 PM] (87541) Could not resolve source for 'pandas' in file '/Users/guidocioni/Downloads/test.ipynb.py'
2025-04-02 21:10:17.263 [info] [Info  - 9:10:17 PM] (87541)   Looking in root directory of execution environment 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:17.263 [info] [Info  - 9:10:17 PM] (87541)   Attempting to resolve using root path 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   Finding python search paths
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   Executing interpreter: '/Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist'
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   Received 0 paths from interpreter
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   No python interpreter search path
2025-04-02 21:10:17.264 [info] (87541) [FG] parsing: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell (0ms)
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541) Could not resolve source for 'IPython.display' in file '/Users/guidocioni/Downloads/test.ipynb.py'
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   Looking in root directory of execution environment 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   Attempting to resolve using root path 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   Finding python search paths
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   Executing interpreter: '/Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist'
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   Received 0 paths from interpreter
2025-04-02 21:10:17.264 [info] [Info  - 9:10:17 PM] (87541)   No python interpreter search path
2025-04-02 21:10:17.287 [info] (87541) [FG] parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 1ms] (24ms)
2025-04-02 21:10:17.295 [info] (87541) [FG] binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/builtins.pyi (7ms)
2025-04-02 21:10:17.295 [info] (87541) [FG] binding: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell ...
2025-04-02 21:10:17.295 [info] (87541) [FG]   parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/display.pyi [fs read 0ms] (0ms)
2025-04-02 21:10:17.295 [info] (87541) [FG]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/display.pyi ...
2025-04-02 21:10:17.295 [info] (87541) [FG]     parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/core/display_functions.pyi [fs read 0ms] (0ms)
2025-04-02 21:10:17.296 [info] (87541) [FG]     binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/core/display_functions.pyi (1ms)
2025-04-02 21:10:17.296 [info] (87541) [FG]     parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/lib/display.pyi [fs read 0ms] (0ms)
2025-04-02 21:10:17.296 [info] (87541) [FG]     binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/lib/display.pyi (0ms)
2025-04-02 21:10:17.296 [info] (87541) [FG]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/display.pyi (1ms)
2025-04-02 21:10:17.296 [info] (87541) [FG] binding: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell (1ms)
2025-04-02 21:10:17.296 [info] (87541) [FG] binding: vscode-notebook-cell:/Users/guidocioni/Downloads/test.ipynb#W0sZmlsZQ%3D%3D (0ms)
2025-04-02 21:10:17.300 [info] (87541) BG: Task background runner(1) root directory: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist
2025-04-02 21:10:17.300 [info] (87541) BG: Task background runner(1) started
2025-04-02 21:10:17.300 [info] [Info  - 9:10:17 PM] (87541) BG: Priority queue background worker(2) root directory: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist
2025-04-02 21:10:17.300 [info] [Info  - 9:10:17 PM] (87541) BG: Priority queue background worker(2) started
2025-04-02 21:10:17.314 [info] (87541) BG: pytest configurations: {"message":"request cancelled","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2025-04-02 21:10:17.314 [info] (87541) BG: pytest configurations: {"message":"spawn /Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist ENOENT","classes":["Test"],"files":["test_*.py","*_test.py"],"functions":["test"]}
2025-04-02 21:10:17.327 [info] (87541) BG: Attempting to resolve using local imports: __builtins__
2025-04-02 21:10:17.327 [info] (87541) BG: Attempting to resolve using root path 'file:///Users/guidocioni/Downloads'
2025-04-02 21:10:17.329 [info] (87541) BG: [BG(1)] SemanticTokens full at file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D ...
2025-04-02 21:10:17.329 [info] (87541) BG: [BG(1)]   parsing: file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D (14ms)
2025-04-02 21:10:17.329 [info] [Info  - 9:10:17 PM] (87541) BG: Could not resolve source for 'pandas' in file '/Users/guidocioni/Downloads/test.ipynb.py'
2025-04-02 21:10:17.329 [info] [Info  - 9:10:17 PM] (87541) BG:   Looking in root directory of execution environment 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:17.329 [info] [Info  - 9:10:17 PM] (87541) BG:   Attempting to resolve using root path 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:17.329 [info] [Info  - 9:10:17 PM] (87541) BG:   Finding python search paths
2025-04-02 21:10:17.329 [info] [Info  - 9:10:17 PM] (87541) BG:   Executing interpreter: '/Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist'
2025-04-02 21:10:17.329 [info] [Info  - 9:10:17 PM] (87541) BG:   Received 0 paths from interpreter
2025-04-02 21:10:17.329 [info] [Info  - 9:10:17 PM] (87541) BG:   No python interpreter search path
2025-04-02 21:10:17.330 [info] (87541) BG: [BG(1)]   parsing: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell (1ms)
2025-04-02 21:10:17.330 [info] [Info  - 9:10:17 PM] (87541) BG: Could not resolve source for 'IPython.display' in file '/Users/guidocioni/Downloads/test.ipynb.py'
2025-04-02 21:10:17.330 [info] [Info  - 9:10:17 PM] (87541) BG:   Looking in root directory of execution environment 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:17.330 [info] [Info  - 9:10:17 PM] (87541) BG:   Attempting to resolve using root path 'file:///%3Cdefault%20workspace%20root%3E'
2025-04-02 21:10:17.330 [info] [Info  - 9:10:17 PM] (87541) BG:   Finding python search paths
2025-04-02 21:10:17.330 [info] [Info  - 9:10:17 PM] (87541) BG:   Executing interpreter: '/Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist'
2025-04-02 21:10:17.330 [info] [Info  - 9:10:17 PM] (87541) BG:   Received 0 paths from interpreter
2025-04-02 21:10:17.330 [info] [Info  - 9:10:17 PM] (87541) BG:   No python interpreter search path
2025-04-02 21:10:17.364 [info] (87541) BG: [BG(1)]   parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 1ms] (34ms)
2025-04-02 21:10:17.375 [info] (87541) BG: [BG(1)]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/builtins.pyi (10ms)
2025-04-02 21:10:17.377 [info] (87541) BG: [BG(1)]   binding: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell ...
2025-04-02 21:10:17.377 [info] (87541) BG: [BG(1)]     parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/display.pyi [fs read 0ms] (2ms)
2025-04-02 21:10:17.379 [info] (87541) BG: [BG(1)]     binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/display.pyi ...
2025-04-02 21:10:17.379 [info] (87541) BG: [BG(1)]       parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/core/display_functions.pyi [fs read 0ms] (2ms)
2025-04-02 21:10:17.380 [info] (87541) BG: [BG(1)]       binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/core/display_functions.pyi (0ms)
2025-04-02 21:10:17.380 [info] (87541) BG: [BG(1)]       parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/lib/display.pyi [fs read 0ms] (1ms)
2025-04-02 21:10:17.381 [info] (87541) BG: [BG(1)]       binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/lib/display.pyi (1ms)
2025-04-02 21:10:17.381 [info] (87541) BG: [BG(1)]     binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/display.pyi (4ms)
2025-04-02 21:10:17.381 [info] (87541) BG: [BG(1)]   binding: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell (6ms)
2025-04-02 21:10:17.381 [info] (87541) BG: [BG(1)]   binding: file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D (0ms)
2025-04-02 21:10:17.390 [info] (87541) BG: [BG(1)]   parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (7ms)
2025-04-02 21:10:17.394 [info] (87541) BG: [BG(1)]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/typing.pyi (3ms)
2025-04-02 21:10:17.395 [info] (87541) BG: [BG(1)] SemanticTokens full at file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D (80ms)
2025-04-02 21:10:17.403 [info] (87541) BG: [BG(1)] SemanticTokens range 0:0 - 1:14 at file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D ...
2025-04-02 21:10:17.403 [info] (87541) BG: [BG(1)]   parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/types.pyi [fs read 0ms] (3ms)
2025-04-02 21:10:17.406 [info] (87541) BG: [BG(1)]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/types.pyi (3ms)
2025-04-02 21:10:17.409 [info] (87541) BG: [BG(1)]   parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (1ms)
2025-04-02 21:10:17.410 [info] (87541) BG: [BG(1)]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (1ms)
2025-04-02 21:10:17.412 [info] (87541) BG: [BG(1)]   parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (0ms)
2025-04-02 21:10:17.413 [info] (87541) BG: [BG(1)]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/typeshed-fallback/stdlib/abc.pyi (1ms)
2025-04-02 21:10:17.414 [info] (87541) BG: [BG(1)]   parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/pandas/__init__.pyi [fs read 0ms] (1ms)
2025-04-02 21:10:17.415 [info] (87541) BG: [BG(1)]   binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/pandas/__init__.pyi (0ms)
2025-04-02 21:10:17.416 [info] (87541) BG: [BG(1)] SemanticTokens range 0:0 - 1:14 at file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D (20ms)
2025-04-02 21:10:17.417 [info] (87541) BG: [BG(1)] SemanticTokens full at file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D (0ms)
2025-04-02 21:10:17.424 [info] (87541) BG: [BG(1)] analyzing: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell ...
2025-04-02 21:10:17.424 [info] (87541) BG: [BG(1)]   analyzing: file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D ...
2025-04-02 21:10:17.424 [info] (87541) BG: [BG(1)]     checking: file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D (6ms)
2025-04-02 21:10:17.424 [info] (87541) BG: [BG(1)]   analyzing: file:///Users/guidocioni/Downloads/test.ipynb.py#W0sZmlsZQ%3D%3D (7ms)
2025-04-02 21:10:17.425 [info] (87541) BG: [BG(1)]   checking: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell ...
2025-04-02 21:10:17.425 [info] (87541) BG: [BG(1)]     parsing: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/core/display.pyi [fs read 0ms] (1ms)
2025-04-02 21:10:17.426 [info] (87541) BG: [BG(1)]     binding: file:///Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist/bundled/stubs/IPython-stubs/core/display.pyi (1ms)
2025-04-02 21:10:17.426 [info] (87541) BG: [BG(1)]   checking: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell (2ms)
2025-04-02 21:10:17.426 [info] (87541) BG: [BG(1)] analyzing: file:///Users/guidocioni/Downloads/test.ipynb.py#pylancePrefixCell (9ms)

</details>

**Comment by rchiodo** [comment]
This is weird:

Executing interpreter: '/Users/guidocioni/.vscode/extensions/ms-python.vscode-pylance-2025.3.105/dist'

That's like the python path is set to the current folder.

**Comment by rchiodo** [comment]
Loose files work for me too if I save the notebook.

**Comment by guidocioni** [comment]
Ok I'm at a loss as I've tried almost everything on my side.
I know you can't reproduce on your end but could you at least point me in the right direction and tell me what I could try further?
thanks 😉

**Comment by rchiodo** [comment]
What's your defaultInterpreterPath? Maybe that's messing things up. I don't have it set.

**Comment by guidocioni** [comment]
> What's your defaultInterpreterPath? Maybe that's messing things up. I don't have it set.

I already tried removing that, it doesn't help.

Are you by any chance never closing the window where you're loading the notebooks? Because, as I wrote at the beginning of the post, the problem is loading the notebook **THE FIRST TIME**. If you keep the window open after selecting the right kernel then it will work. Also I cannot see from your screen capture whether you're on Window or MacOS.

I was able to reproduce the issue in a FRESH copy of VsCode installed in portable mode on yet another machine (so that's the third one). In this copy my `settings.json` is basically empty (besides  `"security.workspace.trust.untrustedFiles": "open"` ) and the only extensions I installed are Jupyter and Python.

Look at the following screen capture. 

https://github.com/user-attachments/assets/c3bb3b58-e78d-4bd8-8eef-7220b1fe6bbe

I'm performing the following operations:

1. Open VSCode
2. Open Notebook for the first time. Kernel is not chosen, so Pylance cannot find Pandas: this is expected. 
3. I select the right kernel, then Pylance does not show warning anymore: this is also fine
4. Closing and reopening the notebook IN THE SAME WINDOW works just fine as the kernel is persisted
5. I open a NEW WINDOW in the same VsCode instance
6. I open the same notebook, the kernel is not persisted, which means I have to select it again and start from point 1.

In order to force this kernel to be used (regardless of the saved notebook, ALWAYS when I open a new window) I tried again to  add all other python interpreters to `jupyter.kernels.excludePythonEnvironments` also in this installation. This again does not work when I open the notebook the first time: even though the `default` kernel is selected automatically by vscode (as there are no other kernels available), I still need to select it again to make it recognizable by Pylance. So we go back to the issue described here in the first comment.

Please try again to properly reproduce the bug by opening a new window and not always re-use the same one where you already picked the kernel once. 

I agree this is not a major issue, but I would expect first of all VsCode to load the right kernel whenever I open a saved notebook and Pylance to recognize that, no matter how this kernel has been set the first time.

**Comment by rchiodo** [comment]
I believe on reopening a loose file VS code doesn't save the kernel. It would only do that if you opened a workspace as the workspace is used as a key for the 'kernel' information in the cache. But I believe that's up to the Jupyter extension. It's the one I believe that is caching this information. 

I can reproduce that problem myself.

**Comment by guidocioni** [comment]
> I believe on reopening a loose file VS code doesn't save the kernel. It would only do that if you opened a workspace as the workspace is used as a key for the 'kernel' information in the cache. But I believe that's up to the Jupyter extension. It's the one I believe that is caching this information.
> 
> I can reproduce that problem myself.

ok I understand this is an intended behavior and not a bug, but then shouldn't the language server properly load in case the kernel is picked automatically at the beginning (by excluding all the others)?

**Comment by rchiodo** [comment]
That's the part I haven't reproduced yet. Figuring out the path to all of my interpreters is going to take a while.

**Comment by guidocioni** [comment]
> That's the part I haven't reproduced yet. Figuring out the path to all of my interpreters is going to take a while.

Once you start entering the environment path in the Json file and use comma it will give you the list automatically.
Also you can screenshot the list from the python interpreters list and the copy paste the paths with ocr (preview does that automatically) 😄

**Comment by rchiodo** [comment]
I created a new VM and was able to reproduce the issue. The Jupyter extension isn't returning a notebook kernel in this scenario.

We make this api call here and it returns empty when the notebook first opens:
https://github.com/microsoft/vscode-jupyter/blob/39422a9412a17c627f209ada37cd537ed390ce9d/src/standalone/intellisense/notebookPythonPathService.node.ts#L92

It looks like the extension then sets the kernel to a default value but then doesn't fire a environment changed event.

**Comment by DonJayamanne** [comment]
@rchiodo Can you use the Python extension API instead of using this callback, the plan is to stop using this hook.
I.e. use what was done here https://github.com/microsoft/vscode-jupyter/issues/15987
https://github.com/microsoft/vscode-python/pull/24771

I believe that will fix this issue, if it doesn't, then we can work on fixing that code instead of this older approach (which we want to depreccate)

**Comment by rchiodo** [comment]
Looks like that should work. Submitting a PR:
https://github.com/microsoft/pyrx/pull/6498

**Comment by rchiodo** [comment]
> Why isn't possible to use the kernel name stored in the metadata of the ipynb file to persist it even in a new editor window instead of relying on the workspace?

If I recall correctly there were two reasons:

- A need to not modify the file just because you picked a kernel. Running would cause a file change, but picking a kernel shouldn't as it may be the default situation you're in (where you didn't consciously `pick` a kernel).
- The kernel metadata wasn't unique enough to identify the correct environment.

**Comment by guidocioni** [comment]
@rchiodo something I also noticed (I don't know if it is related to this issue or not) is that when the notebook is loaded as part of a workspace (e.g. by dragging a folder opened already before into VsCode) then the language server has different syntax highlighting.

For example this is the same notebook loaded as part of a workspace/folder (in this case I didn't have to select the kernel as it was auto-selected as part of the workspace auto-saving feature you described)

![Image](https://github.com/user-attachments/assets/72ab5c9f-d400-41ad-8430-435847655dcb)

Associated logs
<details>

```
2025-04-09 09:11:59.161 [info] (Client) Pylance async client (2025.4.1) started with python extension (2025.4.0)
2025-04-09 09:12:00.159 [info] [Info  - 09:12:00] (99582) Server root directory: file:///Users/thd5tt/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist
2025-04-09 09:12:00.160 [info] [Info  - 09:12:00] (99582) Pylance language server 2025.4.1 (pyright version 1.1.398, commit 4f24eccc) starting
2025-04-09 09:12:00.166 [info] [Info  - 09:12:00] (99582) Starting service instance "forecast_stability" for workspace "/Users/thd5tt/Documents/forecast_stability"
2025-04-09 09:12:00.274 [info] [Info  - 09:12:00] (99582) Setting environmentName for service "forecast_stability": "3.11.11 (default conda)"
2025-04-09 09:12:00.274 [info] [Info  - 09:12:00] (99582) Setting pythonPath for service "forecast_stability": "/Users/thd5tt/miniconda3/envs/default/bin/python"
2025-04-09 09:12:00.274 [info] [Info  - 09:12:00] (99582) No include entries specified; assuming /Users/thd5tt/Documents/forecast_stability
2025-04-09 09:12:00.276 [info] [Info  - 09:12:00] (99582) Auto-excluding **/node_modules
2025-04-09 09:12:00.277 [info] [Info  - 09:12:00] (99582) Auto-excluding **/__pycache__
2025-04-09 09:12:00.277 [info] [Info  - 09:12:00] (99582) Auto-excluding **/.*
2025-04-09 09:12:00.380 [info] [Info  - 09:12:00] (99582) Assuming Python version 3.11.11.final.0
2025-04-09 09:12:00.638 [info] [Info  - 09:12:00] (99582) Found 20 source files
2025-04-09 09:12:00.669 [info] [Info  - 09:12:00] (99582) Setting environmentName for service "forecast_stability": "3.11.11 (default conda)"
2025-04-09 09:12:00.669 [info] [Info  - 09:12:00] (99582) Setting pythonPath for service "forecast_stability": "/Users/thd5tt/miniconda3/envs/default/bin/python"
2025-04-09 09:12:00.670 [info] [Info  - 09:12:00] (99582) No include entries specified; assuming /Users/thd5tt/Documents/forecast_stability
2025-04-09 09:12:00.671 [info] [Info  - 09:12:00] (99582) Auto-excluding **/node_modules
2025-04-09 09:12:00.671 [info] [Info  - 09:12:00] (99582) Auto-excluding **/__pycache__
2025-04-09 09:12:00.672 [info] [Info  - 09:12:00] (99582) Auto-excluding **/.*
2025-04-09 09:12:00.779 [info] [Info  - 09:12:00] (99582) Assuming Python version 3.11.11.final.0
2025-04-09 09:12:00.981 [info] [Info  - 09:12:00] (99582) Found 20 source files
2025-04-09 09:12:01.432 [info] [Info  - 09:12:01] (99582) BG: Priority queue background worker(2) root directory: file:///Users/thd5tt/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist
2025-04-09 09:12:01.432 [info] [Info  - 09:12:01] (99582) BG: Priority queue background worker(2) started
2025-04-09 09:12:01.878 [info] [Info  - 09:12:01] (99582) BG: Indexer background runner(3) root directory: file:///Users/thd5tt/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist (index)
2025-04-09 09:12:01.878 [info] [Info  - 09:12:01] (99582) BG: Indexing(3) started
2025-04-09 09:12:03.933 [info] [Info  - 09:12:03] (99582) BG: scanned(3) 541 files over 1 exec env
2025-04-09 09:12:04.369 [info] [Info  - 09:12:04] (99582) BG: indexed(3) 541 files over 1 exec env
2025-04-09 09:12:04.509 [info] [Info  - 09:12:04] (99582) BG: Indexing finished(3).
```

</details>

and here it is loaded as single file into VsCode (in this case I had to manually select the kernel because it wasn't auto picked as described already here)

![Image](https://github.com/user-attachments/assets/619fcb8c-da5d-4b0f-85b9-5e5b2ca3cf73)

Notice the different coloring of `cartopy` and `numpy` imports. 

Logs for this case 

<details>

```
2025-04-09 09:15:30.271 [info] (Client) Pylance async client (2025.4.1) started with python extension (2025.4.0)
2025-04-09 09:15:31.320 [info] [Info  - 09:15:31] (551) Server root directory: file:///Users/thd5tt/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist
2025-04-09 09:15:31.327 [info] [Info  - 09:15:31] (551) Pylance language server 2025.4.1 (pyright version 1.1.398, commit 4f24eccc) starting
2025-04-09 09:15:31.363 [info] [Info  - 09:15:31] (551) Starting service instance "<default>" for workspace ""
2025-04-09 09:15:31.622 [info] [Info  - 09:15:31] (551) Setting environmentName for service "<default>": "3.13.1 (global)"
2025-04-09 09:15:31.623 [info] [Info  - 09:15:31] (551) Setting pythonPath for service "<default>": "/Users/thd5tt/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist"
2025-04-09 09:15:31.623 [info] [Info  - 09:15:31] (551) No include entries specified; assuming /<default workspace root>
2025-04-09 09:15:31.623 [info] [Info  - 09:15:31] (551) Auto-excluding **/node_modules
2025-04-09 09:15:31.624 [info] [Info  - 09:15:31] (551) Auto-excluding **/__pycache__
2025-04-09 09:15:31.624 [info] [Info  - 09:15:31] (551) Auto-excluding **/.*
2025-04-09 09:15:31.706 [info] [Error - 09:15:31] (551) File or directory "/<default workspace root>" does not exist.
2025-04-09 09:15:31.707 [info] [Info  - 09:15:31] (551) No source files found.
2025-04-09 09:15:32.386 [info] [Info  - 09:15:32] (551) BG: Priority queue background worker(2) root directory: file:///Users/thd5tt/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist
2025-04-09 09:15:32.387 [info] [Info  - 09:15:32] (551) BG: Priority queue background worker(2) started
2025-04-09 09:15:36.554 [info] [Info  - 09:15:36] (551) Starting service instance "<default>" for workspace ""
2025-04-09 09:15:36.591 [info] [Info  - 09:15:36] (551) Setting environmentName for service "<default>": "3.13.1 (global)"
2025-04-09 09:15:36.591 [info] [Info  - 09:15:36] (551) Setting pythonPath for service "<default>": "/Users/thd5tt/miniconda3/envs/default/bin/python"
2025-04-09 09:15:36.591 [info] [Info  - 09:15:36] (551) No include entries specified; assuming /<default workspace root>
2025-04-09 09:15:36.591 [info] [Info  - 09:15:36] (551) Auto-excluding **/node_modules
2025-04-09 09:15:36.592 [info] [Info  - 09:15:36] (551) Auto-excluding **/__pycache__
2025-04-09 09:15:36.592 [info] [Info  - 09:15:36] (551) Auto-excluding **/.*
2025-04-09 09:15:36.675 [info] [Info  - 09:15:36] (551) Assuming Python version 3.11.11.final.0
2025-04-09 09:15:36.903 [info] [Error - 09:15:36] (551) File or directory "/<default workspace root>" does not exist.
2025-04-09 09:15:36.905 [info] [Info  - 09:15:36] (551) No source files found.
2025-04-09 09:15:37.462 [info] [Info  - 09:15:37] (551) BG: Priority queue background worker(4) root directory: file:///Users/thd5tt/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist
2025-04-09 09:15:37.464 [info] [Info  - 09:15:37] (551) BG: Priority queue background worker(4) started
```
<d/etails>

**Comment by rchiodo** [comment]
Yeah, I get the same problem. 

![Image](https://github.com/user-attachments/assets/a31144f9-c676-4ddf-b474-6ef7bde85e4d)

Normally I'd use 'Developer: Inspect Tokens and Scopes', but that doesn't seem to work in a notebook for some reason. 

I'll enter a bug on Pylance.

**Comment by DonJayamanne** [comment]
Given this issue has been around for a few months and no one else has reported this issue.
I'm closing this as not planned.
