### ISSUE TITLE
ipyml error with KeyError: 'buttons' in vscode integration only

### ISSUE THREAD

**Issue by T-Wainwright** [microsoft/vscode-jupyter#16829]
## Environment data

-   VS Code version: 1.102.1 
-   Jupyter Extension version (available under the Extensions sidebar): 2025.6.0
-   Python Extension version (available under the Extensions sidebar): 2025.10.1
-   OS (Windows | Mac | Linux distro) and version: Macos 15.5, vscode server on ubuntu 22.04 LTS
-   Python and/or Anaconda version: 3.12.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A Remote

## Expected behaviour

On jupyter lab:

<img width="847" height="840" alt="Image" src="https://github.com/user-attachments/assets/584e5923-32da-4643-97f4-209d957e86e4" />

## Actual behaviour

on vscode, creates the plot with the following error:

<img width="823" height="286" alt="Image" src="https://github.com/user-attachments/assets/0e79458b-caa1-41fa-835e-cebe0eb6f696" />

## Steps to reproduce:

1. mv/ delete .vscode-server directory
2. check `ps aux | grep jupyter` and kill any lingering `<pid>`
3. fully close down vscode
4. `killall -u <username>` on remote machine, forcing a disconnect
5. ssh connect to remote, create test directory, cd in
6. `python3 -m venv testEnv`
7. `source testEnv/bin/activate`
8. `pip install ipykernel matplotlib ipympl numpy`
9. Connect to ssh host on vscode
10. Open test directory in vscode
11. Create test.ipynb with above code, and save
12. Select kernel -> install recommended extensions [jupyter + python]
13. Reload window
14. Select kernel -> testEnv
15. Run all 

Running on a jupyter lab server works fine, implying its in the implemation of vscode somewhere.

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]
```
import matplotlib
matplotlib.use('module://ipympl.backend_nbagg')  # Set the backend programmatically

import matplotlib.pyplot as plt
import numpy as np

# Data
x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)

fig, ax = plt.subplots()

ax.plot(x, y, label='Sine Wave')

plt.show()
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Discussed with developers of matplotlib and ipympl here: https://github.com/matplotlib/matplotlib/pull/30337, believe issue is vscode side. ipympl was updated here to fix this: https://github.com/matplotlib/ipympl/blob/5e068ed222427919cc20c406e34d02ba9be55cc3/src/mpl_widget.ts#L760-L761, doesn't seem like the fix has carried accross

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, I've tried this out at my end with the latest versions and it works.

> updated here to fix this: https://github.com/matplotlib/ipympl/blob/5e068ed222427919cc20c406e34d02ba9be55cc3/src/mpl_widget.ts#L760-L761, doesn't seem like the fix has carried accross

Please note, the Jupyter extension in VS Code does not ship with any of this code.
The code for ipympl and other widgets are loaded either from the python environment or from the CDN.
Hence there's no way that fixes to such packages or the like don't make it into Jupyter extension.
Its most likely caused by some other issue (given that it works at my end & this hasn't been reported by anyone else)

Please could you enable logging as follows, I'd like to see the environment used.
Please do share all of the logs
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by T-Wainwright** [comment]
HI @DonJayamanne, apologies for the slow reply but still running into issues. Here's the trace for you to look at:

```
07:18:41.187 [debug] Handle Execution of Cells 0 for /n/projects/workarea/zcfd-testing/develop/zcfd-bbsp-daily_1408/bug.ipynb
07:18:41.189 [trace] Execute Notebook /n/projects/workarea/zcfd-testing/develop/zcfd-bbsp-daily_1408/bug.ipynb. Step 1
07:18:41.189 [trace] Connect to Kernel /n/projects/workarea/zcfd-testing/develop/zcfd-bbsp-daily_1408/bug.ipynb. Step 2
07:18:41.189 [trace] Connected to Kernel /n/projects/workarea/zcfd-testing/develop/zcfd-bbsp-daily_1408/bug.ipynb. Step 3
07:18:41.189 [trace] executeCell 0. Step 4
07:18:41.190 [trace] Cell Index:0 sent to kernel
07:18:41.217 [trace] Start cell 0 execution @ 1757402321217 (clear output)
07:18:41.217 [debug] Kernel acknowledged execution of cell 0 @ 1757402321217
07:18:41.691 [trace] Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
07:18:41.695 [trace] Widget Message: WidgetManager: Loading class MPLCanvasModel:jupyter-matplotlib:^0.11
07:18:41.702 [trace] Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
07:18:41.706 [trace] Widget Message: WidgetManager: Loading class ToolbarModel:jupyter-matplotlib:^0.11
07:18:41.724 [trace] Cell 0 completed in 0.507s (start: 1757402321217, end: 1757402321724)
07:18:41.724 [trace] Cell 0 executed successfully
07:18:41.770 [trace] Widget Message: Received display data message d68250dacdad49668c2a9fe8df27801e
07:18:41.787 [trace] Version of IPyWidgets 8 determined after 0.001s
07:18:41.812 [trace] Widget Message: Waiting for model to be available before rendering it d68250dacdad49668c2a9fe8df27801e
07:18:41.812 [trace] Widget Message: WidgetManager: Loading class MPLCanvasView:jupyter-matplotlib:^0.11
07:18:41.815 [trace] Widget Message: WidgetManager: Loading class ToolbarView:jupyter-matplotlib:^0.11
07:18:41.820 [trace] Widget Message: WidgetManager: Loading class LayoutView:@jupyter-widgets/base:2.0.0
07:18:58.064 [trace] Start cell 0 execution @ undefined
07:18:58.064 [trace] Cell 0 completed in 1757402321.724s (start: undefined, end: 1757402321724)
07:18:58.083 [trace] Start cell 0 execution @ undefined
07:18:58.083 [trace] Cell 0 completed in 1757402321.724s (start: undefined, end: 1757402321724)
07:18:58.103 [trace] Start cell 0 execution @ undefined
07:18:58.103 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.121 [trace] Start cell 0 execution @ undefined
07:18:58.122 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.141 [trace] Start cell 0 execution @ undefined
07:18:58.141 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.161 [trace] Start cell 0 execution @ undefined
07:18:58.162 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.182 [trace] Start cell 0 execution @ undefined
07:18:58.183 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.202 [trace] Start cell 0 execution @ undefined
07:18:58.203 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.223 [trace] Start cell 0 execution @ undefined
07:18:58.223 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.244 [trace] Start cell 0 execution @ undefined
07:18:58.244 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.660 [trace] Start cell 0 execution @ undefined
07:18:58.660 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.678 [trace] Start cell 0 execution @ undefined
07:18:58.678 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.695 [trace] Start cell 0 execution @ undefined
07:18:58.695 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.712 [trace] Start cell 0 execution @ undefined
07:18:58.712 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.758 [trace] Start cell 0 execution @ undefined
07:18:58.758 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:58.794 [trace] Start cell 0 execution @ undefined
07:18:58.794 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.445 [trace] Start cell 0 execution @ undefined
07:18:59.445 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.485 [trace] Start cell 0 execution @ undefined
07:18:59.485 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.520 [trace] Start cell 0 execution @ undefined
07:18:59.520 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.561 [trace] Start cell 0 execution @ undefined
07:18:59.561 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.642 [trace] Start cell 0 execution @ undefined
07:18:59.642 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.684 [trace] Start cell 0 execution @ undefined
07:18:59.684 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.726 [trace] Start cell 0 execution @ undefined
07:18:59.727 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.770 [trace] Start cell 0 execution @ undefined
07:18:59.770 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.811 [trace] Start cell 0 execution @ undefined
07:18:59.812 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.854 [trace] Start cell 0 execution @ undefined
07:18:59.854 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.892 [trace] Start cell 0 execution @ undefined
07:18:59.892 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.929 [trace] Start cell 0 execution @ undefined
07:18:59.929 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:18:59.965 [trace] Start cell 0 execution @ undefined
07:18:59.966 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:19:00.004 [trace] Start cell 0 execution @ undefined
07:19:00.004 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:19:00.041 [trace] Start cell 0 execution @ undefined
07:19:00.042 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
07:19:00.680 [trace] Start cell 0 execution @ undefined
07:19:00.681 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
```

There is clearly something wrong somewhere here as multiple users are still reporting an issue and bouncing between the ipympl developers and here to try to figure out what's going on. The biggest clue is that we're not seeing these issues on Jupyter web server: https://github.com/matplotlib/matplotlib/issues/29654

**Comment by DonJayamanne** [comment]
Please can you share the full log.
& can you share the versions of all the packages (pip list)

**Comment by DonJayamanne** [comment]
> https://github.com/matplotlib/ipympl/issues/575

Based on this its not just Jupyter extension, there seems to have been fixes upstream as well.
I'm not saying its not a problem in Jupyter extension, but from the issues it looks like there were fixes upsteam, meaning its possible there were some issues upstream and you haven't got those versions or its not yet fully resolved.

Either way, lets have a look at teh versions and logs.
When sharing the logs, please try to replicate the issue and please share the full logs.
I need the complete logs as it contains information about how the kernel was started, what env was used (version info, location, etc). Whether its python env or kernel spec, etc.
The user name should already be obfuscated (it will be in one place in the logs)
If removing anything from the logs, please keep track so you can share what was remoed.

**Comment by T-Wainwright** [comment]
pip freeze:

```((testEnv) ) tom.wainwright@fdsdev01:~/cases/ipympl_test$ pip freeze
anyio==4.9.0
argon2-cffi==25.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==3.0.0
async-lru==2.0.5
attrs==25.3.0
babel==2.17.0
beautifulsoup4==4.13.4
bleach==6.2.0
certifi==2025.7.14
cffi==1.17.1
charset-normalizer==3.4.2
comm==0.2.2
contourpy==1.3.2
cycler==0.12.1
debugpy==1.8.15
decorator==5.2.1
defusedxml==0.7.1
executing==2.2.0
fastjsonschema==2.21.1
fonttools==4.59.0
fqdn==1.5.1
h11==0.16.0
httpcore==1.0.9
httpx==0.28.1
idna==3.10
ipykernel==6.30.0
ipympl==0.9.7
ipython==9.4.0
ipython_pygments_lexers==1.1.1
ipywidgets==8.1.7
isoduration==20.11.0
jedi==0.19.2
Jinja2==3.1.6
json5==0.12.0
jsonpointer==3.0.0
jsonschema==4.25.0
jsonschema-specifications==2025.4.1
jupyter-events==0.12.0
jupyter-lsp==2.2.6
jupyter_client==8.6.3
jupyter_core==5.8.1
jupyter_server==2.16.0
jupyter_server_terminals==0.5.3
jupyterlab==4.4.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.15
kiwisolver==1.4.8
lark==1.2.2
MarkupSafe==3.0.2
matplotlib==3.10.3
matplotlib-inline==0.1.7
mistune==3.1.3
nbclient==0.10.2
nbconvert==7.16.6
nbformat==5.10.4
nest-asyncio==1.6.0
notebook_shim==0.2.4
numpy==2.3.1
overrides==7.7.0
packaging==25.0
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
pillow==11.3.0
platformdirs==4.3.8
prometheus_client==0.22.1
prompt_toolkit==3.0.51
psutil==7.0.0
ptyprocess==0.7.0
pure_eval==0.2.3
pycparser==2.22
Pygments==2.19.2
pyparsing==3.2.3
python-dateutil==2.9.0.post0
python-json-logger==3.3.0
PyYAML==6.0.2
pyzmq==27.0.0
referencing==0.36.2
requests==2.32.4
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rfc3987-syntax==1.1.0
rpds-py==0.26.0
Send2Trash==1.8.3
setuptools==80.9.0
six==1.17.0
sniffio==1.3.1
soupsieve==2.7
stack-data==0.6.3
terminado==0.18.1
tinycss2==1.4.0
tornado==6.5.1
traitlets==5.14.3
types-python-dateutil==2.9.0.20250708
typing_extensions==4.14.1
uri-template==1.3.0
urllib3==2.5.0
wcwidth==0.2.13
webcolors==24.11.1
webencodings==0.5.1
websocket-client==1.8.0
widgetsnbextension==4.0.14
```

Full log:

```
Visual Studio Code (1.104.0, ssh-remote, desktop)
Jupyter Extension Version: 2025.8.0.
Python Extension Version: 2025.14.0.
Python Environment Extension Version: 1.8.0.
Pylance Extension Version: 2025.8.1.
Platform: linux (x64).
Home = /n/fdshome/tom.wainwright
Temp Storage folder ~/.vscode-server/data/User/globalStorage/ms-toolsai.jupyter/version-2025.8.0
Workspace folder ~/cases/ipympl_test
08:56:02.074 [debug] getDataDirsImpl, Class name = zr (started execution), Arg 1: undefined, Arg 2: undefined
08:56:02.074 [debug] Start refreshing Kernel Picker (1758099362074)
08:56:02.923 [trace] Search for KernelSpecs in Interpreter ~/cases/ipympl_test/testEnv/bin/python
08:56:02.923 [trace] Search for KernelSpecs in Interpreter /bin/python3
08:56:02.923 [trace] Search for KernelSpecs in Interpreter /usr/bin/python3
08:56:02.923 [trace] Search for KernelSpecs in Interpreter ~/.local/bin/python3.12
08:56:02.925 [debug] Get Custom Env Variables, Class name = Qm, completed in 851ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
08:56:02.926 [debug] Jupyter Paths : 
08:56:02.927 [debug] getDataDirsImpl, Class name = zr, completed in 854ms, has a truthy return value, Arg 1: undefined, Arg 2: undefined, Return Value: <Uri:~/.local/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
08:56:02.927 [debug] Kernel Spec Root Paths, ~/.local/share/jupyter/kernels, /usr/local/share/jupyter/kernels, /usr/share/jupyter/kernels, /home/<username>/.local/share/jupyter/kernels
08:56:02.968 [trace] Python API env change detected, update => '~/cases/ipympl_test/testEnv/bin/python'
08:56:02.968 [trace] Search for KernelSpecs in Interpreter ~/cases/ipympl_test/testEnv/bin/python
08:56:02.970 [trace] No Kernels found in interpreter ~/cases/ipympl_test/testEnv/bin/python
08:56:02.971 [trace] Conda file is conda
08:56:02.974 [trace] Hiding default KernelSpec /python for interpreter ~/cases/ipympl_test/testEnv/bin/python (KernelSpec file ~/cases/ipympl_test/testEnv/share/jupyter/kernels/python3/kernel.json)
08:56:02.974 [debug] End refreshing Kernel Picker (1758099362074)
08:56:02.997 [debug] KernelProvider switched kernel to id = .jvsc74a57bd074ff5819b45e180a104a10d26d41b16bbc38dca7b94d31d20ac2f5ef4cbb7a15.~/cases/ipympl_test/testEnv/python.~/cases/ipympl_test/testEnv/python.-m#ipykernel_launcher
08:56:02.997 [debug] start the kernel, options.disableUI=true for ~/cases/ipympl_test/test.ipynb
08:56:03.036 [trace] Registering commtarget jupyter.widget
08:56:03.037 [debug] Controller selection change completed
08:56:06.600 [debug] Get Custom Env Variables, Class name = Qm, completed in 1ms, has a truthy return value, Arg 1: "~/cases/ipympl_test", Arg 2: "RunPythonCode"
08:56:06.602 [info] Starting Kernel (Python Path: ~/cases/ipympl_test/testEnv/bin/python, Venv, 3.12.11) for '~/cases/ipympl_test/test.ipynb' (disableUI=true)
08:56:06.603 [trace] Creating raw notebook for resource '~/cases/ipympl_test/test.ipynb'
08:56:11.067 [debug] Handle Execution of Cells 0 for ~/cases/ipympl_test/test.ipynb
08:56:11.080 [trace] Execute Notebook ~/cases/ipympl_test/test.ipynb. Step 1
08:56:11.080 [trace] Connect to Kernel ~/cases/ipympl_test/test.ipynb. Step 2
08:56:11.091 [debug] Get Custom Env Variables, Class name = Qm, completed in 0ms, has a truthy return value, Arg 1: "~/cases/ipympl_test/test.ipynb", Arg 2: "RunPythonCode"
08:56:12.472 [debug] Launching kernel .jvsc74a57bd074ff5819b45e180a104a10d26d41b16bbc38dca7b94d31d20ac2f5ef4cbb7a15.~/cases/ipympl_test/testEnv/python.~/cases/ipympl_test/testEnv/python.-m#ipykernel_launcher for ~/cases/ipympl_test/test.ipynb in ~/cases/ipympl_test with ports 9031, 9030, 9039, 9037, 9038
08:56:13.094 [debug] Got env vars from Python Ext in 2003ms for ~/cases/ipympl_test/testEnv/bin/python, with env var count 61.
08:56:13.094 [trace] Prepend PATH with python bin for ~/cases/ipympl_test/testEnv/bin/python
08:56:13.094 [debug] Getting activated env variables, Class name = Wd, completed in 2003ms, has a truthy return value, Arg 1: "~/cases/ipympl_test/test.ipynb", Arg 2: "~/cases/ipympl_test/testEnv/bin/python", Arg 3: undefined
08:56:13.105 [info] Process Execution: ~/cases/ipympl_test/testEnv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
08:56:13.115 [info] Process Execution: ~/cases/ipympl_test/testEnv/bin/python -m ipykernel_launcher --f=/run/user/2117774422/jupyter/runtime/kernel-v3b3aafefb579a3aca4509f058f720f35587582a7e.json
    > cwd: ~/cases/ipympl_test
08:56:13.115 [debug] Kernel process 2590314.
08:56:13.120 [debug] Got env vars from Python Ext in 6521ms for ~/cases/ipympl_test/testEnv/bin/python, with env var count 61.
08:56:13.120 [trace] Prepend PATH with python bin for ~/cases/ipympl_test/testEnv/bin/python
08:56:13.120 [debug] Getting activated env variables, Class name = Wd, completed in 6521ms, has a truthy return value, Arg 1: "~/cases/ipympl_test", Arg 2: "~/cases/ipympl_test/testEnv/bin/python", Arg 3: undefined
08:56:13.129 [info] Process Execution: ~/cases/ipympl_test/testEnv/bin/python -m pip list
08:56:16.127 [debug] Kernel output 2590314: To connect another client to this kernel, use:
--existing /run/user/2117774422/jupyter/runtime/kernel-v3b3aafefb579a3aca4509f058f720f35587582a7e.json
08:56:16.160 [debug] Waiting for Raw Session to be ready in postStartRawSession
08:56:16.160 [debug] Waiting for Raw session to be ready, status: connected
08:56:16.160 [trace] Raw session connected
08:56:16.161 [debug] Waited for Raw session to be ready & got status: connected
08:56:16.161 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
08:56:16.161 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
08:56:16.161 [debug] Sending request for kernelInfo
08:56:16.163 [trace] ipykernel version & path 6.30.0, ~/cases/ipympl_test/testEnv/lib/python3.12/site-packages/ipykernel/__init__.py for ~/cases/ipympl_test/testEnv/bin/python
08:56:16.238 [trace] Got response for requestKernelInfo
08:56:16.238 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 77ms
08:56:16.240 [trace] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
08:56:16.262 [trace] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
08:56:16.262 [trace] Started running kernel initialization for ~/cases/ipympl_test/test.ipynb
08:56:16.263 [trace] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
08:56:16.375 [trace] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 1 output(s)
08:56:16.375 [trace] Determined IPyWidgets Version as 8
08:56:16.375 [trace] Version of IPyWidgets 8 determined after 13.339s
08:56:16.375 [trace] Executing silently Code (idle) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None):
08:56:16.391 [trace] Executing silently Code (completed) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None): with 0 output(s)
08:56:16.391 [debug] Requesting Kernel info
08:56:16.391 [trace] Got Kernel info
08:56:16.392 [trace] End running kernel initialization, now waiting for idle
08:56:16.392 [trace] Waiting for idle on (kernel): 6b4bac34-6b7e-42ef-a648-72a31fa3a5d1 -> idle
08:56:16.392 [trace] Finished waiting for idle on (kernel): 6b4bac34-6b7e-42ef-a648-72a31fa3a5d1 -> idle
08:56:16.392 [trace] End running kernel initialization, session is idle
08:56:16.393 [trace] Registering Kernel Completion Provider from kernel testEnv (Python 3.12.11) for language python
08:56:16.394 [trace] IPyWidgetScriptSource.initialize
08:56:16.394 [info] Kernel successfully started
08:56:16.403 [debug] getDataDirsImpl, Class name = zr (started execution), Arg 1: "~/cases/ipympl_test/test.ipynb", Arg 2: "~/cases/ipympl_test/testEnv/bin/python"
08:56:16.417 [info] Process Execution: ~/cases/ipympl_test/testEnv/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2025.8.0-linux-x64/pythonFiles/printJupyterDataDir.py
08:56:16.932 [trace] Queue code ms-toolsai.datawrangler-1 from ms-toolsai.datawrangler after 0ms:
import builtins as __DW_BUILTINS_FOR_SCOPE__
__DW_SCOPE__ = __DW_BUILTINS_FOR_SCOPE__.globals().get("__DW_SCOPE__", {})
__DW_BUILTINS_FOR_SCOPE__.globals()["__DW_SCOPE__"] = __DW_SCOPE__
del __DW_BUILTINS_FOR_SCOPE__
def __DW_GET_SESSION_ID__():
    import uuid
    from builtins import str
    session_id = str(uuid.uuid4())
    return session_id

"""
Note: all executions are function-scoped as we do not assume the code below executes in an isolated kernel environment.
"""

def __DW_IO__(session_id, async_type=None):
    from builtins import dict, Exception, isinstance, object, str

    DW_OUTPUT_MIME_TYPE = "application/vnd.microsoft.datawrangler.output+json"

    def comm():
        from comm import create_comm
        comm = create_comm("datawrangler")
        return lambda msg: comm.send(msg, {"async": True})
    
    def display():
        from IPython.display import DisplayHandle
        handle = DisplayHandle()
        handle.display({ DW_OUTPUT_MIME_TYPE: {} }, raw=True)
        return lambda msg: handle.update({ DW_OUTPUT_MIME_TYPE: msg }, raw=True, metadata={"async": True})

    types = {
        "comm": comm,
        "display": display,
    }

    send_async_output = None
    if async_type in types:
        try:
            send_async_output = types[async_type]()
        except Exception:
            pass
    
    def output_mime(data):
        import sys
        class MimeBundle(object):
            def __init__(self, data):
                self.data = data
            def _repr_mimebundle_(self, **kwargs):
                return { "text/plain": "", **self.data }
            # 'text/plain' may be added to the bundle automatically. Make sure it does not take up space.
            def __str__(self):
                return ""
            def __repr__(self):
                return ""
        sys.displayhook(MimeBundle(data))
    
    def output(data):
        # vscode-jupyter has a problem handling non-object JSON at the top level. So make sure we never send it.
        if not isinstance(data, dict):
            raise Exception("Output data must be a dictionary")
        output_mime({ DW_OUTPUT_MIME_TYPE: data })

    def output_async(**data):
        msg = {"_session": session_id, **data}
        if send_async_output:
            send_async_output(msg)
        
    def log_exception(error_details=None, props={}, measures={}):
        if error_details is not None:
            errorName = error_details["name"]
            error = error_details["message"]
        else:
            import sys
            (errorName, error) = sys.exc_info()[:2]
        output_async(type="error", name=str(errorName), message=str(error), properties=props, measures=measures)
    
    def log_telemetry(name, props={}, measures={}):
        output_async(type="telemetry", event=name, properties=props, measurements=measures)

    return dict(
        output=output,
        output_async=output_async,
        log_exception=log_exception,
        log_telemetry=log_telemetry,
    )

def __DW_PANDAS_TRANSPORT__():
    from builtins import any, AttributeError, bool, dict, Exception, hasattr, ImportError, isinstance, len, list, map, min, object, range, str, tuple, type

    def get_df_shape(df):
        shape = {}
        shape["rows"], shape["columns"] = df.shape
        return shape

    def get_index_column_name(df):
        try:
            index_column_name = df.index.name if df.index.name else str(tuple(df.index.names)) if len(df.index.names) > 1 else "index"
        except AttributeError:
            index_column_name = "index"
        return index_column_name

    def get_inferred_dtype(column):
        import pandas as pd
        # In some older versions of Pandas, infer_dtype does not support sparse columns
        if hasattr(column, "sparse"):
            column = column.sparse.to_dense()
        inferred_dtype = pd.api.types.infer_dtype(column, skipna=True)
        return inferred_dtype

    def map_dtype_to_dw_type(dtype, inferred_dtype=None):
        """
        References to known types:
        - Pandas: https://stackoverflow.com/a/29246498
        - NumPy: https://numpy.org/doc/stable/reference/arrays.scalars.html

        Note: the types here do not necessarily include all NumPy types, but rather
        what type Pandas uses when the type is used as input. For example, NumPy
        supports several precision for datetimes, while Pandas internally only uses
        nanoseconds, see https://github.com/pandas-dev/pandas/issues/6741#issuecomment-39026803

        Note that the value mapped here is used for the following purposes:
        - To figure out what "picker" should be used for this type in the UI, e.g. when replacing
        - To figure out what operations should be associated with this type in the UI
        """
        import re

        # string types
        if dtype == "string" or (dtype == "object" and inferred_dtype == "string"):
            return "string"

        # category types
        # TODO@DW: enable this
        # if dtype == "category":
        #     return "category"

        # float types
        # TODO@DW: consider if we need to distinguish nullable types
        # or pass it along as metadata for certain operations
        if re.fullmatch(r"(?:float|Float)\d+", dtype):
            return "float"

        # int types
        # TODO@DW: consider if we need to distinguish nullable types
        # or pass it along as metadata for certain operations
        if re.fullmatch(r"(?:int|uint|Int|UInt)\d+", dtype):
            return "integer"

        # complex types
        # TODO@DW: enable this
        # if re.fullmatch("complex\d+", dtype):
        #     return "complex"

        # boolean types
        # TODO@DW: consider if we need to distinguish nullable types
        # or pass it along as metadata for certain operations
        if dtype in ["bool", "boolean"]:
            return "boolean"

        # datetime types
        # TODO@DW: handle timezone-specific datetimes
        if dtype == "datetime64[ns]":
            return "datetime"

        # timedelta types
        # TODO@DW: enable this
        # if dtype == "timedelta64[ns]":
        #     return "timedelta"

        # period types
        # TODO@DW: enable this
        # if re.fullmatch(r"period[.*]", dtype):
        #    return "period"

        # interval types
        # TODO@DW: we will need to pass the metadata of the interval type as well
        # interval_match = re.fullmatch(r"interval[(.*), .*]", dtype)
        # if interval_match:
        #    return map_dtype_to_dw_type(interval_match.group(1))

        # sparse types

        # TODO@DW: sparse types don't well for us because they don't support assignments,
        # e.g. https://github.com/pandas-dev/pandas/issues/21818 or describe calls.
        # For now we can just render them, but not support operations on them yet.

        # for sparse types, they're essentially just more compact versions of the
        # type that they wrap around, so we can just extract that part instead
        # sparse_match = re.fullmatch(r"(?:Sparse\[(.*), .*\]|Sparse\[(.*)\])", dtype)
        # if sparse_match:
        #     return map_dtype_to_dw_type(sparse_match.group(1))

        # default to unknown
        return "unknown"

    def is_missing(value):
        import pandas as pd

        return pd.api.types.is_scalar(value) and bool(pd.isna(value))

    def serialize(x):
        if is_missing(x):
            return None
        return str(x)

    def serialize_row(df, idx):
        key = df.index[idx]
        data = [serialize(key), *(serialize(df.iat[idx, col]) for col in range(len(df.columns)))]
        return data

    def pd_dumps(data):
        try:
            # This was renamed in Pandas 2.2.0. We need to try both.
            from pandas.io.json import ujson_dumps as pd_dumps
        except ImportError:
            from pandas.io.json import dumps as pd_dumps

        return pd_dumps(data, iso_dates=True, default_handler=str)
    
    def get_df_payload_v0(df, row_limit, **extra_props):
        import pandas as pd
        data = []
        for i in range(0, min(len(df), row_limit)):
            data.append(serialize_row(df, i))
        column_types = [df.index.dtype] + list(df.dtypes)
        column_names = [get_index_column_name(df)] + list(df)
        columns = [df.index] + [df.iloc[:, column_idx] for column_idx in range(len(list(df)))]
        column_info_list = []
        for column_idx in range(0, len(column_names)):
            column_info = {}

            # for each column, figure out the type and name
            raw_column_type = str(column_types[column_idx])
            column_name = column_names[column_idx]
            column = columns[column_idx]
            column_info["name"] = str(column_name)
            column_info["rawType"] = raw_column_type
            column_info["type"] = map_dtype_to_dw_type(raw_column_type, "string" if pd.api.types.is_string_dtype(column) else None)
            column_info_list.append(column_info)

        return pd_dumps({
            **extra_props,
            "shape": get_df_shape(df),
            "rows": data,
            "columns": column_info_list
        })

    def get_df_payload(df, row_limit, **extra_props):
        return get_df_payload_v0(df, row_limit, **extra_props)

    # namespace exports
    return dict(
        is_missing=is_missing,
        get_df_shape=get_df_shape,
        get_index_column_name=get_index_column_name,
        get_inferred_dtype=get_inferred_dtype,
        map_dtype_to_dw_type=map_dtype_to_dw_type,
        serialize=serialize,
        serialize_row=serialize_row,
        pd_dumps=pd_dumps,
        get_df_payload=get_df_payload
    )

def __DW_CONVERT_TO_PANDAS__(data_type, data):
    from builtins import Exception, type
    import sys
    df = None
    conversion_method = None
    try:
        if "xarray" in sys.modules:
            if data_type == "xarray.core.dataarray.DataArray":
                import pandas as pd
                data_numpy = data.to_numpy()
                df = pd.DataFrame(data_numpy.tolist() if len(data_numpy.shape) > 2 else data_numpy)
        if data_type == "builtins.dict":
            def convert_dict_to_pandas(data):
                from builtins import Exception, any, isinstance, len, list, map, print, tuple
                import numpy as np
                import pandas as pd
                nonlocal conversion_method
                conversion_method = "PandasFromDictOrientIndex"
                try:
                    if not any(map(lambda x: isinstance(x, (list, tuple, np.ndarray)), data.values())):
                        df = pd.DataFrame.from_dict(data, orient='index')
                        return df
                except Exception:
                    pass
                conversion_method = "PandasFromDictOrientColumns"
                try:
                    df = pd.DataFrame.from_dict(data)
                    return df
                except Exception:
                    pass
                conversion_method = "DictToDataFrameWide"
                def import_dict_value(v):
                    if not isinstance(v, (list, tuple, np.ndarray, pd.Series)):
                        return [v]
                    else:
                        v_numpy = np.empty(len(v), dtype=object)
                        v_numpy[:] = list(v)
                        return np.array(v_numpy, dtype=object)
                
                df = pd.DataFrame.from_dict({
                    k: import_dict_value(v) for k, v in data.items()
                }, orient="index").transpose().fillna(value=np.nan)
                return df
            
            df = convert_dict_to_pandas(data)
        if "tensorflow" in sys.modules:
            if data_type == "tensorflow.python.framework.ops.EagerTensor":
                import pandas as pd
                data_numpy = data.numpy()
                df = pd.DataFrame(data_numpy.tolist() if len(data_numpy.shape) > 2 else data_numpy)
        if data_type == "builtins.list":
            def convert_list_to_pandas(data):
                from builtins import Exception, hasattr, len, print
                import numpy as np
                import pandas as pd
                import sys
                nonlocal conversion_method
                conversion_method = "PandasDataFrameConstructor"
                try:
                    df = pd.DataFrame(data)
                    return df
                except Exception:
                    pass
                conversion_method = "NumpyArrayTorchNoGrad"
                try:
                    if 'torch' in sys.modules and hasattr(sys.modules['torch'], 'no_grad'):
                        import torch
                        with torch.no_grad():
                            df = pd.DataFrame(np.array(data))
                        return df
                except Exception:
                    pass
                conversion_method = "NumpyArrayWithObjectDtypeTorchNoGrad"
                try:
                    if 'torch' in sys.modules and hasattr(sys.modules['torch'], 'no_grad'):
                        import torch
                        with torch.no_grad():
                            data_numpy = np.empty(len(data), dtype=object)
                            data_numpy[:] = data
                            df = pd.DataFrame(np.array(data_numpy, dtype=object))
                        return df
                except Exception:
                    pass
                conversion_method = "NumpyArray"
                try:
                    df = pd.DataFrame(np.array(data))
                    return df
                except Exception:
                    pass
                conversion_method = "NumpyArrayWithObjectDtype"
                data_numpy = np.empty(len(data), dtype=object)
                data_numpy[:] = data
                df = pd.DataFrame(np.array(data_numpy, dtype=object))
                return df
            
            df = convert_list_to_pandas(data)
        if "numpy" in sys.modules:
            if data_type == "numpy.ndarray":
                def convert_ndarray_to_pandas(data):
                    from builtins import Exception, len, print
                    import pandas as pd
                    nonlocal conversion_method
                    conversion_method = "PandasDataFrameConstructor"
                    try:
                        df = pd.DataFrame(data)
                        return df
                    except Exception:
                        pass
                    conversion_method = "FlattenDimensions"
                    df = pd.DataFrame(data.tolist())
                    return df
                
                df = convert_ndarray_to_pandas(data)
        if "pandas" in sys.modules:
            if data_type == "pandas.core.frame.DataFrame":
                df = data
        if "pandas" in sys.modules:
            if data_type == "pandas.core.series.Series":
                df = data.to_frame()
        if "polars" in sys.modules:
            if data_type == "polars.dataframe.frame.DataFrame":
                df = data.to_pandas()
        if "polars" in sys.modules:
            if data_type == "polars.series.series.Series":
                df = data.to_pandas().to_frame()
        if "pyspark" in sys.modules:
            if data_type == "pyspark.sql.dataframe.DataFrame":
                df = data.toPandas()
        if "pyspark" in sys.modules:
            if data_type == "pyspark.sql.dataframe.DataFrame":
                df = data.toPandas()
        if "torch" in sys.modules:
            if data_type == "torch.Tensor":
                import pandas as pd
                data_tmp = data.detach().cpu()
                data_tmp = data_tmp.to_dense() if data_tmp.is_sparse else data_tmp
                data_numpy = data_tmp.numpy()
                df = pd.DataFrame(data_numpy.tolist() if len(data_numpy.shape) > 2 else data_numpy)
        return df, conversion_method
    except Exception:
        return None, conversion_method
def __DW_OUTPUT_FORMATTER__(api):
    import IPython
    import traitlets
    import traceback
    from builtins import classmethod, dict, Exception, ImportError, list, set, str, type

    DW_JSON_MIME_TYPE = 'application/vnd.microsoft.datawrangler.viewer.v0+json'
    max_num_rows_to_preload = 50
    tmp_vars = api["output_cache"]
    io = api["io"]
    supported_types = set()

    class DataWranglerFormatter(IPython.core.formatters.BaseFormatter):
        format_type = traitlets.Unicode(DW_JSON_MIME_TYPE)
        print_method = traitlets.ObjectName('_repr_dw_')

    class DataWrangler(IPython.display.DisplayObject):
        """
        Data Wrangler formatter.
        """

        is_supported = False

        def __init__(self, expr_val):
            import time
            start_time = time.time()
            props = {}

            try:
                nonlocal supported_types
                type_str = type_to_str(type(expr_val))

                pandas_supported = is_pandas_supported()
                if pandas_supported and type_str in supported_types:
                    pandas_df, conversion_method = api["pandas_converter"](type_str, expr_val)
                    self.is_supported = pandas_df is not None

                # Base telemetry props
                props = { "type": type_str, "conversionMethod": conversion_method, "supportedTypes": list(supported_types) }

                if self.is_supported:
                    import uuid
                    self.id = str(uuid.uuid4())

                    # create a shallow copy in case a displayed object is mutated in the same cell
                    if pandas_df is expr_val:
                        pandas_df = pandas_df.copy(deep=False)

                    tmp_vars[self.id] = {
                        "original": expr_val,
                        "converted": pandas_df,
                        "conversion_method": conversion_method,
                        "original_type": type_str,
                    }

                    io["log_telemetry"](name="OutputConverted", props=props, measures={"conversionTime": time.time() - start_time})
                elif type_str in supported_types:
                    props["isPandasSupported"] = pandas_supported
                    io["log_exception"](
                        error_details={
                            "name": "OutputConversionError",
                            "message": "Failed to convert"
                        },
                        props=props,
                        measures={"conversionTime": time.time() - start_time}
                    )
                else:
                    # This can be called for subclasses, so we don't actually want to log them to avoid PII.
                    # We just want to check here if we're failing because we don't have pandas or it's a subtype.
                    del props["type"]
                    props["isPandasSupported"] = pandas_supported
                    io["log_telemetry"](name="OutputConversionSkipped", props=props, measures={"conversionTime": time.time() - start_time})
            except Exception:
                # We shouldn't receive errors here, but if we do we can send telemetry for it.
                io["log_exception"](
                    props=props,
                    measures={"conversionTime": time.time() - start_time}
                )

        @classmethod
        def formatter(cls, var, **kwargs):
            s = cls(var, **kwargs)
            return s._repr_dw_()

        def _repr_mimebundle_(self):
            mime_bundle = {}
            try:
                if self.is_supported:
                    mime_bundle[DW_JSON_MIME_TYPE] = self._gen_json()
            except Exception:
                # need to catch and print exception since it is user visible
                traceback.print_exc()
            return mime_bundle

        def _repr_dw_(self):
            try:
                return self._gen_json()
            except Exception:
                # need to catch and print exception since it is user visible
                traceback.print_exc()

        def _gen_json(self):
            if self.is_supported:
                kwargs = {"ref": self.id}
                return api["pandas_transport"]["get_df_payload"](tmp_vars[self.id]["converted"], max_num_rows_to_preload, **kwargs)

    def register_dw_mimetype():
        """Register _repr_dw_ with the IPython display mechanism."""
        shell = IPython.get_ipython()
        if not shell:
            return
        display_formatter = shell.display_formatter
        display_formatter.formatters.setdefault(
            DW_JSON_MIME_TYPE,
            DataWranglerFormatter(parent=display_formatter),
        )

    def enable_formatter_for_types(*args):
        """
        Enables Data Wrangler as the default IPython formatter for the given type.
        """
        nonlocal supported_types
        supported_types = set()
        register_dw_mimetype()
        formatters = IPython.get_ipython().display_formatter.formatters
        for arg in args:
            supported_types.add(type_to_str(arg) if type(arg) == type else arg)
            if type(arg) == str:
                try:
                    path, base = arg.rsplit(".", 1)
                except Exception:
                    path = "builtins"
                    base = arg
                formatters[DW_JSON_MIME_TYPE].for_type_by_name(
                    path, base, DataWrangler.formatter
                )
            else:
                formatters[DW_JSON_MIME_TYPE].for_type(
                    arg, DataWrangler.formatter
                )

    def disable_formatter():
        """
        Disables the formatter.
        """
        nonlocal supported_types
        formatters = IPython.get_ipython().display_formatter.formatters
        supported_types = []
        for key in list(formatters.keys()):
            # Only explicitly disable the MIME type we are registered with.
            # This will allow us to run with several MIME type versions concurrently.
            if key == DW_JSON_MIME_TYPE:
                formatters.pop(key)

    def type_to_str(type):
        return f'{type.__module__}.{type.__qualname__}'

    def is_pandas_supported():
        try:
            import pandas as _
            return True
        except ImportError:
            return False

    # namespace exports
    return dict(
        enable_for_types=enable_formatter_for_types,
        disable=disable_formatter
    )
__DW_OUTPUT_FORMATTER_ID__ = "output-" + __DW_GET_SESSION_ID__()
__DW_OUTPUT_FORMATTER_CACHE__ = __DW_SCOPE__.get("output_cache", {})
__DW_SCOPE__["output_cache"] = __DW_OUTPUT_FORMATTER_CACHE__
__DW_OUTPUT_FORMATTER_API__ = {
    "output_cache": __DW_OUTPUT_FORMATTER_CACHE__,
    "io": __DW_IO__(__DW_OUTPUT_FORMATTER_ID__, async_type="display"),
    "pandas_transport": __DW_PANDAS_TRANSPORT__(),
    "pandas_converter": __DW_CONVERT_TO_PANDAS__,
}
__DW_OUTPUT_FORMATTER__ = __DW_OUTPUT_FORMATTER__(__DW_OUTPUT_FORMATTER_API__)
__DW_SCOPE__[__DW_OUTPUT_FORMATTER_ID__] = __DW_OUTPUT_FORMATTER__
__DW_OUTPUT_FORMATTER__["enable_for_types"]("pandas.core.frame.DataFrame", "pandas.core.series.Series")
import builtins as __DW_BUILTINS__
__DW_BUILTINS__.print(__DW_OUTPUT_FORMATTER_ID__)
del __DW_BUILTINS__
del __DW_OUTPUT_FORMATTER_ID__
del __DW_IO__
del __DW_GET_SESSION_ID__
del __DW_OUTPUT_FORMATTER_CACHE__
del __DW_PANDAS_TRANSPORT__
del __DW_CONVERT_TO_PANDAS__
del __DW_OUTPUT_FORMATTER__
del __DW_OUTPUT_FORMATTER_API__
08:56:16.933 [trace] Execution Id:ms-toolsai.datawrangler-1. Start Code execution.
08:56:16.933 [trace] Execution Id:ms-toolsai.datawrangler-1. Send code for execution.
08:56:16.933 [trace] Execution Id:ms-toolsai.datawrangler-1. Execution Request Sent to Kernel.
08:56:16.958 [debug] Got an empty Jupyter Data Dir from ~/cases/ipympl_test/testEnv/bin/python, stderr = undefined
08:56:16.958 [debug] getDataDirsImpl, Class name = zr, completed in 555ms, has a truthy return value, Arg 1: "~/cases/ipympl_test/test.ipynb", Arg 2: "~/cases/ipympl_test/testEnv/bin/python", Return Value: <Uri:~/.local/share/jupyter>, <Uri:~/cases/ipympl_test/testEnv/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
08:56:16.960 [trace] Web view is ready to receive widget messages
08:56:16.980 [trace] Execution Id:ms-toolsai.datawrangler-1. Executed successfully.
08:56:16.980 [debug] Execution of code ms-toolsai.datawrangler-1 completed in 48ms
08:56:16.982 [trace] ms-toolsai.datawrangler took 579ms during kernel startup
08:56:16.982 [trace] Connected to Kernel ~/cases/ipympl_test/test.ipynb. Step 3
08:56:16.983 [trace] executeCell 0. Step 4
08:56:16.984 [trace] Cell Index:0 sent to kernel
08:56:16.989 [trace] Start cell 0 execution @ 1758099376989 (clear output)
08:56:16.989 [debug] Kernel acknowledged execution of cell 0 @ 1758099376989
08:56:17.009 [error] Widget Error: Failed to access CDN https://unpkg.com/ after 0 attempt(s), TypeError: Failed to fetch
08:56:17.029 [trace] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
08:56:17.030 [trace] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
08:56:17.044 [trace] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
08:56:17.044 [trace] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
08:56:17.044 [trace] Widget Message: data-base-url set to https://vscode-remote%2Bssh-002dremote-002bfdsdev.vscode-resource.vscode-cdn.net~/.vscode-server/extensions/ms-toolsai.jupyter-2025.8.0-linux-x64/temp/scripts/83fe15f01fed0c7c3e0bb7f51af260c8449a7ff3d92276fba43e9c9efa2f9bda/jupyter
08:56:17.044 [trace] Widget Message: data-base-url set to https://vscode-remote%2Bssh-002dremote-002bfdsdev.vscode-resource.vscode-cdn.net~/.vscode-server/extensions/ms-toolsai.jupyter-2025.8.0-linux-x64/temp/scripts/83fe15f01fed0c7c3e0bb7f51af260c8449a7ff3d92276fba43e9c9efa2f9bda/jupyter
08:56:17.051 [trace] Widget Message: Received IPyWidget scripts [{"moduleName":"jupyter-matplotlib","scriptUri":"https://vscode-remote%2Bssh-002dremote-002bfdsdev.vscode-resource.vscode-cdn.net~/.vscode-server/extensions/ms-toolsai.jupyter-2025.8.0-linux-x64/temp/scripts/83fe15f01fed0c7c3e0bb7f51af260c8449a7ff3d92276fba43e9c9efa2f9bda/jupyter/nbextensions/jupyter-matplotlib/index","source":"local"}]
08:56:17.051 [trace] Widget Message: Source for IPyWidget jupyter-matplotlib found in local @ https://vscode-remote%2Bssh-002dremote-002bfdsdev.vscode-resource.vscode-cdn.net~/.vscode-server/extensions/ms-toolsai.jupyter-2025.8.0-linux-x64/temp/scripts/83fe15f01fed0c7c3e0bb7f51af260c8449a7ff3d92276fba43e9c9efa2f9bda/jupyter/nbextensions/jupyter-matplotlib/index.
08:56:17.052 [trace] Widget Message: Registering IPyWidget jupyter-matplotlib found in https://vscode-remote%2Bssh-002dremote-002bfdsdev.vscode-resource.vscode-cdn.net~/.vscode-server/extensions/ms-toolsai.jupyter-2025.8.0-linux-x64/temp/scripts/83fe15f01fed0c7c3e0bb7f51af260c8449a7ff3d92276fba43e9c9efa2f9bda/jupyter/nbextensions/jupyter-matplotlib/index.
08:56:17.563 [trace] Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
08:56:17.569 [trace] Widget Message: WidgetManager: Loading class MPLCanvasModel:jupyter-matplotlib:^0.11
08:56:17.609 [trace] Cell 0 completed in 0.62s (start: 1758099376989, end: 1758099377609)
08:56:17.610 [trace] Cell 0 executed successfully
08:56:17.666 [trace] Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
08:56:17.671 [trace] Widget Message: WidgetManager: Loading class ToolbarModel:jupyter-matplotlib:^0.11
08:56:17.683 [trace] Widget Message: Received display/update data message 3589fff102dd4b6f9ca708e559c80fee
08:56:17.693 [trace] Version of IPyWidgets 8 determined after 0.001s
08:56:17.720 [trace] Widget Message: Waiting for model to be available before rendering it 3589fff102dd4b6f9ca708e559c80fee
08:56:17.721 [trace] Widget Message: WidgetManager: Loading class MPLCanvasView:jupyter-matplotlib:^0.11
08:56:17.722 [trace] Widget Message: WidgetManager: Loading class ToolbarView:jupyter-matplotlib:^0.11
08:56:17.728 [trace] Widget Message: WidgetManager: Loading class LayoutView:@jupyter-widgets/base:2.0.0
08:56:18.366 [trace] Start cell 0 execution @ undefined
08:56:18.366 [trace] Cell 0 completed in 1758099377.609s (start: undefined, end: 1758099377609)
08:56:18.386 [trace] Start cell 0 execution @ undefined
08:56:18.386 [trace] Cell 0 completed in 1758099377.609s (start: undefined, end: 1758099377609)
08:56:18.406 [trace] Start cell 0 execution @ undefined
08:56:18.407 [trace] Cell 0 completed in 1758099377.609s (start: undefined, end: 1758099377609)
08:56:18.426 [trace] Start cell 0 execution @ undefined
08:56:18.427 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:18.481 [trace] Start cell 0 execution @ undefined
08:56:18.482 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:20.658 [trace] Start cell 0 execution @ undefined
08:56:20.659 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:20.703 [trace] Start cell 0 execution @ undefined
08:56:20.703 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:20.750 [trace] Start cell 0 execution @ undefined
08:56:20.750 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:20.793 [trace] Start cell 0 execution @ undefined
08:56:20.793 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:21.621 [trace] Start cell 0 execution @ undefined
08:56:21.621 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:21.708 [trace] Start cell 0 execution @ undefined
08:56:21.708 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:21.728 [trace] Start cell 0 execution @ undefined
08:56:21.728 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:21.749 [trace] Start cell 0 execution @ undefined
08:56:21.749 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:21.769 [trace] Start cell 0 execution @ undefined
08:56:21.770 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:31.126 [trace] Start cell 0 execution @ undefined
08:56:31.127 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:31.164 [trace] Start cell 0 execution @ undefined
08:56:31.165 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:31.203 [trace] Start cell 0 execution @ undefined
08:56:31.204 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:31.240 [trace] Start cell 0 execution @ undefined
08:56:31.240 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
08:56:31.278 [trace] Start cell 0 execution @ undefined
08:56:31.278 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
```

Another note on the behaviour, it appears the image renders correctly intiially, then a secondary process is kicking in causing the error?

**Comment by el-pato** [comment]
I was experiencing this exact issue. I can no longer reproduce after updating the the latest version of VSCode (1.104.2) - so probably it was fixed somewhere between 1.102.1 and 1.104.2?

**Comment by T-Wainwright** [comment]
You've gotten lucky then, still getting the exact same error here in 1.104.2, even after blowing everything away...

**Comment by DonJayamanne** [comment]
This is weird, I've tried this at my end, and it works.
Just doesn't make any sense.
Does it work when you try the following

```python
%matplotlib widget

import matplotlib
import matplotlib.pyplot as plt
import numpy as np

# Data
x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)

fig, ax = plt.subplots()

ax.plot(x, y, label='Sine Wave')

plt.show()
```
