### ISSUE TITLE
Unable to run notebook cells with spaces in path

### ISSUE THREAD

**Issue by dakenblack** [microsoft/vscode-jupyter#17042]
VSCode does not recognise ipykernel package within virtual environment. the issue is fixed by using an older version of the jupyter extension (2025.8.0).

## Environment data

-   Jupyter Extension version (available under the Extensions sidebar): 2025.9.0 (it works with 2025.8.0)
-   Python Extension version (available under the Extensions sidebar): 2025.16.0
-   Python and/or Anaconda version: 3.13
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A

System:
<img width="363" height="252" alt="Image" src="https://github.com/user-attachments/assets/6ae882f5-68ac-4356-b70e-d0df7c837fd0" />

ipykernel==6.30.1 is installed in local venv.

## Expected behaviour

Notebook executes

## Actual behaviour

I get an error message:

<img width="502" height="127" alt="Image" src="https://github.com/user-attachments/assets/67caf30e-f856-4360-a597-b49350082978" />

If I click "Install" I get this error message in the output section of the jupyter cell:
<img width="1719" height="121" alt="Image" src="https://github.com/user-attachments/assets/c1aa8feb-3872-46f9-9b57-c01bd638f733" />

## Steps to reproduce:

Try to execute on empty notebook.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
14:07:57.089 [info] Starting Kernel (Python Path: ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe, Venv, 3.13.5) for '~\Documents\Projects\003 Data Projects\jw-parsers\experiments\20251010 asx\00 explore.ipynb' (disableUI=false)
14:07:57.092 [info] Process Execution: ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
14:07:57.166 [info] Process Execution: ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe -m ipykernel_launcher --f=~\AppData\Roaming\jupyter\runtime\kernel-v3d077834aba04cafb6fa7aea82b801dfdb3413a94.json
    > cwd: ~\Documents\Projects\003 Data Projects\jw-parsers\experiments\20251010 asx
14:07:57.166 [error] Kernel died Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  path: '"c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  spawnargs: [
    '-m',
    'ipykernel_launcher',
    '--f=c:\\<username>s\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3d077834aba04cafb6fa7aea82b801dfdb3413a94.json'
  ]
} 
14:07:57.166 [error] Disposing kernel process due to an error Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  path: '"c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  spawnargs: [
    '-m',
    'ipykernel_launcher',
    '--f=c:\\<username>s\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3d077834aba04cafb6fa7aea82b801dfdb3413a94.json'
  ]
}
14:07:57.166 [error] 
14:07:57.167 [error] Failed to connect raw kernel session: Error: The kernel died. Error: ... View Jupyter [log](command:jupyter.viewOutput) for further details.
14:07:57.167 [error] Failed to connect raw kernel session: Error: The kernel died. Error: ... View Jupyter [log](command:jupyter.viewOutput) for further details.
14:07:57.167 [warn] Failed to shutdown kernel, .jvsc74a57bd0afc3510e580656b4ec2b0df362b50f8521590f26e05bf80bb6ecadd8772d063d.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.-m#ipykernel_launcher TypeError: Cannot read properties of undefined (reading 'dispose')
    at JT.shutdown (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:309:13632)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at qT.shutdown (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:309:22453)
14:07:57.168 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: The kernel died. Error: ... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0afc3510e580656b4ec2b0df362b50f8521590f26e05bf80bb6ecadd8772d063d.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe
    > at new n (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:62:51941)
    > originalException = Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    > stdErr = 
14:07:57.168 [warn] Kernel Error, context = start Error: The kernel died. Error: ... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0afc3510e580656b4ec2b0df362b50f8521590f26e05bf80bb6ecadd8772d063d.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe
    > at new n (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:62:51941)
    > originalException = Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    > stdErr = 
14:07:57.170 [info] Process Execution: ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
14:07:57.170 [warn] Module ipykernel not installed in environment ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  path: '"c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  spawnargs: [
    '-c',
    "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
  ]
}
14:07:57.171 [info] Check & install missing Kernel dependencies for ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe, ui.disabled=false for resource '~\Documents\Projects\003 Data Projects\jw-parsers\experiments\20251010 asx\00 explore.ipynb'
14:07:57.172 [info] Process Execution: ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
14:07:57.172 [warn] Module ipykernel not installed in environment ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  path: '"c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  spawnargs: [
    '-c',
    "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
  ]
}
14:07:57.173 [info] Process Execution: ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
14:07:57.173 [warn] Module pip not installed in environment ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  path: '"c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  spawnargs: [ '-c', "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')" ]
}
14:07:59.941 [info] Dispose Kernel '~\Documents\Projects\003 Data Projects\jw-parsers\experiments\20251010 asx\00 explore.ipynb' associated with '~\Documents\Projects\003 Data Projects\jw-parsers\experiments\20251010 asx\00 explore.ipynb'
14:07:59.942 [error] Error in notebook cell execution Error: The kernel died. Error: ... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0afc3510e580656b4ec2b0df362b50f8521590f26e05bf80bb6ecadd8772d063d.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe
    > at new n (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:62:51941)
    > originalException = Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    > stdErr = 
14:07:59.942 [error] Error in execution (get message for cell) Error: The kernel died. Error: ... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0afc3510e580656b4ec2b0df362b50f8521590f26e05bf80bb6ecadd8772d063d.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe
    > at new n (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:62:51941)
    > originalException = Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    > stdErr = 
14:07:59.944 [info] Process Execution: ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
14:07:59.944 [warn] Module ipykernel not installed in environment ~\Documents\Projects\003 Data Projects\jw-parsers\.venv\Scripts\python.exe Error: spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  path: '"c:/<username>s/<username>/Documents/Projects/003 Data Projects/jw-parsers/.venv/Scripts/python.exe"',
  spawnargs: [
    '-c',
    "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
  ]
}

```

</p>
</details>

**Comment by YeapJieShen** [comment]
Same issue encountered, despite having ipykernel and pip installed in my virtual environment.

Jupyter extension version: `2025.9.0`

OS Specifications:
```
Edition	Windows 11 Home Single Language
Version	24H2
Installed on	‎16/‎5/‎2025
OS build	26100.6584
Experience	Windows Feature Experience Pack 1000.26100.234.0
```

Python version: `3.12.9`

Libraries installed (Using venv):
```
Package                 Version
----------------------- -----------
asttokens               3.0.0
colorama                0.4.6
comm                    0.2.3
contourpy               1.3.3
cycler                  0.12.1
debugpy                 1.8.17
decorator               5.2.1
executing               2.2.1
fonttools               4.60.1
ipykernel               6.30.1
ipython                 9.6.0
ipython_pygments_lexers 1.1.1
jedi                    0.19.2
jupyter_client          8.6.3
jupyter_core            5.8.1
kiwisolver              1.4.9
matplotlib              3.10.7
matplotlib-inline       0.1.7
nest-asyncio            1.6.0
numpy                   2.2.6
opencv-python           4.12.0.88
packaging               25.0
parso                   0.8.5
pillow                  11.3.0
pip                     25.2
platformdirs            4.5.0
prompt_toolkit          3.0.52
psutil                  7.1.0
pure_eval               0.2.3
Pygments                2.19.2
pyparsing               3.2.5
python-dateutil         2.9.0.post0
pywin32                 311
pyzmq                   27.1.0
six                     1.17.0
stack-data              0.6.3
tornado                 6.5.2
traitlets               5.14.3
wcwidth                 0.2.14
```


<details>
  <summary>Execution logs as shown:</summary>
  
```
12:28:35.225 [debug] Handle Execution of Cells 0 for ~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb
12:28:35.227 [trace] Execute Notebook ~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb. Step 1
12:28:35.228 [trace] Connect to Kernel ~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb. Step 2
12:28:35.228 [debug] start the kernel, options.disableUI=false for ~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb
12:28:35.230 [info] Starting Kernel (Python Path: ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe, Venv, 3.12.9) for '~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb' (disableUI=false)
12:28:35.231 [trace] Creating raw notebook for resource '~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb'
12:28:35.242 [info] Process Execution: ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
12:28:35.750 [debug] Launching kernel .jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201.~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe.~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe.-m#ipykernel_launcher for ~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb in ~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks with ports 9009, 9008, 9012, 9010, 9011
12:28:35.760 [trace] Got a response of 1700 for INITIALIZE_INTERRUPT:2
12:28:35.763 [info] Process Execution: ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe -m ipykernel_launcher --f=~\AppData\Roaming\jupyter\runtime\kernel-v3b5761140344150f79c61ec9b97c60b8be6248a20.json
    > cwd: ~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks
12:28:35.763 [debug] Kernel process undefined.
12:28:35.766 [error] Kernel died Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  spawnargs: [
    '-m',
    'ipykernel_launcher',
    '--f=c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3b5761140344150f79c61ec9b97c60b8be6248a20.json'
  ]
} 
12:28:35.767 [error] Disposing kernel process due to an error Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  spawnargs: [
    '-m',
    'ipykernel_launcher',
    '--f=c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3b5761140344150f79c61ec9b97c60b8be6248a20.json'
  ]
}
12:28:35.768 [error] 
12:28:35.768 [debug] Dispose Kernel process undefined.
12:28:35.770 [error] Failed to connect raw kernel session: Error: The kernel died. Error: ... View Jupyter [log](command:jupyter.viewOutput) for further details.
12:28:35.771 [error] Failed to connect raw kernel session: Error: The kernel died. Error: ... View Jupyter [log](command:jupyter.viewOutput) for further details.
12:28:35.772 [warn] Failed to shutdown kernel, .jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201.~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe.~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe.-m#ipykernel_launcher TypeError: Cannot read properties of undefined (reading 'dispose')
    at JT.shutdown (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:309:13632)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at qT.shutdown (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:309:22453)
12:28:35.774 [warn] Error occurred while trying to start the kernel, options.disableUI=false pp [Error]: 
    at new n (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:62:51941)
    at new Ml (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:181:21022)
    at new pp (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:267:27167)
    at ub.launch (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:306:4)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)

Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  category: 'unknown',
  isJupyterError: true,
  originalException: Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
      at onErrorNT (node:internal/child_process:483:16)
      at processTicksAndRejections (node:internal/process/task_queues:90:21) {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
    path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
    spawnargs: [
      '-m',
      'ipykernel_launcher',
      '--f=c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3b5761140344150f79c61ec9b97c60b8be6248a20.json'
    ]
  },
  kernelConnectionMetadata: n {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: _d {
      specFile: 'c:\\Users\\<username>\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-toolsai.jupyter\\version-2025.9.0\\jupyter\\kernels\\python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201\\kernel.json',
      interpreterPath: 'c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: '.venv',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: 'C:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe',
      uri: [Pa]
    },
    id: '.jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher'
  },
  stdErr: '\n\n'
}
12:28:35.775 [warn] Kernel Error, context = start pp [Error]: 
    at new n (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:62:51941)
    at new Ml (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:181:21022)
    at new pp (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:267:27167)
    at ub.launch (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:306:4)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)

Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  category: 'unknown',
  isJupyterError: true,
  originalException: Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
      at onErrorNT (node:internal/child_process:483:16)
      at processTicksAndRejections (node:internal/process/task_queues:90:21) {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
    path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
    spawnargs: [
      '-m',
      'ipykernel_launcher',
      '--f=c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3b5761140344150f79c61ec9b97c60b8be6248a20.json'
    ]
  },
  kernelConnectionMetadata: n {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: _d {
      specFile: 'c:\\Users\\<username>\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-toolsai.jupyter\\version-2025.9.0\\jupyter\\kernels\\python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201\\kernel.json',
      interpreterPath: 'c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: '.venv',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: 'C:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe',
      uri: [Pa]
    },
    id: '.jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher'
  },
  stdErr: '\n\n'
}
12:28:35.792 [info] Process Execution: ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
12:28:35.793 [warn] Module ipykernel not installed in environment ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  spawnargs: [
    '-c',
    "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
  ]
}
12:28:35.793 [debug] Checking if product is installed, Class name = JD, completed in 5ms, has a falsy return value, Arg 1: 19, Arg 2: undefined, Return Value: false
12:28:35.794 [debug] Are Dependencies Installed, Class name = bp, completed in 7ms, has a falsy return value, Arg 1: "~\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher", Arg 2: undefined, Arg 3: true, Return Value: false
12:28:35.794 [info] Check & install missing Kernel dependencies for ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe, ui.disabled=false for resource '~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb'
12:28:35.799 [info] Process Execution: ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
12:28:35.800 [warn] Module ipykernel not installed in environment ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  spawnargs: [
    '-c',
    "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
  ]
}
12:28:35.801 [debug] Checking if product is installed, Class name = JD, completed in 7ms, has a falsy return value, Arg 1: 19, Arg 2: undefined, Return Value: false
12:28:35.802 [debug] Are Dependencies Installed, Class name = bp, completed in 8ms, has a falsy return value, Arg 1: "~\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher", Arg 2: {"a":false,"b":null}, Arg 3: true, Return Value: false
12:28:35.810 [info] Process Execution: ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
12:28:35.811 [warn] Module pip not installed in environment ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  spawnargs: [ '-c', "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')" ]
}
12:28:35.813 [debug] Checking if product is installed, Class name = JD, completed in 10ms, has a falsy return value, Arg 1: 27, Arg 2: undefined, Return Value: false
12:28:35.832 [debug] Disposed Kernel process undefined.
12:28:37.972 [debug] Install Missing Dependencies, Class name = bp, completed in 2178ms, has a truthy return value, Arg 1: {"resource":{"$mid":1,"fsPath":"c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\notebooks\\test.ipynb","_sep":1,"external":"file:///c%3A/Users/<username>/Downloads/Ctrl%20CV/2d-to-3d-reprojection/notebooks/test.ipynb","path":"/c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/notebooks/test.ipynb","scheme":"file"},"kernelConnection":{"id":".jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher","kernelSpec":{"specFile":"c:\\Users\\<username>\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-toolsai.jupyter\\version-2025.9.0\\jupyter\\kernels\\python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201\\kernel.json","interpreterPath":"c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":".venv","metadata":{"interpreter":{"path":"c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe"}},"env":{}},"interpreter":{"id":"C:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe","path":"c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe"},"kind":"startUsingPythonInterpreter"},"ui":{"_event":{"A":0},"_disableUI":false},"token":{"a":false,"b":{"A":0}},"ignoreCache":true,"cannotChangeKernels":false}, Return Value: 1
12:28:37.973 [info] Dispose Kernel '~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb' associated with '~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb'
12:28:37.973 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~\Downloads\Ctrl CV\2d-to-3d-reprojection\notebooks\test.ipynb
12:28:37.974 [error] Error in notebook cell execution pp [Error]: 
    at new n (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:62:51941)
    at new Ml (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:181:21022)
    at new pp (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:267:27167)
    at ub.launch (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:306:4)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)

Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  category: 'unknown',
  isJupyterError: true,
  originalException: Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
      at onErrorNT (node:internal/child_process:483:16)
      at processTicksAndRejections (node:internal/process/task_queues:90:21) {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
    path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
    spawnargs: [
      '-m',
      'ipykernel_launcher',
      '--f=c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3b5761140344150f79c61ec9b97c60b8be6248a20.json'
    ]
  },
  kernelConnectionMetadata: n {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: _d {
      specFile: 'c:\\Users\\<username>\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-toolsai.jupyter\\version-2025.9.0\\jupyter\\kernels\\python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201\\kernel.json',
      interpreterPath: 'c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: '.venv',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: 'C:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe',
      uri: [Pa]
    },
    id: '.jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher'
  },
  stdErr: '\n\n'
}
12:28:37.975 [trace] Start cell 0 execution @ undefined (clear output)
12:28:37.975 [error] Error in execution (get message for cell) pp [Error]: 
    at new n (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:62:51941)
    at new Ml (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:181:21022)
    at new pp (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:267:27167)
    at ub.launch (~\.vscode\extensions\ms-toolsai.jupyter-2025.9.0-win32-x64\dist\extension.node.js:306:4)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)

Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  category: 'unknown',
  isJupyterError: true,
  originalException: Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
      at onErrorNT (node:internal/child_process:483:16)
      at processTicksAndRejections (node:internal/process/task_queues:90:21) {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
    path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
    spawnargs: [
      '-m',
      'ipykernel_launcher',
      '--f=c:\\Users\\<username>\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3b5761140344150f79c61ec9b97c60b8be6248a20.json'
    ]
  },
  kernelConnectionMetadata: n {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: _d {
      specFile: 'c:\\Users\\<username>\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-toolsai.jupyter\\version-2025.9.0\\jupyter\\kernels\\python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201\\kernel.json',
      interpreterPath: 'c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3129jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: '.venv',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: 'C:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe',
      uri: [Pa]
    },
    id: '.jvsc74a57bd01f7d269287d2ed15961507065ee27560ab9735010d3cd5f18d32541f3e137201.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher'
  },
  stdErr: '\n\n'
}
12:28:37.985 [info] Process Execution: ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
12:28:37.985 [warn] Module ipykernel not installed in environment ~\Downloads\Ctrl CV\2d-to-3d-reprojection\.venv\Scripts\python.exe Error: spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe" ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  path: '"c:/Users/<username>/Downloads/Ctrl CV/2d-to-3d-reprojection/.venv/Scripts/python.exe"',
  spawnargs: [
    '-c',
    "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
  ]
}
12:28:37.986 [debug] Checking if product is installed, Class name = JD, completed in 8ms, has a falsy return value, Arg 1: 19, Arg 2: undefined, Return Value: false
12:28:37.987 [debug] Are Dependencies Installed, Class name = bp, completed in 10ms, has a falsy return value, Arg 1: "~\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.c:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher", Arg 2: undefined, Arg 3: true, Return Value: false
12:28:38.048 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)
``` 
</details>

**Comment by DonJayamanne** [comment]
**Steps to repro**
* Create a folder with a space e.g. `testing folder`
* Create a virtual env inside this folder & install ipykernel in that
* Open a notebook and select that and run a cell
* Fails to install ipykernel & fails to run a cell on windows

**Testing**
* Repro steps, and it should work

**Comment by rnckp** [comment]
I observe the same issue on MacOS. 

Switching the Jupyter extension to Pre-Release fixed the issue for me for now. (v 2025.9.2025092201 works)

**Comment by DonJayamanne** [comment]
We've identified the fix and will ship a fix soon.
I've already fixed this in main and a new pre-release version (for those using VS Code Insiders) will go out soon with the fixes.
Will organize a fix to go out for those using VS Code stable (1.105)

**Comment by DonJayamanne** [comment]
@rnckp Sorry you ran into this.
please can you confirm you had spaces in the path 
thanks

**Comment by YeapJieShen** [comment]
> [@rnckp](https://github.com/rnckp) Sorry you ran into this. please can you confirm you had spaces in the path thanks

Yes, I do have spaces around `CTRL CV`, as shown:

```
C:\\Users\\<username>\\Downloads\\Ctrl CV\\2d-to-3d-reprojection\\.venv\\Scripts\\python.exe
```

**Comment by rnckp** [comment]
> [@rnckp](https://github.com/rnckp) Sorry you ran into this. please can you confirm you had spaces in the path thanks

@DonJayamanne Thanks! And yes, I do have spaces in the path.

**Comment by DonJayamanne** [comment]
# Temporary solution
* Install VS Code insiders and latest pre-release
* Please install version 2025.8.0 (older version of extension), until we get a fix out soon for VS Code Stable

- Right click Jupyter extension and select "Install Specific Version"
- Select "2025.8.0"

<img width="390" height="337" alt="Image" src="https://github.com/user-attachments/assets/1d6b587e-a9a7-4c40-9f5b-ff08eb745ce9" />

<br />

<img width="174" height="74" alt="Image" src="https://github.com/user-attachments/assets/979c7f69-52df-42c9-9b92-7eced31692a8" />

**Comment by Carbaz** [comment]
Until a fix is released this is not `complete` and should not be `closed`.

Otherwise users running into the issue will not see this and will open new ones…
( Like the 14 you have already closed... 😉 )

**Comment by tomiyasu-ishikawa** [comment]
Thank you for the fix.
I’m experiencing the same issue in my environment.
Even when using a path without spaces (e.g., c:/user/pebble/Documents/test/), the error persists.
Also, following the suggested temporary solution and downgrading the Jupyter extension did not resolve the problem.

**Comment by DonJayamanne** [comment]
@tomiyasu-ishikawa you are running into a different issue, please can you file a separate issue so we can help you.

**Comment by DonJayamanne** [comment]
Fix had been shipped, please install the latest version 2025.9.1

**Comment by sushantnair** [comment]
Hello @DonJayamanne 

Unfortunately, I am still facing this issue. I have Windows 11 Home, VSCode 105 (the same version you get when you click install from the website) and Python 3.12. I am running the latest Jupyter extension version. The forever loading problem is still present "Connecting to kernel: venv ( Python 3.12.0); ..."
I even tried a complete uninstall, going all the way as to delete files in the AppData and the Registry. Then I did a fresh install of latest VSCode followed by installing the latest python and jupyter extensions.

Pleas help. Thanks.

**Comment by DonJayamanne** [comment]
Please can yoy create a separate issue and provide the details requested in issue template
