### ISSUE TITLE
Renderer extension not being installed -- causes some packages not to work, like plotly.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#3936]

**Comment by DonJayamanne** [comment]
Fixed by #3938

**Comment by DonJayamanne** [comment]
**Testing:**
* Install Jupyter
* Open a notebook
* Run a cell with plotly or vega or the like
* Ensure the renderer displays the output
	* Confirm the renderer is used (in the drop down against mim types you'll see the name of the renderer extension)

**Comment by hellmrf** [comment]
@DonJayamanne, I'm still having problems in the latest insider build.

![image](https://user-images.githubusercontent.com/25724069/99757515-4984c680-2ace-11eb-9fab-40cc37b8737b.png)

The LaTeX renderer seems to not be present, so I always need to select `text/plain` manually to see the ugly output.

**Comment by thakkarparth007** [comment]
I'm unable to view Plotly plots in the new notebooks. This screenshot shows the problem and the version being used:

![image](https://user-images.githubusercontent.com/747423/100549317-49d44d00-3298-11eb-832f-c4adc56eb0cd.png)

No new updates were available when I tried checking for updates.

**Comment by MichaelSteurer** [comment]
Same here. I run this as a quick workaround:
```python
import plotly.io as pio
pio.renderers.default = 'iframe_connected'
```

**Comment by rchiodo** [comment]
This doesn't seem to have been fixed. I sometimes get the renderer extension and sometimes don't. If I uninstall the jupyter extension, reinstall, and then run a notebook with plotly in it, the renderer extension is not downloaded.

**Comment by giammi56** [comment]
> Same here. I run this as a quick workaround:
> 
> ```python
> import plotly.io as pio
> pio.renderers.default = 'iframe_connected'
> ```

works good in Jupiter-notebook preview

**Comment by rchiodo** [comment]
https://github.com/microsoft/vscode-jupyter/issues/4149 is an item tracking the work to fix this.

**Comment by rchiodo** [comment]
Actually just removing #4149

**Comment by andreamoro** [comment]
> ```python
> renderers.default = 'iframe_connected'
> ```

Do you have any corresponding for plotly express. I can't see the corresponding entry point in the library.

**Comment by rchiodo** [comment]
Validated. Next release should have this fixed.
