### ISSUE TITLE
Endless product feedback request pop-ups!

### ISSUE THREAD

**Issue by r11-moto** [microsoft/vscode-jupyter#4002]
Issue Type: <b>Bug</b>

I keep getting asked to give feedback on jupyter notebooks! I've already given it. But every time I run a cell, I restart my environment, or randomly -- I get prompted to give my feedback.

Extension version: 2020.11.372831992
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|VirtualApple @ 2.50GHz processor (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id e987354c-7428-47d8-b68a-ac5a78bcde9c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joyceerhl** [comment]
Hey @r11-moto sorry about the trouble here. Would you mind providing the following details:
- Are you on the insider or stable build of VS Code?
- What does the text on the popup say? Is it the same popup each time?
- If you click 'no' on the popup, does it continue to appear?

**Comment by searri** [comment]
I am also having this issue!

- I am on the stable build
- The popup comes up **anytime** I interact with the notebook, as @r11-moto said. It always says "Can you please take 2 minutes to tell us how the Python Data Science features are working for you?"
- I click "No, thanks" every time and it still appears, regardless of VSCode or system restart

The first time it came up, I *did* fill out the survey, and I tried clicking "Yes, take survey now" (to see if that would suppress the prompt), but SurveyMonkey says I've already completed it. There appears to be no way to suppress this in the Extension Settings.

**Comment by DonJayamanne** [comment]
@r11-moto @searri 

Apologies for this issue, I think we have identified the cause of this issue.

**We create a new persistent object without passing the experiration value.**
```this.persistentState.createGlobalPersistentState<boolean>(DSSurveyStateKeys.ShowBanner, true).value &&```

Ideally we should just create the object once & re-use that insteaad of calling `createGlobalPersistentState` mutliple times. I.e. create it and store the value in a property.

**Comment by DonJayamanne** [comment]
Fixed

**Comment by escape0707** [comment]
Hi! Although this issue is technically fixed, I can only switch to non-stable channel to benefit from it. How can I know after which version of stable release should I switch back to stable channel?

**Comment by r11-moto** [comment]
> Hey @r11-moto sorry about the trouble here. Would you mind providing the following details:
> 
> * Are you on the insider or stable build of VS Code?
> * What does the text on the popup say? Is it the same popup each time?
> * If you click 'no' on the popup, does it continue to appear?

Sorry for the delayed reply - TL;DR as @escape0707 mentioned it is not fixed for the stable version

- **Are you on the insider or stable build of VS Code?** Stable
- **What does the text on the popup say? Is it the same popup each time?** It is the same pop-up each time - 
_"Can you please take 2 minutes to tell us how the Python Data Science features are working for you?'_
- **If you click 'no' on the popup, does it continue to appear**? Clicking any of the below options have no effect on permanently making the pop-up disappear:

1. 'No Thanks'
2. 'Yes Take Me To the Survey'
3. the X symbol
4. the gear symbol

**Comment by joyceerhl** [comment]
@escape0707 we are planning to release a fix in the stable channel early this coming week :)

**Comment by escape0707** [comment]
@joyceerhl Thank you for replying. Normally I'll just check the repo's release page and see if the commits in the merged PR which fix the issue is included in the stable tag or pre-release tag to decide when I should switch my update channel. But this repo didn't give those info in release page. That's why I was asking.

Anyway, thank you for your amazing work!
