### ISSUE TITLE
Persist Cell Language in Notebook Cell Metadata

### ISSUE THREAD

**Issue by ChrisCompton** [microsoft/vscode-jupyter#4757]
## Environment data

Version: 1.54.0-insider
Commit: 93f705ab40b37aade9d3b5165ed09114a8c87ac9
Date: 2021-02-11T05:43:26.672Z (8 hrs ago)
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

## Expected behaviour

In a notebook, when I select the language for a cell, it should retain that setting whenever the notebook is opened.  This should be maintained even if the kernel is changed because the language highlighting in the cell depends on this selection.

<img width="691" alt="Screen Shot 2021-02-10 at 1 39 28 PM" src="https://user-images.githubusercontent.com/2931691/107648465-fa1fe380-6c41-11eb-8f30-76691b770f8b.png">

The example shows expected behavior when python and ruby cells are included in a notebook.

## Actual behaviour

When I close the notebook file, and reopen it in the same session, the selections seem to be maintained; however, when I close the editor completely, reopen the folder, then open the file, the language selections are reset.

<img width="800" alt="Screen Shot 2021-02-10 at 1 49 33 PM" src="https://user-images.githubusercontent.com/2931691/107648949-8cc08280-6c42-11eb-9ed0-f1edda6700c3.png">

The example shows the ruby kernel selected, but all cells are marked as "Python."  Also, notice that the ruby cells are marked with syntax errors based on python.

## Steps to reproduce:

The example images show a very basic notebook format that will reproduce the problem.

1. Open a notebook with mixed cells.
2. Make sure that the language selections are accurate.
3. Close the notebook.
4. Close the editor.
5. Start the editor.
6. Open the notebook.
7. All cell language settings will be based on one language.

I'm not sure exactly what determines the language automatically chosen.  In the example above, the iruby kernel was selected at close, and was selected when I started the editor, yet all cells were marked as Python.
 
<img width="607" alt="Screen Shot 2021-02-11 at 8 31 41 AM" src="https://user-images.githubusercontent.com/2931691/107649953-97c7e280-6c43-11eb-8cf2-64776f804ad3.png">

Lastly, to repeat the behavior stated above, as long as I haven't closed the editor itself, I can open and close notebooks, and switch kernels without impacting the cell language selections.

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue, this is a known issue.
Currently we try to persis the language once you have executed a cell.
Please could you confirm this works as expected once you have executed a cell, saved the notebook & then reopened it.

**Comment by DonJayamanne** [comment]
**Related issues:**
* https://github.com/dotnet/interactive/issues/1038
* Using other kernels that support multiple languages (Jupyter SOS)
*

**Comment by ChrisCompton** [comment]
In the samples provided above, the cells had been saved after executing.  It did persist when closing the notebook and reopening -- provided you never close the editor.  Once you close VS Code, start it, and *then* open the notebook, the cells appeared as depicted in the second screenshot.

When the ruby kernel is selected, I can run both Ruby and Python in the same notebook as shown.  I will say that I can't pass output to the next cell if the languages are different, but other than that, I can run both languages in one notebook.

**Comment by greazer** [comment]
Check with John Lamb about state of polyglot notebook investigation.

**Comment by DonJayamanne** [comment]
Moving back to triage, as Johns spec doesn't address this, that's a whole different spec (related to execution, not persisting information in cells).

**Comment by Nordes** [comment]
I think this should be addressed. It's a pity that every time I re-open VsCode I lose all my previous settings for each cells. 

Only the markdown seems to be persisted. As the duplicated #4934 mentionned, cells always reset back to python while they were shell script, json, html, etc. This makes this extension non-usable if we are to share notebook between colleagues. Even for personal notes, IMO, to always put back the options is a non-go to use that extension.

**Comment by TeNNoX** [comment]
I also used to have this issue, but for me it is fixed.
Please check again.

**Comment by Qiuzhuang** [comment]
I use pyspark kernel and once notebook is saved and reopened,  all cells' language mode changed to 'plain text' and it causes the notebook not to execute cells normally and worse, notebook can't response any action. 

Version: 1.57.0-insider
Commit: 45aafeb326d0d3d56cbc9e2932f87e368dbf652d
Date: 2021-05-18T05:12:52.309Z (1 day ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.4.0

**Comment by Qiuzhuang** [comment]
After I enabling experiments flag, it works:)

"jupyter.experiments.enabled": true

**Comment by greazer** [comment]
The original bug still repro's in vscode insiders 1.61 and an associated jupyter extension.

**Comment by DonJayamanne** [comment]
Concerns:
* Opening & saving a notebook will now end up with a lot of changes
* Should this be done in vscode or jupyter extension
	* If we have a kernel such as Julia, whats the benefit of saving language, 0 benefit, as we only support julia languages in cells
		* Hence adding this metadata for notebooks with julia kernels is just going to add more noise
	* The opposite for .NET notebooks (they save the language info in the cells, or so i think)
	* However looking at the above screen sample, it seems we have python & ruby cells, looks like we're switching kernels.
	* Hence, i think we should store languages only when a Jupyter kernel is used (kernels/controllers contributed by the Jupyter extension) - upon running.
* If users have cell magics like %%shell, %%javascript, etc, then no point saving the language in the metadata, we can already get that info from the magics
	* Suggestion - store the language in metadata only when necessary
	* For these we can automatically detect the language from the magics (this can be done in vscode core extension)

**Comment by storrer** [comment]
I think that I am having this issue right now. I create a blank notebook with a powershell cell. I don't select a language kernel. I save the notebook, close it, and open it again. The language of the cell is changed to python. I can't get the language of a cell to save. in the notebook editor.

**Comment by amunger** [comment]
mostly fixed in vs code insiders, though a **blank** cell will still lose language selection when closing and re-opening the .ipynb file or selecting a different kernel. So more of an edge case now

**Comment by claudiaregio** [comment]
Hey @amunger, I am still seeing this in stable when working with .net interactive. If I open up a notebook (I've attached it) that has a C# cell and an F# cell, they both open up as C# despite the correct metadata being saved by our extension but I can't reopen https://github.com/microsoft/vscode/issues/140673 as it's limited to collaborators. 

[default.NETtest.zip](https://github.com/microsoft/vscode-jupyter/files/8972680/default.NETtest.zip)

**Comment by amunger** [comment]
The notebook you attached only has the language specified in the "dotnet_interactive" metadata, which vscode doesn't seem to use to set the cell language, but if I open that file with the latest .net interactive extension installed, it immediately adds the vscode metadata and seems to have the correct language set in the cell (without the .net extension, the cell language is C# for both).

```
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "dotnet_interactive": {
     "language": "fsharp"
    },
    "vscode": {
     "languageId": "dotnet-interactive.fsharp"
    }
   },
```

So I'm not sure how you are managing to save a notebook without that vscode metadata. Is the kernel getting selected correctly?

**Comment by jonsequitur** [comment]
Right. The issue is that on first open, the Jupyter extension rather than the .NET Interactive extension opens the notebook, and the cell languages are shown incorrectly. The metadata is set as expected but the wrong extension is opening the notebook.

**Comment by amunger** [comment]
ah, I got that to repro once out of around 10 tries. But how was this file created in the first place where it doesn't have vscode.languageId in the metadata?

**Comment by jonsequitur** [comment]
It could be an older file from before that metadata was implemented or it could be an .ipynb that was created or edited using an editor other than VS Code.

**Comment by DonJayamanne** [comment]
@jonsequitur is this still an issue in the latest version of VS Code?

**Comment by jonsequitur** [comment]
No, this is no longer an issue.

**Comment by DonJayamanne** [comment]
Thanks, closing this issue for now.

**Comment by johnmbarrett** [comment]
This issue appears to have regressed as of VS Code v1.74.2. The [attached notebook](https://github.com/microsoft/vscode-jupyter/files/10300164/test_matlab.ipynb.txt) has the language specified as Matlab everywhere possible, but when I open it in VS Code the language indicator in the bottom right briefly reads MATLAB before switching to Python (along with a tonne of red squiggles, because the code is very clearly Matlab and not Python).

Environment info:-

Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Relevant extentions and their versions:-

Jupyter v2022.11.1003412109
Matlab v2.3.1
Python v2022.20.1
