### ISSUE TITLE
[Inconsistent Behavior] Cannot click-to-source from Jupyter notebook

### ISSUE THREAD

**Issue by nfx** [microsoft/vscode-jupyter#4897]
Issue Type: <b>Bug</b>

When working with Python Notebooks from VSCode, i cannot click to source code (CTRL+click or CMD+click), defining a method/class/function, like I do for the rest of Python code in VSCode IDE. As a user of VSCode IDE, i expect integrated consistency of all features of Python language this extension aims to provide.

Extension version: 2021.2.582707922
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by DavidKutu** [comment]
Thanks for raising the issue @nfx. Our new Notebook Experience does support `ctrl + click` (and everything you expect from a normal file). You can try it out on VS Code insiders. https://code.visualstudio.com/insiders/

**Comment by nfx** [comment]
@DavidKutu that’s very interesting. Will try it out.

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed by VS Code's native notebook support. Please see https://github.com/microsoft/vscode/issues/91987.

**Comment by nfx** [comment]
@DavidKutu yes, isiders build looks cooler, but the issue still persists - i've created the new one #4972 and looking forward for that one to be addressed :) 

@greazer newer native notebook support is definitely a move in the right direction - kudos to the team.

btw, i'm a bit annoyed that i see `Python` in the bottom of every cell. if you want to get markdown switch, please make it less visible.
![image](https://user-images.githubusercontent.com/259697/109393644-4302b800-7923-11eb-9fab-bb0a828ce373.png)
