### ISSUE TITLE
spawn ENOTDIR when launching a Jupyter notebook

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5046]
@noce2 and @patientzero

I'm opening up this bug in the Jupyter repo based on your comments here:
https://github.com/microsoft/vscode/issues/118124#issuecomment-791464317

This may still be related to the VS Code issue, but it looks like a different symptom and it happens when the extension has already loaded and is trying to open a notebook. 

To help us investigate if you could do the following it would be very helpful.

1. Check in the output log for Developer: Toggle Developer Tools, this will give general VS Code debugging output
2. Set the setting Jupyter->Logging->Level to "debug" in VS Code settings. Then rerun the notebook launch and copy out everything in the VS Code Output window in the "Jupyter" section of the drop down. There may be a lot here, so you can paste that output into a file and then just drag that file onto a comment here to attach it.

Thanks much.

**Comment by DonJayamanne** [comment]
I think its related to https://github.com/microsoft/vscode-jupyter/issues/5049
If you look at the stack trace, it seems to be caused by the Python extension https://github.com/microsoft/vscode/issues/118124#issuecomment-791464317

**Comment by thesoundhead** [comment]
This is a real showstopper. Here's my log output – I hope this helps...

```
Error 2021-03-08 12:24:06: Install Missing Dependencies, Class name = g, completed in 14ms, has a falsy return value, Return Value: undefined [Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at spawn (child_process.js:557:9)
	at Object.execFile (child_process.js:241:17)
	at Object.t.<computed> [as execFile] (electron/js2c/asar_bundle.js:5:2208)
	at Object.exec (child_process.js:162:25)
	at Object.exec (electron/js2c/asar_bundle.js:5:12113)
	at /Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701932
	at new Promise (<anonymous>)
	at Object.t.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701902)
	at o.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:29:17474)
	at P.getActivatedEnvironmentVariablesImpl (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:59:589520)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  errno: 'ENOTDIR',
  code: 'ENOTDIR',
  syscall: 'spawn'
}
Error 2021-03-08 12:24:06: Find kernel spec, Class name = O, completed in 36ms, has a falsy return value, Arg 1: <Uri:/Users/USERNAME/mynotebook.ipynb>, Arg 2: {"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.0-final"},"orig_nbformat":2,"kernelspec":{"name":"python3","display_name":"Python 3.9.0 64-bit ('myvirtualenv')","metadata":{"interpreter":{"hash":"4a8f02c304692383966082d7fc10eb7840084d0d73b2565935126ca54dd3e86a"}}}}, Arg 3: undefined, Arg 4: undefined, Return Value: undefined [Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at spawn (child_process.js:557:9)
	at Object.execFile (child_process.js:241:17)
	at Object.t.<computed> [as execFile] (electron/js2c/asar_bundle.js:5:2208)
	at Object.exec (child_process.js:162:25)
	at Object.exec (electron/js2c/asar_bundle.js:5:12113)
	at /Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701932
	at new Promise (<anonymous>)
	at Object.t.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701902)
	at o.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:29:17474)
	at P.getActivatedEnvironmentVariablesImpl (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:59:589520)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  errno: 'ENOTDIR',
  code: 'ENOTDIR',
  syscall: 'spawn'
}
Error 2021-03-08 12:24:06: Get preferred local kernel connection, Class name = O, completed in 38ms, has a falsy return value [Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at spawn (child_process.js:557:9)
	at Object.execFile (child_process.js:241:17)
	at Object.t.<computed> [as execFile] (electron/js2c/asar_bundle.js:5:2208)
	at Object.exec (child_process.js:162:25)
	at Object.exec (electron/js2c/asar_bundle.js:5:12113)
	at /Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701932
	at new Promise (<anonymous>)
	at Object.t.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701902)
	at o.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:29:17474)
	at P.getActivatedEnvironmentVariablesImpl (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:59:589520)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  errno: 'ENOTDIR',
  code: 'ENOTDIR',
  syscall: 'spawn'
}
Error 2021-03-08 12:24:06: Exception attempting to start notebook:  [Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at spawn (child_process.js:557:9)
	at Object.execFile (child_process.js:241:17)
	at Object.t.<computed> [as execFile] (electron/js2c/asar_bundle.js:5:2208)
	at Object.exec (child_process.js:162:25)
	at Object.exec (electron/js2c/asar_bundle.js:5:12113)
	at /Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701932
	at new Promise (<anonymous>)
	at Object.t.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701902)
	at o.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:29:17474)
	at P.getActivatedEnvironmentVariablesImpl (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:59:589520)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  errno: 'ENOTDIR',
  code: 'ENOTDIR',
  syscall: 'spawn'
}
Info 2021-03-08 12:24:06: Exception executing cell NotebookImport#0:  [Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at spawn (child_process.js:557:9)
	at Object.execFile (child_process.js:241:17)
	at Object.t.<computed> [as execFile] (electron/js2c/asar_bundle.js:5:2208)
	at Object.exec (child_process.js:162:25)
	at Object.exec (electron/js2c/asar_bundle.js:5:12113)
	at /Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701932
	at new Promise (<anonymous>)
	at Object.t.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701902)
	at o.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:29:17474)
	at P.getActivatedEnvironmentVariablesImpl (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:59:589520)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  errno: 'ENOTDIR',
  code: 'ENOTDIR',
  syscall: 'spawn'
}
Info 2021-03-08 12:24:06: Finished executing cell NotebookImport#0
Error 2021-03-08 12:24:06: DataScience Error [Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at spawn (child_process.js:557:9)
	at Object.execFile (child_process.js:241:17)
	at Object.t.<computed> [as execFile] (electron/js2c/asar_bundle.js:5:2208)
	at Object.exec (child_process.js:162:25)
	at Object.exec (electron/js2c/asar_bundle.js:5:12113)
	at /Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701932
	at new Promise (<anonymous>)
	at Object.t.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:9:701902)
	at o.shellExec (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:29:17474)
	at P.getActivatedEnvironmentVariablesImpl (/Users/USERNAME/.vscode/extensions/ms-python.python-2021.2.625869727/out/client/extension.js:59:589520)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  errno: 'ENOTDIR',
  code: 'ENOTDIR',
  syscall: 'spawn'
}
Info 2021-03-08 12:24:07: Found matching interpreter based on interpreter or interpreterPath in metadata, for the kernel python3, Python 3, /Users/USERNAME/.pyenv/shims/python3
Info 2021-03-08 12:24:07: Find matching interpreter for a given kernel spec, Class name = P, completed in 1027ms, has a truthy return value, Arg 1: {"specFile":"/Users/USERNAME/Library/Jupyter/kernels/python3/kernel.json","interpreterPath":"/Users/USERNAME/.pyenv/shims/python3","name":"python3","argv":["/Users/USERNAME/.pyenv/shims/python3","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"/Users/USERNAME/.pyenv/shims/python3","display_name":"Python 3"}, Arg 2: undefined, Return Value: {"architecture":3,"path":"/Users/USERNAME/.pyenv/shims/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.7.0-final","major":3,"minor":7,"patch":0,"prerelease":["final"],"build":[],"version":"3.7.0-final"},"sysVersion":"3.7.0 (default, Apr 17 2020, 17:10:41) \n[Clang 10.0.0 (clang-1000.11.45.5)]","sysPrefix":"/Users/USERNAME/.pyenv/versions/3.7.0","fileHash":"a712ac92646570af9092b41e9946578ce6ef9a9a84e66ec3d45ee43b2ce460abe0dcf2c25a1d96189781cc9038b8eaad0a224ec6e02d1bb0d50030071b10de8e","envType":"Pyenv","envName":".pyenv","displayName":"Python 3.7.0 64-bit ('.pyenv': pyenv)"}
```

**Comment by DonJayamanne** [comment]
@thesoundhead Please could you install the insiders version of the Python extension, that should fix it
* Select the following command from the command palette
* `Python: Switch to Insiders Daily Channel`

**Comment by thesoundhead** [comment]
> @thesoundhead Please could you install the insiders version of the Python extension, that should fix it
> 
> * Select the following command from the command palette
> * `Python: Switch to Insiders Daily Channel`

Thank you! I will try that as soon as I get to it and report the outcome here.
Is there a way to stay on a reliably stable (release) version other than "the latest", which is explicitly said to be prone to be broken at times? If not: Why?

**Comment by kevin-bruton** [comment]
I have this same problem and I've tried switching to the insiders daily channel, as suggested, but I am still getting the "spawn ENOTDIR" when running a cell in a Jupyter notebook or when trying to open an interactive window.
Any help or suggestions greatly appreciated!

**Comment by kevin-bruton** [comment]
On further investigation, in my case at least, it appears that it has something to do with which interpreter path I choose. If i choose the one I have from pyenv, I can run notebooks and interactive windows correctly, however, other interpreters don't. The conda python interpreters that I have installed give the spawn error as well as when I select the venv of the project I'm working on at the the moment.

**Comment by thesoundhead** [comment]
@kevin-bruton Interesting!

A work-around that worked for me is to execute `jupyter notebook` in the terminal and use this server's URL in VSCode.

**Comment by DonJayamanne** [comment]
> Is there a way to stay on a reliably stable (release) version other than "the latest", which is explicitly said to be prone to be broken at times? If not: Why?

If you want the most stable version, then I'd use VS Code Stable.
However if you want to get unblocked, then I'd suggest trying insiders, & yes, it can break once inn a while (recently we've been breaking more often due to a lot of great but aggressive API changes by VS Code in the Notebook space).

**Comment by DonJayamanne** [comment]
Created an issue here where we'll look at getting a fix out into stable extension for this issue https://github.com/microsoft/vscode-jupyter/issues/5143

**Comment by IanMatthewHuff** [comment]
Don't really see a specific validation to check here. If there is one I can add it, but closing for now.
