### ISSUE TITLE
Interpreter picker seems to be displayed in Jupyter remote scenario

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6247]
It should not show up.

**Comment by IanMatthewHuff** [comment]
Still repros.

**Comment by DonJayamanne** [comment]
Could be the active interpreter that we're displaying.

**Comment by DonJayamanne** [comment]
Could be caused by interactive window , as it doesn't support remote yet.

**Comment by DonJayamanne** [comment]
Should be fixed

**Comment by IanMatthewHuff** [comment]
![image](https://user-images.githubusercontent.com/812783/135360583-7f5394eb-d3ca-4cb8-98c2-a107c45255a1.png)
This is still broken. I'm debugging now. Looks like there is a bigger issue here with extension activation.

**Comment by IanMatthewHuff** [comment]
This concerns me a bit. It looks like we are relying on onDidActivationPythonExtension, which from the code doesn't seem reliable. There are other places we are using this as well. I'm surprised that VS Code doesn't have a way to see when an extension is activated.

**Comment by IanMatthewHuff** [comment]
Dropping a quick note here, I see this as the probable issue here (per the comment):
https://github.com/microsoft/vscode-jupyter/blob/22f866c737e90eb6441685ec10d1afa951aad7c1/src/client/api/pythonApi.ts#L341
In the remote case we are not getting this event to hook up. Which I believe could cause issues with the other usages of this.

**Comment by DonJayamanne** [comment]
FYI - I added this to october as its not a ship blocker

**Comment by rchiodo** [comment]
I think this is working? Not sure what the problem is.

This shows in the kernel picker for interactive window (when using remote)

![image](https://user-images.githubusercontent.com/19672699/150879881-38de51fb-bfb1-4842-9821-67c5a9f5a0e5.png)

IW starts fine with remote.

**Comment by rchiodo** [comment]
@DonJayamanne do you remember what the problem was here?
