### ISSUE TITLE
HTML view not working with py3Dmol

### ISSUE THREAD

**Issue by Psirving** [microsoft/vscode-jupyter#6588]
Nobody has reported an issue with py3Dmol, but there was one about a performance issue with NGLview, which is a similar package for viewing molecular models. However, I think the backends of these two packages are different, and the issue I am having is different.

Py3Dmol is a python implementation of 3Dmol.js. The output displays in browser implementations of a Jupyter Notebook (using Chrome), and it was working around a month ago in VS Code, but now it creates an empty output cell of roughly the correct size.

## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999662501
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10.0.19043 build 19043
-   Python and/or Anaconda version: Anaconda 2020.11 Python 3.7.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda, but using 'base'
-   Jupyter server running: Local

## Expected behaviour

An interactive plot should display in the output cell.

## Actual behaviour

A blank output of roughly the correct size displays in the output cell.

## Steps to reproduce:

Run the following in a code cell:
```python
!pip install py3Dmol
import py3Dmol
p = py3Dmol.view(query='mmtf:1ycr')
p.setStyle({'cartoon': {'color':'spectrum'}})
p
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```

Info 2021-07-08 11:32:41: restartKernel - finishing cells that are outstanding
Info 2021-07-08 11:32:41: restartKernel - restarting kernel
Info 2021-07-08 11:32:41: Restarting ea8fa227-96a8-4cc1-9268-13ca982d86f4
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_onRestartKernel
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_kernelOptions
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: Got new session 00e5c2cb-0f18-41aa-90ac-9f64a3c749ca
Info 2021-07-08 11:32:41: Starting raw kernel Python 3.7.9 64-bit ('base': conda)
Info 2021-07-08 11:32:41: installMissingDependencies C:\Users\psirv\Anaconda3\python.exe
Info 2021-07-08 11:32:41: Started new restart session
Info 2021-07-08 11:32:41: shutdownSession ea8fa227-96a8-4cc1-9268-13ca982d86f4, .jvsc74a57bd06c33f2e669c4252adcb6b35df72ed100d5670b3dff543db2a50ccff0137b1beb.C:\Users\psirv\Anaconda3\python.exe.C:\Users\psirv\Anaconda3\python.exe - start
Info 2021-07-08 11:32:41: Session can be shutdown .jvsc74a57bd06c33f2e669c4252adcb6b35df72ed100d5670b3dff543db2a50ccff0137b1beb.C:\Users\psirv\Anaconda3\python.exe.C:\Users\psirv\Anaconda3\python.exe
Info 2021-07-08 11:32:41: Dispose Kernel process
Info 2021-07-08 11:32:41: kill daemon
Info 2021-07-08 11:32:41: restartKernel - initialSetup
Info 2021-07-08 11:32:41: Initial setup for untitled:Untitled-1.ipynb starting ...
Info 2021-07-08 11:32:41: UpdateWorkingDirectoryAndPath
Info 2021-07-08 11:32:41: Process Execution: > ~\Anaconda3\python.exe -c "import ipykernel"
> ~\Anaconda3\python.exe -c "import ipykernel"
Info 2021-07-08 11:32:41: KernelProcess output: Content-Length: 121
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"Execute rpc method kill_kernel in DS Daemon","pid":8940}}
Info 2021-07-08 11:32:41: Python Daemon (pid: 8940): Execute rpc method kill_kernel in DS Daemon
Info 2021-07-08 11:32:41: KernelProcess output: Content-Length: 153
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"Execute rpc method kill_kernel from C:\\Users\\psirv\\Anaconda3\\python.exe","pid":8940}}Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"Kill kernel in DS Kernel Launcher Daemon","pid":8940}}Content-Length: 129
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"Kill kernel in DS Kernel Launcher Daemon, pid 15236","pid":8940}}Content-Length: 38
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":2,"result":null}
Info 2021-07-08 11:32:41: Python Daemon (pid: 8940): Execute rpc method kill_kernel from C:\Users\psirv\Anaconda3\python.exe
Info 2021-07-08 11:32:41: Python Daemon (pid: 8940): Kill kernel in DS Kernel Launcher Daemon
Info 2021-07-08 11:32:41: Python Daemon (pid: 8940): Kill kernel in DS Kernel Launcher Daemon, pid 15236
Info 2021-07-08 11:32:41: Dispose Kernel process
Info 2021-07-08 11:32:41: shutdownSession ea8fa227-96a8-4cc1-9268-13ca982d86f4, .jvsc74a57bd06c33f2e669c4252adcb6b35df72ed100d5670b3dff543db2a50ccff0137b1beb.C:\Users\psirv\Anaconda3\python.exe.C:\Users\psirv\Anaconda3\python.exe - shutdown complete
Info 2021-07-08 11:32:41: Dispose Kernel process
Info 2021-07-08 11:32:41: KernelProcess Exit Exit - undefined 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_registerCommTarget
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_registerCommTarget
Info 2021-07-08 11:32:41: IPyWidgetMessageDispatcher.initialize
Info 2021-07-08 11:32:41: IPyWidgetMessageDispatcher.initialize
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: Kernel switching to busy
Info 2021-07-08 11:32:41: Notebook Session status untitled:Untitled-1.ipynb # Busy
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: Kernel switching to idle
Info 2021-07-08 11:32:41: Notebook Session status untitled:Untitled-1.ipynb # Idle
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: Kernel switching to busy
Info 2021-07-08 11:32:41: Notebook Session status untitled:Untitled-1.ipynb # Busy
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: Kernel switching to idle
Info 2021-07-08 11:32:41: Notebook Session status untitled:Untitled-1.ipynb # Idle
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: Initial setup complete for untitled:Untitled-1.ipynb
Info 2021-07-08 11:32:41: restartKernel - initialSetup completed
Info 2021-07-08 11:32:41: Time to restart kernel is 0.152s
Info 2021-07-08 11:32:41: Notebook Kernel restarted untitled:Untitled-1.ipynb
Info 2021-07-08 11:32:41: Cancel all executions as Kernel was restarted
Info 2021-07-08 11:32:41: Cancel pending cells
Info 2021-07-08 11:32:41: Registering commtarget jupyter.widget
Info 2021-07-08 11:32:41: UpdateWorkingDirectoryAndPath
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: changeDirectoryIfPossible
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: Kernel switching to busy
Info 2021-07-08 11:32:41: Notebook Session status untitled:Untitled-1.ipynb # Busy
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:41: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:41: Kernel switching to idle
Info 2021-07-08 11:32:41: Notebook Session status untitled:Untitled-1.ipynb # Idle
Info 2021-07-08 11:32:41: Waiting for idle on (kernel): 00e5c2cb-0f18-41aa-90ac-9f64a3c749ca -> idle
Info 2021-07-08 11:32:41: Finished waiting for idle on (kernel): 00e5c2cb-0f18-41aa-90ac-9f64a3c749ca -> idle
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:41: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:42: Install Missing Dependencies, Class name = w, completed in 942ms, has a falsy return value, Return Value: undefined
Info 2021-07-08 11:32:42: Kernel launching with ports 9010,9011,9012,9013,9014. Start port is 9000
Info 2021-07-08 11:32:42: Launching kernel daemon for Python 3.7.9 64-bit ('base': conda) # C:\Users\psirv\Anaconda3\python.exe
Info 2021-07-08 11:32:42: Fetching interpreter variables of Conda environment to be used as env vars of Kernel
Info 2021-07-08 11:32:42: Creating daemon process for C:\Users\psirv\Anaconda3\python.exe with env variables count 67
Info 2021-07-08 11:32:42: Process Execution: > ~\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\Anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2021-07-08 11:32:42: Got custom variables for Kernel owned by a conda interpreter
Info 2021-07-08 11:32:42: Python Daemon (pid: 17564): Execute rpc method exec_module in DS Daemon
Info 2021-07-08 11:32:42: Python Daemon (pid: 17564): Execute rpc method exec_module from C:\Users\psirv\Anaconda3\python.exe
Info 2021-07-08 11:32:42: Python Daemon (pid: 17564): Exec module in DS Kernel Launcher Daemon ipykernel_launcher with args ['--ip=127.0.0.1', '--stdin=9013', '--control=9011', '--hb=9010', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"7b65afe3-6949-453f-b9ca-6d4f1b0549d4"', '--shell=9012', '--transport="tcp"', '--iopub=9014', '--f=C:\\Users\\psirv\\AppData\\Local\\Temp\\tmp-40882I6r4f6j8YeC.json']
Info 2021-07-08 11:32:42: Python Daemon (pid: 17564): Exec in DS Kernel Launcher Daemon (observable) ipykernel_launcher with args ['--ip=127.0.0.1', '--stdin=9013', '--control=9011', '--hb=9010', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"7b65afe3-6949-453f-b9ca-6d4f1b0549d4"', '--shell=9012', '--transport="tcp"', '--iopub=9014', '--f=C:\\Users\\psirv\\AppData\\Local\\Temp\\tmp-40882I6r4f6j8YeC.json']
Info 2021-07-08 11:32:42: Python Daemon (pid: 17564): Exec in DS Kernel Launcher Daemon (observable) ['C:\\Users\\psirv\\Anaconda3\\python.exe', '-m', 'ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9013', '--control=9011', '--hb=9010', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"7b65afe3-6949-453f-b9ca-6d4f1b0549d4"', '--shell=9012', '--transport="tcp"', '--iopub=9014', '--f=C:\\Users\\psirv\\AppData\\Local\\Temp\\tmp-40882I6r4f6j8YeC.json']
Info 2021-07-08 11:32:42: Python Daemon (pid: 17564): Exec in DS Kernel Launcher Daemon (observable)
Info 2021-07-08 11:32:42: Python Daemon (pid: 17564): Kernel launched, with PID 9400
Warn 2021-07-08 11:32:42: Python Daemon (pid: 17564): Waiting for Kernel to die 9400
Info 2021-07-08 11:32:42: Launching kernel daemon, Class name = f, completed in 247ms, has a truthy return value, Arg 1: <Uri:Untitled-1.ipynb>, Arg 2: "c:\\Users\\psirv\\OneDrive - University of North Carolina at Chapel Hill\\GitHub\\JNBTools", Arg 3: {"specFile":"C:\\Users\\psirv\\Anaconda3\\share\\jupyter\\kernels\\python3\\kernel.json","interpreterPath":"C:\\Users\\psirv\\Anaconda3\\python.exe","name":"python379jvsc74a57bd06c33f2e669c4252adcb6b35df72ed100d5670b3dff543db2a50ccff0137b1beb","argv":["C:/Users/psirv/Anaconda3\\python.exe","-m","ipykernel_launcher","--ip=127.0.0.1","--stdin=9013","--control=9011","--hb=9010","--Session.signature_scheme=\"hmac-sha256\"","--Session.key=b\"7b65afe3-6949-453f-b9ca-6d4f1b0549d4\"","--shell=9012","--transport=\"tcp\"","--iopub=9014","--f=C:\\Users\\psirv\\AppData\\Local\\Temp\\tmp-40882I6r4f6j8YeC.json"],"language":"python","path":"C:/Users/psirv/Anaconda3\\python.exe","display_name":"Python 3.7.9 64-bit ('base': conda)"}, Arg 4: {"sysPrefix":"C:\\Users\\psirv\\Anaconda3","envType":"Conda","envName":"base","envPath":"C:\\Users\\psirv\\Anaconda3","path":"C:\\Users\\psirv\\Anaconda3\\python.exe","architecture":3,"sysVersion":"3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]","version":{"raw":"3.7.9","major":3,"minor":7,"patch":9,"build":[],"prerelease":["final","0"]},"companyDisplayName":"ContinuumAnalytics","displayName":"Python 3.7.9 64-bit ('base': conda)"}, Return Value: <Return value cannot be serialized for logging>
Info 2021-07-08 11:32:42: Launching kernel in kernelProcess.ts, Class name = b, completed in 248ms, has a truthy return value, Arg 1: "c:\\Users\\psirv\\OneDrive - University of North Carolina at Chapel Hill\\GitHub\\JNBTools", Return Value: {"proc":{"_events":{},"_eventsCount":2,"_closesNeeded":3,"_closesGot":0,"connected":false,"signalCode":null,"exitCode":null,"killed":false,"spawnfile":"C:\\Users\\psirv\\Anaconda3\\python.exe","_handle":{"pid":17564},"spawnargs":["C:\\Users\\psirv\\Anaconda3\\python.exe","-m","vscode_datascience_helpers.daemon","--daemon-module=vscode_datascience_helpers.kernel_launcher_daemon","-v"],"pid":17564,"stdin":{"connecting":false,"_hadError":false,"_parent":null,"_host":null,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null,"readable":false},"_events":{},"_eventsCount":3,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"errored":null,"closed":false,"closeEmitted":false},"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null},"stdout":{"connecting":false,"_hadError":false,"_parent":null,"_host":null,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":true,"ended":false,"endEmitted":false,"reading":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null},"_events":{"close":[null,null]},"_eventsCount":4,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"errored":null,"closed":false,"writable":false,"closeEmitted":false},"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null},"stderr":{"connecting":false,"_hadError":false,"_parent":null,"_host":null,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":true,"ended":false,"endEmitted":false,"reading":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null},"_events":{},"_eventsCount":3,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"errored":null,"closed":false,"writable":false,"closeEmitted":false},"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null},"stdio":[{"connecting":false,"_hadError":false,"_parent":null,"_host":null,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null,"readable":false},"_events":{},"_eventsCount":3,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":false,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"errored":null,"closed":false,"closeEmitted":false},"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null},{"connecting":false,"_hadError":false,"_parent":null,"_host":null,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":true,"ended":false,"endEmitted":false,"reading":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null},"_events":{"close":[null,null]},"_eventsCount":4,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"errored":null,"closed":false,"writable":false,"closeEmitted":false},"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null},{"connecting":false,"_hadError":false,"_parent":null,"_host":null,"_readableState":{"objectMode":false,"highWaterMark":16384,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":[],"flowing":true,"ended":false,"endEmitted":false,"reading":true,"sync":false,"needReadable":true,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"destroyed":false,"errored":null,"closed":false,"closeEmitted":false,"defaultEncoding":"utf8","awaitDrainWriters":null,"multiAwaitDrain":false,"readingMore":false,"decoder":null,"encoding":null},"_events":{},"_eventsCount":3,"_writableState":{"objectMode":false,"highWaterMark":16384,"finalCalled":false,"needDrain":false,"ending":false,"ended":false,"finished":false,"destroyed":false,"decodeStrings":false,"defaultEncoding":"utf8","length":0,"writing":false,"corked":0,"sync":true,"bufferProcessing":false,"writecb":null,"writelen":0,"afterWriteTickInfo":null,"buffered":[],"bufferedIndex":0,"allBuffers":true,"allNoop":true,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":false,"autoDestroy":false,"errored":null,"closed":false,"writable":false,"closeEmitted":false},"allowHalfOpen":false,"_sockname":null,"_pendingData":null,"_pendingEncoding":"","server":null,"_server":null}]},"out":{"_isScalar":false,"observers":[],"closed":false,"isStopped":false,"hasError":false,"thrownError":null}}
Info 2021-07-08 11:32:42: Execute Cells request 2 0, 1
Info 2021-07-08 11:32:42: Execute Cell 0 untitled:Untitled-1.ipynb
Info 2021-07-08 11:32:42: Cell Index:0, state:1, exec: 1. User queued cell for execution
Info 2021-07-08 11:32:42: Execute Cell 1 untitled:Untitled-1.ipynb
Info 2021-07-08 11:32:42: Cell Index:1, state:undefined, exec: undefined. User queued cell for execution
Info 2021-07-08 11:32:42: Cell Index:0, state:1, exec: 1. Ready to execute
Info 2021-07-08 11:32:42: Cell Index:1, state:undefined, exec: undefined. Ready to execute
Info 2021-07-08 11:32:42: Cell Index:0, state:1, exec: 1. Before Execute individual cell
Info 2021-07-08 11:32:42: Cell Index:0, state:1, exec: 1. Start execution
Info 2021-07-08 11:32:42: Cell Index:0, state:3, exec: undefined. Send code for execution
Info 2021-07-08 11:32:42: Cell Index:0, state:3, exec: undefined. Wait for jupyter execution
Info 2021-07-08 11:32:42: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-07-08 11:32:42: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:42: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:42: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:42: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:42: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:42: Cell Index:0, state:3, exec: undefined. Kernel switching to busy
Info 2021-07-08 11:32:42: Notebook Session status untitled:Untitled-1.ipynb # Busy
Info 2021-07-08 11:32:42: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:42: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:42: Cell Index:0, state:3, exec: 1. Update output
Info 2021-07-08 11:32:42: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:42: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:42: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:42: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:42: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-08 11:32:42: [32mPosting message to Notebook UI 
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-08 11:32:42: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-08 11:32:42: Cell Index:0, state:3, exec: 1. Update output
Info 2021-07-08 11:32:43: Cell Index:0, state:3, exec: 1. Kernel switching to idle
Info 2021-07-08 11:32:43: Notebook Session status untitled:Untitled-1.ipynb # Idle
Info 2021-07-08 11:32:43: Cell Index:0, state:3, exec: 1. Jupyter execution completed
Info 2021-07-08 11:32:43: Cell Index:0, state:3, exec: 1. Completed successfully
Info 2021-07-08 11:32:43: Cell Index:0, state:3, exec: 1. Completed successfully & resolving
Info 2021-07-08 11:32:43: Cell Index:0, state:3, exec: 1. After Execute individual cell 3
Info 2021-07-08 11:32:43: Cell Index:1, state:2, exec: undefined. Before Execute individual cell
Info 2021-07-08 11:32:43: Cell Index:1, state:2, exec: undefined. Start execution
Info 2021-07-08 11:32:43: Cell Index:0, state:3, exec: 1. Executed successfully in executeCell
Info 2021-07-08 11:32:43: Cell Index:0, state:3, exec: 1. Execution disposed
Info 2021-07-08 11:32:43: Cell Index:1, state:3, exec: undefined. Send code for execution
Info 2021-07-08 11:32:43: Cell Index:1, state:3, exec: undefined. Empty cell execution
Info 2021-07-08 11:32:43: Cell Index:1, state:3, exec: undefined. Completed successfully
Info 2021-07-08 11:32:43: Cell Index:1, state:3, exec: undefined. Completed successfully & resolving
Info 2021-07-08 11:32:43: Cell Index:1, state:3, exec: undefined. After Execute individual cell 2
Info 2021-07-08 11:32:43: Cell Index:1, state:3, exec: undefined. Execution disposed
Info 2021-07-08 11:32:43: KernelProcess output: Content-Length: 335
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"write to stderr: C:\\Users\\psirv\\Anaconda3\\lib\\site-packages\\traitlets\\traitlets.py:2199: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '\"hmac-sha256\"' \u2013 or use CUnicode.\r\n","pid":17564}}Content-Length: 312
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"output","params":{"source":"stderr","out":"C:\\Users\\psirv\\Anaconda3\\lib\\site-packages\\traitlets\\traitlets.py:2199: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '\"hmac-sha256\"' \u2013 or use CUnicode.\r\n"}}
Info 2021-07-08 11:32:43: Python Daemon (pid: 17564): write to stderr: C:\Users\psirv\Anaconda3\lib\site-packages\traitlets\traitlets.py:2199: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode.

Info 2021-07-08 11:32:43: KernelProcess output: Content-Length: 116
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"write to stderr:   FutureWarning)\r\n","pid":17564}}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"output","params":{"source":"stderr","out":"  FutureWarning)\r\n"}}Content-Length: 361
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"write to stderr: C:\\Users\\psirv\\Anaconda3\\lib\\site-packages\\traitlets\\traitlets.py:2154: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '7b65afe3-6949-453f-b9ca-6d4f1b0549d4' instead of 'b\"7b65afe3-6949-453f-b9ca-6d4f1b0549d4\"'.\r\n","pid":17564}}Content-Length: 338
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"output","params":{"source":"stderr","out":"C:\\Users\\psirv\\Anaconda3\\lib\\site-packages\\traitlets\\traitlets.py:2154: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '7b65afe3-6949-453f-b9ca-6d4f1b0549d4' instead of 'b\"7b65afe3-6949-453f-b9ca-6d4f1b0549d4\"'.\r\n"}}Content-Length: 116
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"write to stderr:   FutureWarning)\r\n","pid":17564}}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"output","params":{"source":"stderr","out":"  FutureWarning)\r\n"}}
Warn 2021-07-08 11:32:43: Kernel 17564 as possibly died, StdErr from Kernel Process C:\Users\psirv\Anaconda3\lib\site-packages\traitlets\traitlets.py:2199: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode.

Warn 2021-07-08 11:32:43: StdErr from Kernel Process C:\Users\psirv\Anaconda3\lib\site-packages\traitlets\traitlets.py:2199: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode.

Info 2021-07-08 11:32:43: Python Daemon (pid: 17564): write to stderr:   FutureWarning)

Warn 2021-07-08 11:32:43: Kernel 17564 as possibly died, StdErr from Kernel Process   FutureWarning)

Warn 2021-07-08 11:32:43: StdErr from Kernel Process   FutureWarning)

Info 2021-07-08 11:32:43: Python Daemon (pid: 17564): write to stderr: C:\Users\psirv\Anaconda3\lib\site-packages\traitlets\traitlets.py:2154: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '7b65afe3-6949-453f-b9ca-6d4f1b0549d4' instead of 'b"7b65afe3-6949-453f-b9ca-6d4f1b0549d4"'.

Warn 2021-07-08 11:32:43: Kernel 17564 as possibly died, StdErr from Kernel Process C:\Users\psirv\Anaconda3\lib\site-packages\traitlets\traitlets.py:2154: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '7b65afe3-6949-453f-b9ca-6d4f1b0549d4' instead of 'b"7b65afe3-6949-453f-b9ca-6d4f1b0549d4"'.

Warn 2021-07-08 11:32:43: StdErr from Kernel Process C:\Users\psirv\Anaconda3\lib\site-packages\traitlets\traitlets.py:2154: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '7b65afe3-6949-453f-b9ca-6d4f1b0549d4' instead of 'b"7b65afe3-6949-453f-b9ca-6d4f1b0549d4"'.

Info 2021-07-08 11:32:43: Python Daemon (pid: 17564): write to stderr:   FutureWarning)

Warn 2021-07-08 11:32:43: Kernel 17564 as possibly died, StdErr from Kernel Process   FutureWarning)

Warn 2021-07-08 11:32:43: StdErr from Kernel Process   FutureWarning)
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Should be fixed in our new release, will be releasing shortly.

**Comment by greazer** [comment]
@Psirving, please reopen if this has not been fixed in the next release (happening very very soon)

**Comment by Psirving** [comment]
I just updated to v2021.8.1013163132. I'm still getting the same result.

**Comment by Psirving** [comment]
I don't think I have permission to reopen an issue which you closed.

**Comment by DonJayamanne** [comment]
@Psirving works for me, see here
Please could you provide logs:
* Jupyter output panel
* Toggle Developer tools & go into `console` window
<img width="712" alt="Screen Shot 2021-07-09 at 10 53 26" src="https://user-images.githubusercontent.com/1948812/125118027-f5057a00-e0a3-11eb-9ce8-910728c14eaa.png">

**Comment by Psirving** [comment]
My mistake, kind of.

It is working in newly created notebooks only. If I run this cell in an existing notebook, or if I make a copy of a notebook, and run that, It doesn't display. If I copy all of the contents of a notebook to a newly created notebook. It works perfectly. The logs, to me look basically the same. 


## Logs

<details>

<summary>Log 1, a new notebook, this displays correctly.</summary>

<p>

```
Info 2021-07-09 14:30:43: Execute Cells request 1 0
Info 2021-07-09 14:30:43: Execute Cell 0 untitled:Untitled-1.ipynb?jupyter-notebook
Info 2021-07-09 14:30:43: Cell Index:0, state:1, exec: 1. User queued cell for execution
Info 2021-07-09 14:30:43: Cell Index:0, state:1, exec: 1. Ready to execute
Info 2021-07-09 14:30:43: Cell Index:0, state:1, exec: 1. Before Execute individual cell
Info 2021-07-09 14:30:43: Cell Index:0, state:1, exec: 1. Start execution
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: undefined. Send code for execution
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: undefined. Wait for jupyter execution
Info 2021-07-09 14:30:43: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-07-09 14:30:43: [32mPosting message to Notebook UI 
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:30:43: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:30:43: [32mPosting message to Notebook UI 
Info 2021-07-09 14:30:43: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:30:43: [32mPosting message to Notebook UI 
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: undefined. Kernel switching to busy
Info 2021-07-09 14:30:43: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-07-09 14:30:43: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:30:43: [32mPosting message to Notebook UI 
Info 2021-07-09 14:30:43: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:30:43: [32mPosting message to Notebook UI 
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: undefined. Update output
Info 2021-07-09 14:30:43: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:30:43: [32mPosting message to Notebook UI 
Info 2021-07-09 14:30:43: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:30:43: [32mPosting message to Notebook UI 
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:30:43: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: 3. Update output
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: 3. Kernel switching to idle
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: 3. Jupyter execution completed
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: 3. Completed successfully
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: 3. Completed successfully & resolving
Info 2021-07-09 14:30:43: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: 3. After Execute individual cell 3
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: 3. Executed successfully in executeCell
Info 2021-07-09 14:30:43: Cell Index:0, state:3, exec: 3. Execution disposed
```

</p>
</details>

<details>

<summary>Log 2, an existing notebook, this does not display anything.</summary>

<p>

```
Info 2021-07-09 14:31:38: Execute Cells request 1 0
Info 2021-07-09 14:31:38: Execute Cell 0 file:///c%3A/Users/psirving/OneDrive%20-%20University%20of%20North%20Carolina%20at%20Chapel%20Hill/GitHub/JNBTools/JNB-example/3d_test.ipynb
Info 2021-07-09 14:31:38: Cell Index:0, state:1, exec: 2. User queued cell for execution
Info 2021-07-09 14:31:38: Cell Index:0, state:1, exec: 2. Ready to execute
Info 2021-07-09 14:31:38: Cell Index:0, state:1, exec: 2. Before Execute individual cell
Info 2021-07-09 14:31:38: Cell Index:0, state:1, exec: 2. Start execution
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: undefined. Send code for execution
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: undefined. Wait for jupyter execution
Info 2021-07-09 14:31:38: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-07-09 14:31:38: [32mPosting message to Notebook UI 
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:31:38: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:31:38: [32mPosting message to Notebook UI 
Info 2021-07-09 14:31:38: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:31:38: [32mPosting message to Notebook UI 
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: undefined. Kernel switching to busy
Info 2021-07-09 14:31:38: Notebook Session status file:///c%3A/Users/psirving/OneDrive%20-%20University%20of%20North%20Carolina%20at%20Chapel%20Hill/GitHub/JNBTools/JNB-example/3d_test.ipynb # Busy
Info 2021-07-09 14:31:38: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:31:38: [32mPosting message to Notebook UI 
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: undefined. Update output
Info 2021-07-09 14:31:38: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:31:38: [32mPosting message to Notebook UI 
Info 2021-07-09 14:31:38: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:31:38: [32mPosting message to Notebook UI 
Info 2021-07-09 14:31:38: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-07-09 14:31:38: [32mPosting message to Notebook UI 
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-07-09 14:31:38: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: 3. Update output
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: 3. Kernel switching to idle
Info 2021-07-09 14:31:38: Notebook Session status file:///c%3A/Users/psirving/OneDrive%20-%20University%20of%20North%20Carolina%20at%20Chapel%20Hill/GitHub/JNBTools/JNB-example/3d_test.ipynb # Idle
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: 3. Jupyter execution completed
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: 3. Completed successfully
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: 3. Completed successfully & resolving
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: 3. After Execute individual cell 3
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: 3. Executed successfully in executeCell
Info 2021-07-09 14:31:38: Cell Index:0, state:3, exec: 3. Execution disposed
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Odd, I can replicate in stable however it works in insiders.
Please could you install VS Code insiders and try this out, its possible its related to an upstream issue (in vsocde) & its been fixed there.
Appreciate your help.

**Comment by Psirving** [comment]
Yup, works perfect with insiders. Thanks so much!

**Comment by DonJayamanne** [comment]
Sounds like a bug in vscode stable that's fixed in insiders. 
I'll try to keep an eye out for this when the next version of vscode gets released
