### ISSUE TITLE
Always Scroll On new cell setting not working in new native Interactive mode

### ISSUE THREAD

**Issue by jonvlcs07** [microsoft/vscode-jupyter#6603]
-   VS Code version: 1.58.0
-   Jupyter Extension version: 2021.8.0

In the new native interactive mode with the setting `Jupyter: Always Scroll On New Cell` enabled, when I'm running cells it doesn't scroll down to newest cell in the interactive window as it should.

**Comment by joyceerhl** [comment]
We actually need a way to scroll to show the output, not the cell input.

![image](https://user-images.githubusercontent.com/30305945/125119612-38f97e80-e0a6-11eb-8c6e-a6fb0d50d0c8.png)

I don't believe we have a way to do this yet:

![image](https://user-images.githubusercontent.com/30305945/125119706-54648980-e0a6-11eb-8438-331e3f0f9b93.png)

**Comment by StevenLi-DS** [comment]
This is missing indeed and the notebook UI not scroll at all.

**Comment by joyceerhl** [comment]
@jonvlcs07 This should be fixed in tonight's build, please let us know if it works for you 😊

**Comment by jonvlcs07** [comment]
Hey, it's still not scrolling down to the latest output in the interactive window when `jupyter.enableNativeInteractiveWindow` is set and I'm running cells.

**Comment by Keeptg** [comment]
> 
> 
> Hey, it's still not scrolling down to the latest output in the interactive window when `jupyter.enableNativeInteractiveWindow` is set and I'm running cells.

It doesn't work to me too!

**Comment by joyceerhl** [comment]
Sorry, I should have been more specific. It should be fixed in the latest Jupyter build for VS Code Insiders, or our next stable release at the beginning of August.

**Comment by rzhao271** [comment]
This works on Insiders.
