### ISSUE TITLE
Newly installed python venv doesn't show up in the kernel list until workbench reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#6865]
* Create a `venv` from the integrated terminal
* 🐛 The new interpreter is available in the interpreter list, but it's not visible in the kernel list, until we reload the window

**Comment by rchiodo** [comment]
This should have been fixed in the insiders build. We used to not get interpreter change events from the python extension.

@rebornix what version are you using?

**Comment by DonJayamanne** [comment]
> used to not get interpreter change events from the python extension.

We're still don't get the events. I've filled an issue requesting the api changes from python extension (we need an event that tells us when the list of interpreters change).

**Comment by rebornix** [comment]
I'm using 

```
Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2021.8.1074296055
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
```

**Comment by DonJayamanne** [comment]
Here's the feature request for Python:
* https://github.com/microsoft/vscode-python/issues/16676
* https://github.com/microsoft/vscode-python/discussions/16683

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5319
