### ISSUE TITLE
Auto complete not working properly

### ISSUE THREAD

**Issue by raj-adroit** [microsoft/vscode-jupyter#6970]
Issue Type: <b>Bug</b>

create new Jupyternote book:

when you type ->
```
from tensorflow import keras
keras.datasets.mn
```

It will show a autocomplete option mnist, press enter and the expected result is:
`keras.datasets.mnist`

but what's happening is: 
`keras.datasets.keras.datasets.mnist
`

Extension version: 2021.8.1054968649
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-63-generic
Restricted Mode: No
Fetching remote diagnostics for 'ssh-remote+gcp-mongodb-1' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1225 v5 @ 3.30GHz (4 x 800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|15.51GB (4.25GB free)|
|Process Argv|. --crash-reporter-id f54ac525-65f2-4329-b4a7-f525dd441fb9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

Fetching remote diagnostics for 'ssh-remote+gcp-mongodb-1' timed out.
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464:30346472

```

</details>

**Comment by greazer** [comment]
Thanks for the report. This should be fixed in today's VS Code release (v1.59)

**Comment by raj-adroit** [comment]
Looks this bug not fixed yet, I just tested in the new version v1.59

![screen_1](https://user-images.githubusercontent.com/2361576/128527454-b9fcf8f3-2ae0-46ff-8ab5-81da5a214237.png)
![screen_2](https://user-images.githubusercontent.com/2361576/128527466-4795de6e-8c00-48ae-aefd-d595817bcb2d.png)
![version](https://user-images.githubusercontent.com/2361576/128527613-857c2c9d-c6a9-43f8-8546-ea8df3ed2b26.png)
