### ISSUE TITLE
Diagnostics reported for JS cells in Python notebooks

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7039]
![image](https://user-images.githubusercontent.com/30305945/128788828-168269a0-8964-4e92-91b1-5607743624c1.png)

We should be skipping these cells when their language changes.

**Comment by rchiodo** [comment]
This should be fixed.

**Comment by DonJayamanne** [comment]
Not fixed:
* Create a python cell type `console.log(1234);`
* Confirm we have errors
* Change language to javascript
* We still have errors
* Edit the cell and the errors go away, 

FYI I'm testing `We should be skipping these cells when their language changes.`

**Comment by judej** [comment]
Is this still repro? I am seeing the ts language server offer diagnostics now.
![image](https://user-images.githubusercontent.com/547753/136603271-7795ae6d-506f-45d3-b86b-88a92ee927ff.png)

**Comment by rchiodo** [comment]
This is working now. Switch over to pylance doing notebooks fixed this.

To verify follow Don's steps:
- Create new notebook
- In first cell type ```console.log('foo')```
- Switch cell type to javascript
- Verify diagnostics disappear
- Switch cell back to python
- Verify diagnostics reappear.
