### ISSUE TITLE
Fail to use catboost-widget in vscode-jupyter

### ISSUE THREAD

**Issue by RayAnteku** [microsoft/vscode-jupyter#7407]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @RayAnteku, could you please fill out the issue template including vs code version, extension versions etc. and provide an example of the code and output when you attempt to use catboost? Screenshots, videos, or the code creating problems and the error would be helpful too

**Comment by RayAnteku** [comment]
> Hi @RayAnteku, could you please fill out the issue template including vs code version, extension versions etc. and provide an example of the code and output when you attempt to use catboost? Screenshots, videos, or the code creating problems and the error would be helpful too

hello, @claudiaregio ,
my vscode can refer to this
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

and the version of my jupyter extension is v2021.8.2031190714

here is my code :

```
from catboost.datasets import amazon
(train_df, test_df) = amazon()
y = train_df.ACTION
X = train_df.drop('ACTION', axis=1)
cat_features = list(range(0, X.shape[1]))
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from catboost import Pool

data = train_test_split(X, y, test_size=0.2, random_state=0)
X_train, X_validation, y_train, y_validation = data
train_pool = Pool(data=X_train, label=y_train, cat_features=cat_features)
validation_pool = Pool(data=X_validation, label=y_validation, cat_features=cat_features)

model = CatBoostClassifier(iterations=50, learning_rate=0.5, custom_loss=['AUC', 'Accuracy'])
model.fit(train_pool, eval_set=validation_pool, verbose=False, plot=True)
```

and the screenshot following is the situation of runing my code

![image](https://user-images.githubusercontent.com/32634151/132155153-98396097-7413-4ca2-91e7-045e523158db.png)


 you can see my test code is running well, but It can not output the plot like this
 
![image](https://user-images.githubusercontent.com/32634151/132155671-d5dd8777-6904-4503-bc22-afd4294c8830.png)

thx!!

**Comment by DonJayamanne** [comment]
This shoudl now be fixed with https://github.com/microsoft/vscode-jupyter/pull/10509

**Comment by aeschli** [comment]
I still see the same error with
Jupyter v2022.6.1001831043
Python v2022.9.11811011

![image](https://user-images.githubusercontent.com/6461412/176728907-51bd4eab-da83-482b-9cf4-5fa624e5d9d5.png)

**Comment by DonJayamanne** [comment]
Closing this so it gets validated

**Comment by roblourens** [comment]
Weird - the first time, it rendered correctly but I got the error notification. I reloaded the window and tried again, and now I only get the text output

<img width="748" alt="image" src="https://user-images.githubusercontent.com/323878/186481579-a81745b9-4904-4460-bf45-f38ac9c368ae.png">

<img width="618" alt="image" src="https://user-images.githubusercontent.com/323878/186482109-8d54791d-dd10-459a-9f13-38519de830c9.png">

Third time, I got the same as the first attempt

**Comment by DonJayamanne** [comment]
@roblourens 
* Do you have a custom value defined for `jupyter.widgetScriptSources` (or is it the default)
* When you run the the cell and end up with the text output, can you share the logs, both VS Code console window as well as Jupyter output

**Comment by roblourens** [comment]
I did have that setting. Not sure where it came from. I commented out and now rendering this output seems to be working consistently.
