### ISSUE TITLE
Provide a way to skip diagnostics in the interactive window

### ISSUE THREAD

**Issue by RichardPflaum** [microsoft/vscode-jupyter#8289]
See my [question](https://stackoverflow.com/questions/70001482/how-to-ignore-python-interactive-window-for-linting-in-vscode) on Stackoverflow.

**Comment by rchiodo** [comment]
Thanks for the bug.

This has been addressed in the insiders version.

This commit here removed all diagnostics from the interactive window:
https://github.com/microsoft/vscode-jupyter/commit/796361a98965ecf0e178034bf939e72e3058022e

**Comment by RichardPflaum** [comment]
Hi, sorry to bug you again. I'm currently using the latest insiders version and I still see the Pylance linting output for the interactive windows. 

### System Info:
Version: 1.70.0-insider (user setup)
Commit: cc098faebd320a2eea3da6ae154b7e2e1347a4b9
Date: 2022-07-26T05:16:55.337Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by rchiodo** [comment]
You might try setting this flag and trying again:

```
"python.pylanceLspNotebooksEnabled": true
```

That flag informs pylance to take over all intellisense for notebooks and the interactive window.

**Comment by RichardPflaum** [comment]
Thank you, unfortunately this didn't deactivate linting for the interactive window.
The linting messages I see were also given by Pylance before, independent of that setting.
Here is an **exemplary error message**:
<details>
  <summary>Click to expand!</summary>

```
[{
	"resource": "Interactive-1.interactive",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportUndefinedVariable",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "\"blabla\" is not defined",
	"source": "Pylance",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 7
}]
```
</details>


Here is my full **settings.json:**

<details>
  <summary>Click to expand!</summary>

```
{
    "python.defaultInterpreterPath": "C:\\ProgramData\\Anaconda3\\python.exe",
    "editor.rulers": [
        100
    ],
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "editor.tabCompletion": "on",
    "terminal.integrated.profiles.windows": {
        "Anaconda Prompt": {
            "source": "PowerShell",
            "args": ["C:\\ProgramData\\Anaconda3\\Scripts\\activate.bat C:\\ProgramData\\Anaconda3",]
        }
    },
    "terminal.integrated.defaultProfile.windows": "Command Prompt",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "editor.wordWrap": "on",
    "python.linting.pylintEnabled": false,
    "python.linting.pylintArgs": [
        "--include-naming-hint=n",
        "--disable=all",
        "--enable=F,E,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode",
        "--ignored-modules=scipy.special",
        "--ignored-classes=numpy.ndarray",
        "--ignored-classes=numpy.random"
    ],
    "python.linting.enabled": true,
    "python.linting.pycodestyleEnabled": true,
    "python.linting.pycodestyleArgs": [
        "--ignore=E501, E303, E302, E265, E262, E116, W292, E402, W391, W503, W504, E305, W605"
    ],
    "python.linting.pycodestyleCategorySeverity.E": "Warning",
    "python.linting.pycodestylePath": "pycodestyle",
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": [
        "--max-line-length=100",
        "--ignore=E116, E265, W605, W503",
    ],
    "python.terminal.launchArgs": [
        "-c",
        "\"from IPython import start_ipython; start_ipython()\""
    ],
    "editor.detectIndentation": false,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
    "autoDocstring.docstringFormat": "google",
    "python.linting.ignorePatterns": [
        ".vscode/*.py",
        "**/site-packages/**/*.py",
        "numpy/**",
        "scipy/**",
        "*interactive*",
        "Interactive*",
        "*.interactive"
    ],
    "python.formatting.autopep8Args": [
        "--select=E,W"
    ], // %matplotlib qt
    "svn.multipleFolders.enabled": true,
    "svn.multipleFolders.depth": 3,
    "terminal.integrated.inheritEnv": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.minimap.renderCharacters": false,
    "python.testing.pytestEnabled": false,
    "python.testing.unittestEnabled": true,
    "python.languageServer": "Pylance",
    "files.associations": {
        "*.cfg": "ini",
        "*.code": "ini",
        "*.jcfg": "json",
        "Jenkinsfile*": "groovy"
    },
    "window.zoomLevel": 2,
    "jupyter.sendSelectionToInteractiveWindow": true,
    "jupyter.askForKernelRestart": false,
    "jupyter.runStartupCommands": [
        "%reload_ext autoreload",
        "%autoreload 2"
    ],
    "jupyter.notebookFileRoot": "${workspaceFolder}",
    "workbench.editorAssociations": {
        "*.ipynb": "jupyter-notebook"
    },
    "indentRainbow.ignoreErrorLanguages": [
        "*"
    ],
    "security.workspace.trust.untrustedFiles": "open",
    "notebook.cellToolbarLocation": {
        "default": "right",
        "jupyter-notebook": "left"
    },
    "files.autoGuessEncoding": true,
    "workbench.colorTheme": "Ayu Light",
    "editor.unicodeHighlight.nonBasicASCII": false,
    "git.autofetch": true,
    "notebook.output.textLineLimit": 500,
    "python.pylanceLspNotebooksEnabled": true
}
```

</details>


**Specs:** 
<details>
  <summary>Click to expand!</summary>
<html>
<body>


CPUs | AMD Ryzen 7 5800U with Radeon Graphics (16 x 1896)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.31GB (23.13GB free)
Process Argv | --crash-reporter-id 2c1de22a-3312-4301-a9af-3054bf5bf057
Screen Reader | no
VM | 0%


</body>
</html>

</details>

**Extensions:**
<details>
 <summary>Click to expand!</summary>
<html>
<body>


Extension | Author (truncated) | Version
-- | -- | --
svn-scm | joh | 2.15.5
vsc-python-indent | Kev | 1.17.0
python | ms- | 2022.13.12141005
vscode-pylance | ms- | 2022.7.44
jupyter | ms- | 2022.8.1002161046
jupyter-keymap | ms- | 1.0.0
jupyter-renderers | ms- | 1.0.9
autodocstring | njp | 0.6.1
indent-rainbow | ode | 8.3.1
trailing-spaces | sha | 0.4.1
ayu | tea | 1.0.5


</body>
</html>
</details>

**A/B Experiment info:**
<details>
   <summary>Click to expand!</summary>
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
vscaac:30438845
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
</details>

Is there anything else I can provide which might help to reproduce this on your side?

**Comment by rchiodo** [comment]
Oh that's the same as this issue then.

https://github.com/microsoft/pylance-release/issues/3103

If the experimental flag is turned on, pylance should be handling all of this themselves.

**Comment by rchiodo** [comment]
Actually with that flag off, the linting problem goes away for me. You might want to turn off that experiment (it's hard to tell if you ended up in the experiment automatically or not).

**Comment by RichardPflaum** [comment]
Thank you for the quick replies. Are you referring to the setting `"python.experiments.enabled": false`?
That doesn't remove linting of the cells for me.
I don't have the problem where function definitiions are not transfered from one cell to the next.
For me it's when i execute a script with a mistake, where something is actually not defined. 
E.g. running a file hello.py containing nothing but `hello` gives me this error message:

<details>
  <summary> Click to expand! </summary>

```
[{
	"resource": "Interactive-1.interactive",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportUndefinedVariable",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "\"hello\" is not defined",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 6
}]
```
</details> 

This error message remains, until I close the interactive window and I don't think it's beneficial, because I cannot change the executed cells in the interactive window anyways and the error is shown below the executed code in the interactive window.

**Comment by rchiodo** [comment]
This is the setting I was referring to: 

```
"python.pylanceLspNotebooksEnabled": false
```

That switches to a different way to do notebook intellisense. It changes linting in the interactive window.

However I would expect the value `hello` in a python file to show an error? Are you asking for it to not show any diagnostic messges for the interactive window (well because the execution of them shows the error anyway)?

That's not quite the same as linting bugs, but I could see how that might be useful. Why bother linting the interactive window if it just runs everything anyway.

**Comment by RichardPflaum** [comment]
Exactly. The interactive window runs everything anyways and once you execute the cell, it is read only and cannot be modified. Linting cells that cannot be modified serves no purpose and clutters the "problems" area.

**Comment by MCRE-BE** [comment]
I think my issue is related (should have taken screenshots) :

- I had an interactive window with more or less 500 cells (but regularly cleared), so more like 500 executions
- VSCode performed linting on all 500 cells even when cleared
- VSCode linting for the normal window is disabeled
- This resulted in > 14K warnings or errors (seriously slowing down my computer) with no way to clear them outside restarting the interactive window.

Curious to see if changing that setting will prevent this from happening.

**Comment by MCRE-BE** [comment]
A small toy example : 
![pylancce issue](https://user-images.githubusercontent.com/99316631/182830604-5fb4368a-a360-44d9-a4de-6f27d56edadb.jpg)

Changing the setting seems to work

**Comment by ortk95** [comment]
Here is another simple example where disabling linting would be useful - if you try to use a variable defined in a previous cell, module previously imported etc., you get a `"..." is not defined` error:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/26504228/205118714-1b137a5c-f821-43d3-b361-131646fb4725.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/26504228/205119061-bfcec1c6-d9bd-4138-91aa-a4403f9cc9f1.png">

**Comment by DonJayamanne** [comment]
This is a fairly old issue, over a year and we haven't seen any new content here since.
I'm assuming this has been resolved, if not, then I would suggest filing an issue in the repo of the corresponding extension
E.g. if pylance is reporting issues, then please file an issue on that repo
as those extensions are responsible and Jupyter extension cannot disable those.
