### ISSUE TITLE
Interactive Widgets fail on Apple Silicon, Remote Jupyter & when using non-Raw kernels

### ISSUE THREAD

**Issue by evgenyneu** [microsoft/vscode-jupyter#8378]
## Environment data

-   VS Code version: 1.62.3
-   Jupyter Extension version: v2021.10.1101450599
-   Python Extension version: v2021.11.1422169775
-   OS and version: macOS Monterey 12.0.1 running on AppleSilicon Mac
-   Python version: 3.9.5
-   Type of virtual environment used: venv
-   Jupyter server running: Local 

## Expected behaviour

As you move a slider the function is called multiple times.

## Actual behaviour

The function is called once.

## Steps to reproduce:

* Create a Jupiter notebook with this code, which contains a slider.

```
from ipywidgets import interact

def f(x):
  print(x)
    
interact(f, x=10);
```

* Open it in VSCode, move the slider.

## Expected behaviour

The widget calls the function `f` multiple times as you move the slider.

## Actual behaviour

The function `f` is only called once at the beginning:

![demo_m1](https://user-images.githubusercontent.com/880411/143863722-3f7ae9d8-fe11-4659-b490-62e8c2aa2bf3.gif)

## Notes

* I could only see the bug on Apple Silicon Mac and not on my Intel Mac. 

* The widget works as expected on Apple Silicon Mac if opened in jupuyter-lab instead of VSCode.

## Repository that reproduces the bug

https://github.com/evgenyneu/ipywidgets_vscode_bug

**Comment by DonJayamanne** [comment]
Please could you try the latest VS Code insiders version.
Its possible this has been fixed in there. I'm unable to repro this in VS Code insiders.
* Install VSCode insiders from here https://code.visualstudio.com/insiders/
* Install Jupyter extesnsion (in VS Code Insiders you'll automatically get the latest dev version of Jupyter extension built daily from our main branch)

**Comment by DonJayamanne** [comment]
Weird, works for me with the same python packages.
Please could you try another Python environment, possible something hasn't been installed correctly.
Also, please could you install jupyter & notebook into the same environment (`python -m pip install jupyter notebook`) and run Jupyter from there `python -m jupyter notebook` and run the same code to see whether it works.

**Comment by evgenyneu** [comment]
Thanks, @DonJayamanne 

Tried both conda and venv environments (see commands below), still have this problem in both.  Tried python installed by conda and asdf, same problem. Tried different Python versions (3.9.5, 3.10.0, 3.8.11), no difference.


### Conda

```
conda create --name widgets_demo python=3.10
conda activate widgets_demo
python -m pip install jupyter notebook
```

### venv

```
python -m venv .venv
. .venv/bin/activate
python -m pip install jupyter notebook
```


> run Jupyter from there python -m jupyter notebook and run the same code to see whether it works

The problem does not exist in Jupyter notebook when I run it normally (in the web browser). Everything works fine. The problem only exist in the Apple Silicon version of VS code.

**Comment by evgenyneu** [comment]
Here is a demo video. TLRD: I installed both Intel and Apple Silicon versions of VS Code Insiders. The widget works fine in Intel but not in Apple Silicon.

https://user-images.githubusercontent.com/880411/143978562-eafebcb7-ff91-4f0d-ae68-a252a9359656.mp4

id

**Comment by DonJayamanne** [comment]
@evgenyneu Thanks for your patience, I'e identified the problem and should be able to get this fixed.

**Comment by DonJayamanne** [comment]
Verified here https://github.com/microsoft/vscode-jupyter/issues/8407#issuecomment-983668647

**Comment by DonJayamanne** [comment]
**Testing steps**
* Use non-raw 
* Create a cell with teh code:
```python
from ipywidgets import interact

def f(x):
  print(x)
    
interact(f, x=10);
```
* Run the cell & move the slider
* Confirm the outputs are updated (both counters)

In stable, this will not work with remote or non-raw.
Now this should work in raw, non-raw & remote

**Comment by evgenyneu** [comment]
I can confirm the bug is fixed in VS Code insiders Apple Silicon build.

* VS Code: 1.63.0-insider Commit: 0cc0904c565399781defa830facf43141db8b6f3
* Jupyter extension: v2021.11.1001524965
* Python extension: v2021.11.1422169775

**Comment by DonJayamanne** [comment]
@antonindurieux thanks for finding that, I've created an issue for that here https://github.com/microsoft/vscode-jupyter/issues/8431

**Comment by DonJayamanne** [comment]
@antonindurieux
I've managed to identify the fix and got a PR open for this.

**Comment by DonJayamanne** [comment]
**Testing steps**
* Connect to a remote Jupyter server
* Create a cell with teh code:
```python
from ipywidgets import interact

def f(x):
  print(x)
    
interact(f, x=10);
```
* Run the cell & move the slider
* Confirm the outputs are updated (both counters)
* Restart the kernel and re-run the cell and confirm its rendered

**Comment by DonJayamanne** [comment]
Closing as done for verification
