### ISSUE TITLE
kernel connection file created in `/tmp/` rather than `~/.local/share/jupyter/runtime/`

### ISSUE THREAD

**Issue by Fan-iX** [microsoft/vscode-jupyter#8827]
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Gentoo Linux / CentOS 7 / WSL Ubuntu 20.04
-   Python and/or Anaconda version: Python 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote / WSL

## Expected behaviour

runtime kernel connection json file created in `~/.local/share/jupyter/runtime/` so that it can be recognized by `jupyter console --existing`

## Actual behaviour

runtime kernel connection json file created in `/tmp/` and `jupyter console --existing` shows error message
`[ZMQTerminalIPythonApp] CRITICAL | Could not find existing kernel connection file kernel*.json`

this is not a big problem for ipykernel since I can connect a jupyter console to the kernel according to the `%connect_info` message.
but it becomes a problem when I use irkernel in which the `%connect_info` method haven't been implemented.

## Steps to reproduce:

1. create an interactive window in VS Code.
2. run `%connect_info`
3. see `$> jupyter <app> --existing /tmp/tmp-1033rJp0TWSU8vOv.json` in cell output, indicating that the connection json file is created in `/tmp/`
4. run `jupyter console --existing`
5. get error message `[ZMQTerminalIPythonApp] CRITICAL | Could not find existing kernel connection file kernel*.json`

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel 
</summary>

<p>

```
%connect_info
```

```
{
  "shell_port": 9002,
  "iopub_port": 9004,
  "stdin_port": 9003,
  "control_port": 9001,
  "hb_port": 9000,
  "ip": "127.0.0.1",
  "key": "0b43f78a-4183-4728-b3c6-d734dfa4fb12",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""
}

Paste the above JSON into a file, and connect with:
    $> jupyter <app> --existing <file>
or, if you are local, you can connect with just:
    $> jupyter <app> --existing /tmp/tmp-1033rJp0TWSU8vOv.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
I repro the same. Thanks for filing this I don't believe that we were considering this scenario of connecting to the session started from the interactive window. We can look at where we are creating the connection.

Out of interest, can I ask why you are connecting to the IW kernel? I'd like to understand the scenario more.

**Comment by greazer** [comment]
We should use the jupyter location. If it's not writable fall back to tmp.

**Comment by Fan-iX** [comment]
> I repro the same. Thanks for filing this I don't believe that we were considering this scenario of connecting to the session started from the interactive window. We can look at where we are creating the connection.
> 
> Out of interest, can I ask why you are connecting to the IW kernel? I'd like to understand the scenario more.

Well, what I actually want to do is to connect a jupyter console to an `.ipynb` runtime R kernel to have an console interface like in RStudio.

"create an interactive window in VS Code" in the repro step simply means "start a kernel from vscode-jupyter".

**Comment by DonJayamanne** [comment]
I'm @Fan-iX we've published a new Pre-release version of the jupyter extension.
The connection .json file will exist (we were deleting this in some cases)

Leaving this issue open to move these json files into the `jupyter/runtime` directory

**Comment by Fan-iX** [comment]
Sorry to disturb again, it seems this issue is not fixed for Linux - the connection file is still created in `/tmp/` for jupyter extension version `v2022.4.1000912146`.

<details>
<summary>Linux <code>%connect_info</code> output</summary>

```
{
  "shell_port": 9002,
  "iopub_port": 9004,
  "stdin_port": 9003,
  "control_port": 9001,
  "hb_port": 9000,
  "ip": "127.0.0.1",
  "key": "8e92b294-2890-49a4-a880-272bffe8e437",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""
}

Paste the above JSON into a file, and connect with:
    $> jupyter <app> --existing <file>
or, if you are local, you can connect with just:
    $> jupyter <app> --existing /tmp/tmp-1632j63KH5nlqi2P.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.
```

</details>

**Comment by DonJayamanne** [comment]
that doesn't look like the latest version, please could you check for updates and update to the latest version

**Comment by Fan-iX** [comment]
the same in version `v2022.4.1001252103`.
the problem is that this issue is actually fixed in macOS.
<details>
<summary>MacOS <code>%connect_info</code> output</summary>

```
{
  "shell_port":53564,
  "iopub_port":53565,
  "stdin_port":53566,
  "control_port":53568,
  "hb_port":53567,
  "ip":"127.0.0.1",
  "key":"fd14aee4-7c2275f3fc3f8ded65af35f9",
  "transport":"tcp",
  "signature_scheme":"hmac-sha256",
  "kernel name":""
}

Paste the above JSON into a file,and connect with:
    $>jupyter <app> --existing <file>
or,if you are local, you can connect with just:
    $> jupyter <app> --existing kernel-56dfc4c9-4ac7-4243-a627-fde6501a2448.json
or even just:
    $> jupyter <app> --existing
if this is the most recent Jupyter kernel you have started.
```

</details>

**Comment by DonJayamanne** [comment]
will test wsl,

**Comment by DonJayamanne** [comment]
@Fan-iX is this still an issue in the latest version of VS Code and Jupyter extensions?

**Comment by Fan-iX** [comment]
It works as expected generally, and is compatible with `jupyter console`.
But there is another small problem that these connection files won't be deleted when I close the VS Code window directly (leaving the notebook/interactive window tab open before closing the VS Code window), so sometimes I'll have to remove them manually.
Anyway, thanks for the fix, this issue can be closed if needed.

**Comment by DonJayamanne** [comment]
Thanks for getting back
