### ISSUE TITLE
"Failed to start the kernel"

### ISSUE THREAD

**Issue by OneMoreSecond** [microsoft/vscode-jupyter#9234]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

VSCode always said Jupyter kernel failed to start on my local machine after updated to 2022.2.
Reverting the extension version to 2022.1 can solve this issue.

However, the local Jupyter server launched successfully. I can browse it with the URL in logs and run Python code.

Translations in logs:

- "内核 Python 3.8.10 不能使用。查看 Jupyter 输出标签页了解更多信息。"："Kernel Python 3.8.10 is not available. Check Jupyter output tab for further details"

### VS Code Version

Version: 1.65.0 Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43 Date: 2022-03-02T11:12:36.248Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Linux x64 5.13.0-28-generic snap

### Jupyter Extension Version

2022.2.102

### Jupyter logs

```shell
Visual Studio Code (1.65.0, undefined, desktop)
Jupyter Extension Version: 2022.2.1020642448.
Python Extension Version: 2022.2.1924087327.
用户属于实验组 'jupyterTest'
用户属于实验组 'jupyterEnhancedDataViewer'
Error 16:01:57: Exception while attempting zmq : Error: /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/node_modules/zeromq/prebuilds/linux-x64/electron.napi.glibc.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1185:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.n._load (/snap/code/89/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32148)
    at Function._._load (/snap/code/89/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28737)
    at Function.g._load (/snap/code/89/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:60372)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/snap/code/89/usr/share/code/resources/app/out/vs/loader.js:4:699)
    at load (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/node_modules/node-gyp-build/index.js:1:605)
    at Object.<anonymous> (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/node_modules/zeromq/lib/native.js:1:198)
    at Module.u._compile (/snap/code/89/usr/share/code/resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.n._load (/snap/code/89/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32148)
    at Function._._load (/snap/code/89/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28737)
    at Function.g._load (/snap/code/89/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:60372)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/snap/code/89/usr/share/code/resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/node_modules/zeromq/lib/index.js:1:144)
    at Module.u._compile (/snap/code/89/usr/share/code/resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.n._load (/snap/code/89/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32148)
    at Function._._load (/snap/code/89/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28737)
    at Function.g._load (/snap/code/89/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:60372)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at h (/snap/code/89/usr/share/code/resources/app/out/vs/loader.js:4:699)
    at Object.92747 (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:3878485)
    at __webpack_require__ (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:4545798)
    at d.zmqSupported (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:973026)
    at d.isSupportedForLocalLaunch (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:972817)
    at d.get isSupported [as isSupported] (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:972727)
    at t.registerTypes (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:983912)
    at /home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:1070474
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:4547373
    at e.activate (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:4547050)
Info 16:01:57: Old kernelspecs (created by Jupyter extension) stored in directory /home/xhtang/.local/share/jupyter/kernels/__old_vscode_kernelspecs
Info 16:01:57: Preferred kernel connection found in cache .jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher
Info 16:01:57: PreferredConnection: .jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher found for NotebookDocument: ~/crypto-log/monthly_report.ipynb
Info 16:01:57: Early registration of controller for Kernel connection .jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher
Info 16:01:57: TargetController found ID: .jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher for document ~/crypto-log/monthly_report.ipynb
Info 16:01:57: Setting controller affinity for ~/crypto-log/monthly_report.ipynb .jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher
Info 16:01:57: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 16:01:57: Creating controller for jupyter-notebook with interpreter /usr/bin/python3.8
Info 16:01:57: Getting activation commands for /usr/bin/python3.8 are not cached. May take a while.
Info 16:01:57: Interrupt requested & no kernel.
Info 16:01:57: Setting setActiveController for ~/crypto-log/monthly_report.ipynb
Info 16:01:57: KernelProvider switched kernel to id = .jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher
Info 16:01:57: Starting Notebook in kernel.ts id = .jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher
Info 16:01:57: Checking for server existence.
Info 16:01:57: Checking for server usability.
Info 16:01:57: Process Execution: > /usr/bin/python3.8 -m pip list
> /usr/bin/python3.8 -m pip list
Info 16:01:57: Process Execution: > /usr/bin/python3.8 -c "import jupyter"
> /usr/bin/python3.8 -c "import jupyter"
Info 16:01:57: Process Execution: > /usr/bin/python3.8 -c "import notebook"
> /usr/bin/python3.8 -c "import notebook"
Info 16:01:57: Process Execution: > /usr/bin/python3.8 -m jupyter kernelspec --version
> /usr/bin/python3.8 -m jupyter kernelspec --version
Info 16:01:57: Registering dummy command feature
Info 16:01:57: Starting notebook server.
Info 16:01:57: Connecting to server
Info 16:01:57: Launching server
Info 16:01:57: Starting Notebook
Info 16:01:57: Generating custom default config at /tmp/eea54227-9425-464d-835b-ffefbccfa5d3/jupyter_notebook_config.py
Info 16:01:57: Starting Jupyter Notebook
用命令行 --no-browser --notebook-dir="/home/txh/crypto-log" --config=/tmp/eea54227-9425-464d-835b-ffefbccfa5d3/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0 从 /usr/bin/python3.8 启动 Jupyter
Info 16:01:58: Creating daemon pool for /usr/bin/python3.8 with env variables count 89
Info 16:01:58: Process Execution: > /usr/bin/python3.8 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 828064
> /usr/bin/python3.8 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 828064
Info 16:01:58: Process Execution: > /usr/bin/python3.8 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 828064
> /usr/bin/python3.8 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 828064
Info 16:01:58: Process Execution: > /usr/bin/python3.8 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 828064
> /usr/bin/python3.8 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 828064
Info 16:01:58: Process Execution: > /usr/bin/python3.8 (daemon) -m jupyter notebook --no-browser --notebook-dir="/home/txh/crypto-log" --config=/tmp/eea54227-9425-464d-835b-ffefbccfa5d3/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /usr/bin/python3.8 (daemon) -m jupyter notebook --no-browser --notebook-dir="/home/txh/crypto-log" --config=/tmp/eea54227-9425-464d-835b-ffefbccfa5d3/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
Info 16:01:58: Waiting for Jupyter Notebook
/home/txh/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '/home/txh/crypto-log' instead of '"/home/txh/crypto-log"' – or use CUnicode.
  warn(
Info 16:01:58: /home/txh/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '/home/txh/crypto-log' instead of '"/home/txh/crypto-log"' – or use CUnicode.
  warn(

[I 16:01:58.453 NotebookApp] 启动notebooks 在本地路径: /home/txh/crypto-log
Info 16:01:58: /home/txh/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '/home/txh/crypto-log' instead of '"/home/txh/crypto-log"' – or use CUnicode.
  warn(
[I 16:01:58.453 NotebookApp] 启动notebooks 在本地路径: /home/txh/crypto-log

[I 16:01:58.453 NotebookApp] Jupyter Notebook 6.4.3 is running at:
Info 16:01:58: /home/txh/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '/home/txh/crypto-log' instead of '"/home/txh/crypto-log"' – or use CUnicode.
  warn(
[I 16:01:58.453 NotebookApp] 启动notebooks 在本地路径: /home/txh/crypto-log
[I 16:01:58.453 NotebookApp] Jupyter Notebook 6.4.3 is running at:

[I 16:01:58.453 NotebookApp] http://localhost:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
Info 16:01:58: /home/txh/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '/home/txh/crypto-log' instead of '"/home/txh/crypto-log"' – or use CUnicode.
  warn(
[I 16:01:58.453 NotebookApp] 启动notebooks 在本地路径: /home/txh/crypto-log
[I 16:01:58.453 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 16:01:58.453 NotebookApp] http://localhost:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364

Info 16:01:58: Process Execution: > /usr/bin/python3.8 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3.8 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 16:01:58.453 NotebookApp]  or http://127.0.0.1:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
Info 16:01:58: /home/txh/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '/home/txh/crypto-log' instead of '"/home/txh/crypto-log"' – or use CUnicode.
  warn(
[I 16:01:58.453 NotebookApp] 启动notebooks 在本地路径: /home/txh/crypto-log
[I 16:01:58.453 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 16:01:58.453 NotebookApp] http://localhost:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
[I 16:01:58.453 NotebookApp]  or http://127.0.0.1:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364

Info 16:01:58: Process Execution: > /usr/bin/python3.8 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3.8 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 16:01:58.453 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
Info 16:01:58: /home/txh/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '/home/txh/crypto-log' instead of '"/home/txh/crypto-log"' – or use CUnicode.
  warn(
[I 16:01:58.453 NotebookApp] 启动notebooks 在本地路径: /home/txh/crypto-log
[I 16:01:58.453 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 16:01:58.453 NotebookApp] http://localhost:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
[I 16:01:58.453 NotebookApp]  or http://127.0.0.1:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
[I 16:01:58.453 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).

[C 16:01:58.456 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/txh/.local/share/jupyter/runtime/nbserver-828261-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
     or http://127.0.0.1:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
Info 16:01:58: /home/txh/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '/home/txh/crypto-log' instead of '"/home/txh/crypto-log"' – or use CUnicode.
  warn(
[I 16:01:58.453 NotebookApp] 启动notebooks 在本地路径: /home/txh/crypto-log
[I 16:01:58.453 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 16:01:58.453 NotebookApp] http://localhost:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
[I 16:01:58.453 NotebookApp]  or http://127.0.0.1:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
[I 16:01:58.453 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 16:01:58.456 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/txh/.local/share/jupyter/runtime/nbserver-828261-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364
     or http://127.0.0.1:8888/?token=a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364

Info 16:01:58: Connecting to process server
Info 16:01:58: Connecting server kernel http://localhost:8888/
Info 16:01:58: Creating server with settings : {"baseUrl":"http://localhost:8888/","appUrl":"","wsUrl":"ws://localhost:8888/","token":"a8c2294fe05b6c1d2c9171411f1ce9c4517104ca7c4bc364","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 16:01:58: Connection complete server
Info 16:01:58: Server started.
Info 16:01:58: Process Execution: > /usr/bin/python3.8 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3.8 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/pythonFiles/vscode_datascience_helpers/getServerInfo.py
Info 16:01:58: Process Execution: > /usr/bin/python3.8 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3.8 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 16:02:01.468 NotebookApp] Creating new notebook in 
Info 16:02:01: installMissingDependencies /usr/bin/python3.8
Info 16:02:01: IPykernel found previously in this environment /usr/bin/python3.8
Info 16:02:01: Spec argv[0] updated from '/usr/bin/python3.8' to '/usr/bin/python3.8'
Info 16:02:01: Starting a new session for kernel id = .jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher, name = python3810jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6
[I 16:02:01.539 NotebookApp] Kernel started: d1faf0b5-fcd4-443e-be27-f8d54970d828, name: python3810jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6
Info 16:02:01: Waiting for idle on (kernel): d1faf0b5-fcd4-443e-be27-f8d54970d828 -> unknown
[W 16:02:01.552 NotebookApp] delete /monthly_report-jvsc-2ecfeead-e9fe-43db-9f46-f6511d5f6db2.ipynb
[I 16:02:04.541 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
[I 16:02:07.549 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
[I 16:02:10.554 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
[I 16:02:13.561 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
[W 16:02:16.568 NotebookApp] KernelRestarter: restart failed
[W 16:02:16.568 NotebookApp] Kernel d1faf0b5-fcd4-443e-be27-f8d54970d828 died, removing from map.
Error 16:03:01: Failed to change kernel TypeError: Cannot read property 'statusChanged' of null
    at C.waitForIdleOnSession (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:267513)
    at C.createNewKernelSession (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:610331)
    at C.connect (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:609167)
    at m.startNew (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:617517)
    at a (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:742232)
    at w.createNotebookInstance (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:742380)
    at w.createNotebook (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:743323)
Error 16:03:01: failed to create INotebook in kernel, UI Disabled = true c [Error]: 内核 Python 3.8.10 不能使用。查看 Jupyter 输出标签页了解更多信息。
    at C.createNewKernelSession (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:610534)
    at C.connect (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:609167)
    at m.startNew (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:617517)
    at a (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:742232)
    at w.createNotebookInstance (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:742380)
    at w.createNotebook (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:743323) {
  category: 'invalidkernel',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/txh/.local/share/jupyter/kernels/python3810jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6/kernel.json',
      interpreterPath: '/usr/bin/python3.8',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3810jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6',
      argv: [Array],
      language: 'python',
      path: '/usr/bin/python3.8',
      display_name: 'Python 3.8.3 64-bit',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      sysPrefix: '/usr',
      envType: 'Unknown',
      envName: '',
      envPath: '',
      path: '/usr/bin/python3.8',
      architecture: 3,
      sysVersion: '3.8.10 (default, Nov 26 2021, 20:14:08) \n[GCC 9.3.0]',
      version: [Object],
      displayName: 'Python 3.8.3 64-bit'
    },
    id: '.jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher'
  }
}
Error 16:03:01: failed to start INotebook in kernel, UI Disabled = true c [Error]: 内核 Python 3.8.10 不能使用。查看 Jupyter 输出标签页了解更多信息。
    at C.createNewKernelSession (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:610534)
    at C.connect (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:609167)
    at m.startNew (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:617517)
    at a (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:742232)
    at w.createNotebookInstance (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:742380)
    at w.createNotebook (/home/txh/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:743323) {
  category: 'invalidkernel',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/txh/.local/share/jupyter/kernels/python3810jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6/kernel.json',
      interpreterPath: '/usr/bin/python3.8',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3810jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6',
      argv: [Array],
      language: 'python',
      path: '/usr/bin/python3.8',
      display_name: 'Python 3.8.3 64-bit',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      sysPrefix: '/usr',
      envType: 'Unknown',
      envName: '',
      envPath: '',
      path: '/usr/bin/python3.8',
      architecture: 3,
      sysVersion: '3.8.10 (default, Nov 26 2021, 20:14:08) \n[GCC 9.3.0]',
      version: [Object],
      displayName: 'Python 3.8.3 64-bit'
    },
    id: '.jvsc74a57bd0df0893f56f349688326838aaeea0de204df53a132722cbd565e54b24a8fec5f6./usr/bin/python3.8./usr/bin/python3.8.-m#ipykernel_launcher'
  }
}
[W 16:03:01.561 NotebookApp] Timeout waiting for kernel_info reply from d1faf0b5-fcd4-443e-be27-f8d54970d828
[E 16:03:01.562 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: d1faf0b5-fcd4-443e-be27-f8d54970d828)
```

### Coding Language and Runtime Version

Python 3.8.10

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@OneMoreSecond @Fournierp @Bart-van-Ingen

Please could you install the pre-release version of the extension and confirm this has been fixed in there.
I believe it should work (we identified an issue just after the release and fixed it).

**Comment by Tartenpi0m** [comment]
Same issue but the pre-release version fixed it for me.

**Comment by G-R-A-F-F** [comment]
The same issue here, pre-release of Jupyter fixed it.

**Comment by esther119** [comment]
The same issue here, pre-release of Jupyter fixed it.

**Comment by zhengyy24** [comment]
The same issue here, pre-release of Jupyter fixed it.

**Comment by DonJayamanne** [comment]
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/9231

**Comment by DonJayamanne** [comment]
### Temporary Solution until a fix is published tomorrow (7th March PST)

Please install the pre-release version of the Extension as a temporary work around.
Just go into the extension panel and install the pre-release version see below.
Click the `Switch to pre-release version`
![image](https://user-images.githubusercontent.com/1948812/156850466-24088c58-08f3-4881-91a5-5b5794ff923e.png)

Once installed you should see the green badge indicating you are on pre-release
![image](https://user-images.githubusercontent.com/1948812/156850551-d8110011-f5b1-4c13-a2a4-55e1988b6680.png)

**Comment by DonJayamanne** [comment]
This has been fixed and a release has been shipped

**Comment by carlosan1708** [comment]
I faced the same issue and it seems this fix it's still not in the release version yet, overall the solution works perfectly in the pre-release version.

**Comment by chongfengling** [comment]
Hi, I met the same problem and updated to the pre-release version but it did not work for me still.

**Comment by chongfengling** [comment]
> Hi, I met the same problem and updated to the pre-release version but it did not work for me still.

`Visual Studio Code (1.66.2, undefined, desktop)
Jupyter Extension Version: 2022.4.1000912146.
Python Extension Version: 2022.4.1.
Workspace folder c:\Users\59903\OneDrive\XJTLU\FYP
Info 01:47:15: ZMQ install verified.
用户属于实验组 'jupyterTest'
用户属于实验组 'jupyterEnhancedDataViewer'
Info 01:47:15: Preferred kernel connection found in cache .jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2.C:\Users\59903\anaconda3\python.exe.C:\Users\59903\anaconda3\python.exe.-m#ipykernel_launcher
Info 01:47:15: PreferredConnection: .jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2.C:\Users\59903\anaconda3\python.exe.C:\Users\59903\anaconda3\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\59903\OneDrive\XJTLU\FYP\software\graph.ipynb
Info 01:47:15: Early registration of controller for Kernel connection .jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2.C:\Users\59903\anaconda3\python.exe.C:\Users\59903\anaconda3\python.exe.-m#ipykernel_launcher
Info 01:47:15: TargetController found ID: .jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2.C:\Users\59903\anaconda3\python.exe.C:\Users\59903\anaconda3\python.exe.-m#ipykernel_launcher for document c:\Users\59903\OneDrive\XJTLU\FYP\software\graph.ipynb
Info 01:47:15: Setting controller affinity for c:\Users\59903\OneDrive\XJTLU\FYP\software\graph.ipynb .jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2.C:\Users\59903\anaconda3\python.exe.C:\Users\59903\anaconda3\python.exe.-m#ipykernel_launcher
Info 01:47:15: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 01:47:16: Setting setActiveController for c:\Users\59903\OneDrive\XJTLU\FYP\software\graph.ipynb
Info 01:47:16: KernelProvider switched kernel to id = .jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2.C:\Users\59903\anaconda3\python.exe.C:\Users\59903\anaconda3\python.exe.-m#ipykernel_launcher
Info 01:47:16: Starting Notebook in kernel.ts id = .jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2.C:\Users\59903\anaconda3\python.exe.C:\Users\59903\anaconda3\python.exe.-m#ipykernel_launcher for c:\Users\59903\OneDrive\XJTLU\FYP\software\graph.ipynb
Info 01:47:16: Creating raw notebook for c:\Users\59903\OneDrive\XJTLU\FYP\software\graph.ipynb
Info 01:47:16: Getting preferred kernel for c:\Users\59903\OneDrive\XJTLU\FYP\software\graph.ipynb
Info 01:47:16: Computing working directory c:\Users\59903\OneDrive\XJTLU\FYP\software\graph.ipynb
Info 01:47:16: Creating controller for jupyter-notebook with interpreter ~\anaconda3\python.exe
Info 01:47:16: Starting raw kernel base (Python 3.8.5) for interpreter ~\anaconda3\python.exe
Info 01:47:16: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 01:47:17: Registering dummy command feature
Info 01:47:17: Execute Cells request 0
Info 01:47:17: Execute Cell 0 c:\Users\59903\OneDrive\XJTLU\FYP\software\graph.ipynb
Info 01:47:18: Process Execution: > ~\anaconda3\python.exe -m pip list
> ~\anaconda3\python.exe -m pip list
Info 01:47:18: Process Execution: > ~\anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 01:47:18: Adding env Variable PYTHONNOUSERSITE to ~\anaconda3\python.exe
Info 01:47:18: Creating daemon process for ~\anaconda3\python.exe with env variables count 69
Info 01:47:18: Process Execution: > ~\anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 12884
> ~\anaconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 12884
Info 01:47:19: get interrupthandle daemon
Info 01:47:19: Process Execution: > ~\anaconda3\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"988f788d-bfbe-4c18-8c53-50f221ee3a2f" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\59903\AppData\Local\Temp\tmp-128848KTl52dN12kS.json
> ~\anaconda3\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"988f788d-bfbe-4c18-8c53-50f221ee3a2f" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\59903\AppData\Local\Temp\tmp-128848KTl52dN12kS.json
Info 01:47:19: Process Execution: cwd: c:\Users\59903\OneDrive\XJTLU\FYP\software
cwd: c:\Users\59903\OneDrive\XJTLU\FYP\software
Info 01:47:19: ipykernel version 6.10.0 for ~\anaconda3\python.exe
Info 01:47:19: ipykernel location ~\anaconda3\lib\site-packages\ipykernel\__init__.py for ~\anaconda3\python.exe
Warn 01:47:20: StdErr from Kernel Process Traceback (most recent call last):

Warn 01:47:20: StdErr from Kernel Process   File "C:\Users\59903\anaconda3\lib\runpy.py", line 194, in _run_module_as_main

Warn 01:47:20: StdErr from Kernel Process     return _run_code(code, main_globals, None,
  File "C:\Users\59903\anaconda3\lib\runpy.py", line 87, in _run_code

Warn 01:47:20: StdErr from Kernel Process     
Warn 01:47:20: StdErr from Kernel Process exec(code, run_globals)
  File "C:\Users\59903\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>

Warn 01:47:20: StdErr from Kernel Process     from ipykernel import kernelapp as app
  File "C:\Users\59903\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 22, in <module>

Warn 01:47:20: StdErr from Kernel Process     from IPython.core.application import (
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\__init__.py", line 51, in <module>

Warn 01:47:20: StdErr from Kernel Process     from .core.application import Application
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\application.py", line 27, in <module>

Warn 01:47:20: StdErr from Kernel Process     from IPython.core import release, crashhandler
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>

Warn 01:47:20: StdErr from Kernel Process     from IPython.core import ultratb
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\ultratb.py", line 107, in <module>

Warn 01:47:20: StdErr from Kernel Process     from IPython.core import debugger
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\debugger.py", line 123, in <module>

Warn 01:47:20: StdErr from Kernel Process     from pdb import Pdb as OldPdb
  File "C:\Users\59903\anaconda3\lib\pdb.py", line 77, in <module>

Warn 01:47:20: StdErr from Kernel Process     
Warn 01:47:20: StdErr from Kernel Process import code
  File "c:\Users\59903\OneDrive\XJTLU\FYP\software\code.py", line 18
    df = pd.DataFrame(columns=)
                              ^
SyntaxError: invalid syntax

Error 01:47:20: Disposing kernel process due to an error [o [Error]: 内核已被中止。查看 Jupyter [日志](command:jupyter.viewOutput)了解更多细节。
错误：Traceback (most recent call last):
  File "C:\Users\59903\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\59903\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\59903\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\59903\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 22, in <module>
    from IPython.core.application import (
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\__init__.py", line 51, in <module>
    from .core.application import Application
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\application.py", line 27, in <module>
    from IPython.core import release, crashhandler
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\ultratb.py", line 107, in <module>
    from IPython.core import debugger
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\debugger.py", line 123, in <module>
    from pdb import Pdb as OldPdb
  File "C:\Users\59903\anaconda3\lib\pdb.py", line 77, in <module>
    import code
  File "c:\Users\59903\OneDrive\XJTLU\FYP\software\code.py", line 18
    df = pd.DataFrame(columns=)
                              ^
SyntaxError: invalid syntax...
	at ChildProcess.<anonymous> (c:\Users\59903\.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:487531)
	at ChildProcess.emit (node:events:402:35)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)] {
  category: 'kerneldied',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: 'c:\\Users\\59903\\.vscode\\extensions\\ms-toolsai.jupyter-2022.4.1000912146\\temp\\jupyter\\kernels\\python385jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2\\kernel.json',
      interpreterPath: 'C:\\Users\\59903\\anaconda3\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python385jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2',
      argv: [Array],
      language: 'python',
      path: 'python',
      display_name: "Python 3.8.5 ('base')",
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: 'C:\\USERS\\59903\\ANACONDA3\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\59903\\anaconda3',
      envType: 'Conda',
      envName: 'base',
      envPath: 'C:\\Users\\59903\\anaconda3',
      path: 'C:\\Users\\59903\\anaconda3\\python.exe',
      architecture: 3,
      sysVersion: '3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]',
      version: [Object],
      companyDisplayName: 'ContinuumAnalytics',
      displayName: "Python 3.8.5 ('base')",
      detailedDisplayName: "Python 3.8.5 ('base': conda)"
    },
    id: '.jvsc74a57bd0f91f13d384e68efd17c728347eec4dcd8917015cb7974b4e72550edebe4372e2.C:\\Users\\59903\\anaconda3\\python.exe.C:\\Users\\59903\\anaconda3\\python.exe.-m#ipykernel_launcher'
  },
  exitCode: 1,
  stdErr: 'Traceback (most recent call last):\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\runpy.py", line 194, in _run_module_as_main\r\n' +
    '    return _run_code(code, main_globals, None,\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\runpy.py", line 87, in _run_code\r\n' +
    '    exec(code, run_globals)\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py", line 15, in <module>\r\n' +
    '    from ipykernel import kernelapp as app\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\site-packages\\ipykernel\\kernelapp.py", line 22, in <module>\r\n' +
    '    from IPython.core.application import (\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\site-packages\\IPython\\__init__.py", line 51, in <module>\r\n' +
    '    from .core.application import Application\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\site-packages\\IPython\\core\\application.py", line 27, in <module>\r\n' +
    '    from IPython.core import release, crashhandler\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\site-packages\\IPython\\core\\crashhandler.py", line 28, in <module>\r\n' +
    '    from IPython.core import ultratb\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\site-packages\\IPython\\core\\ultratb.py", line 107, in <module>\r\n' +
    '    from IPython.core import debugger\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\site-packages\\IPython\\core\\debugger.py", line 123, in <module>\r\n' +
    '    from pdb import Pdb as OldPdb\r\n' +
    '  File "C:\\Users\\59903\\anaconda3\\lib\\pdb.py", line 77, in <module>\r\n' +
    '    import code\r\n' +
    '  File "c:\\Users\\59903\\OneDrive\\XJTLU\\FYP\\software\\code.py", line 18\r\n' +
    '    df = pd.DataFrame(columns=)\r\n' +
    '                              ^\r\n' +
    'SyntaxError: invalid syntax\r\n'
}
Error 01:47:20: Traceback (most recent call last):
  File "C:\Users\59903\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\59903\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\59903\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\59903\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 22, in <module>
    from IPython.core.application import (
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\__init__.py", line 51, in <module>
    from .core.application import Application
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\application.py", line 27, in <module>
    from IPython.core import release, crashhandler
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\ultratb.py", line 107, in <module>
    from IPython.core import debugger
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\debugger.py", line 123, in <module>
    from pdb import Pdb as OldPdb
  File "C:\Users\59903\anaconda3\lib\pdb.py", line 77, in <module>
    import code
  File "c:\Users\59903\OneDrive\XJTLU\FYP\software\code.py", line 18
    df = pd.DataFrame(columns=)
                              ^
SyntaxError: invalid syntax

Info 01:47:20: Dispose Kernel process
Info 01:47:20: kill daemon
Error 01:47:20: Failed to connect raw kernel session: Error: 内核已被中止。查看 Jupyter [日志](command:jupyter.viewOutput)了解更多细节。
错误：Traceback (most recent call last):
  File "C:\Users\59903\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\59903\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\59903\anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\59903\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 22, in <module>
    from IPython.core.application import (
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\__init__.py", line 51, in <module>
    from .core.application import Application
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\application.py", line 27, in <module>
    from IPython.core import release, crashhandler
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\ultratb.py", line 107, in <module>
    from IPython.core import debugger
  File "C:\Users\59903\anaconda3\lib\site-packages\IPython\core\debugger.py", line 123, in <module>
    from pdb import Pdb as OldPdb
  File "C:\Users\59903\anaconda3\lib\pdb.py", line 77, in <module>
    import code
  File "c:\Users\59903\OneDrive\XJTLU\FYP\software\code.py", line 18
    df = pd.DataFrame(columns=)
                              ^
SyntaxError: invalid syntax...
Info 01:47:20: Process Execution: > ~\anaconda3\python.exe -c "import ipykernel"
> ~\anaconda3\python.exe -c "import ipykerne‘’
`

**Comment by carlosan1708** [comment]
chongfengling, not sure if related, but "df = pd.DataFrame(columns=)" is a compilation error of your program, remove columns or define columns inside the pandas dataFrame.

**Comment by chongfengling** [comment]
> chongfengling, not sure if related, but "df = pd.DataFrame(columns=)" is a compilation error of your program, remove columns or define columns inside the pandas dataFrame.

Thank you for your comment and it is not related to kernel start (even "a = 1" failed). Your words hit me. There was a file called "code.py" and it was mentioned in the log. I changed the filename and the kernel started correct,

**Comment by JosueCom** [comment]
I am still having an issue with this error

**Comment by amunger** [comment]
@JosueCom - could you open a new issue with the logs from the output window with "Jupyter" selected in the dropdown.

**Comment by mahasaya** [comment]
but why does this problem arise

**Comment by BlackHawk0** [comment]
switching to prelease worked for me

**Comment by Fatheed7** [comment]
Switching to prerelease did not work for me.

**Comment by Frederic-Jacquet** [comment]
It's odd. The rollback to pre-release didn't work for me. In fact i renamed a .py file to .txtfile in the same folder and the issue disapeared.....
FYI the kernel was sending me error message only because of these 2 lines :

!pip install beautifulsoup4
!pip install requests

**Comment by DonJayamanne** [comment]
> In fact i renamed a .py file to .txt file in the same folder and the issue disapeared.....

This is an indication that you have some file that is shaowing a Python module.
E.g. if you create a file like `random.py` that will shaow the `random` python module and most of the Python environment to completely fall over and you might not event be able to run a simple hello world program.
