### ISSUE TITLE
tqdm unable to remove progress bar widgets – blank vertical space left in the output container

### ISSUE THREAD

**Issue by aldanor** [microsoft/vscode-jupyter#9397]
## Environment data

-   VS Code version: 1.65.2
-   Jupyter Extension version: v2022.2.1030672458
-   Python Extension version: v2022.2.1924087327
-   macOS 10.15.7
-   Python 3.9, conda
-   Jupyter server: local

## Observed behaviour

https://user-images.githubusercontent.com/2418513/158709989-5f602613-cee7-4c56-a080-d540fec5645b.mp4

## Expected behaviour

No blank vertical space is left.

## Related

https://github.com/tqdm/tqdm/issues/1287

**Comment by IanMatthewHuff** [comment]
Hmm, I'm looking at this right now in vscode-insiders (which has all our newest bits) I'm seeing something slightly different.
![TQDM](https://user-images.githubusercontent.com/812783/158870352-b71d7e61-6b15-4c5b-8d79-5fc49575e328.gif)
Here I don't see the extra lines, but I also don't see the second and third passes of the 10 size loop. 

Does seem like there is some type of issue though. Thanks for the report on this.

**Comment by DonJayamanne** [comment]
This looks like a bug in VS Code, I'm seeing a lot of weird behaviors
* Basically sometimes the 2nd progress is not visible (but when i scroll or add a new cell it magically appears)
* The output `Done` is not displayed at the end (but when i scroll or add a new cell it magically appears)

**Comment by DonJayamanne** [comment]
This should now be fixed in the latest insider version of VS Code and Jupyter extension

**Comment by rchiodo** [comment]
It's better but still not fixed. I'll reopen the vscode bug too.

Here's what I get:
![tqdm](https://user-images.githubusercontent.com/19672699/165835982-68e50027-0596-45b2-bc18-87389d6fed03.gif)

Compare that to jupyter and you can see we end up with extra blank lines.

**Comment by rebornix** [comment]
@rchiodo it doesn't seem to be an issue with rendering, if you check the document after saving it, you would see for every blank line is actually a widget output. VS Code is rendering them as expected.

**Comment by rchiodo** [comment]
Yeah this is a VS code issue. Jupyter doesn't use absolute positioning. We do. So even empty outputs show up as taking space.

You can see it here in Jupyter:

![image](https://user-images.githubusercontent.com/19672699/170388904-7269ed17-2eac-4032-bdf4-594810fcab22.png)

And this is the same DOM in VS code:

![image](https://user-images.githubusercontent.com/19672699/170388949-e09c0768-4317-42ac-8614-a54b7a0b391f.png)

The absolute positioning of the empty lines forces them to have a perceived height.

**Comment by rchiodo** [comment]
@rebornix is it possible to skip the height for items that have nothing in the DOM? These are widgets, so we're doing the rendering, but we don't add anything.

The DOM for one of the empty lines is this:

![image](https://user-images.githubusercontent.com/19672699/170389160-180f094a-c020-49a5-a617-4402b5457b5d.png)

It has zero height (just like Jupyter)

**Comment by DonJayamanne** [comment]
>  possible to skip the height for items that have nothing in the DOM? These 

I recall this being fixed at one point in time. basically @rebornix added a fix to check if there as no output added or checking the height, & if none, then he'd collapse the output. looks like we've regressed here.

**Comment by rchiodo** [comment]
After a bunch of discussion we decided on this:

- Jupyter extension will detect empty model scenario
- If an empty model is present, it will remove the other mimetypes from the output
- This should cause VS code to not render anything for the empty model

This has the side effect of losing the text/plain data (maybe we only remove this type) so that if you were to reopen this in Jupyter it would only show the text/plain for the model that had some output.

**Comment by DonJayamanne** [comment]
> If an empty model is present, it will remove the other mimetypes from the output

We can add these into another hidden metadata or the like.
Lets explore different options. E.g. how about a metadata to indicate something needs to be hidden?

**Comment by cceyda** [comment]
Looking forward to a fix on this since it effects not just `tqdm` but everything that uses `ipywidgets` to render in notebooks
<img width="535" alt="image" src="https://user-images.githubusercontent.com/15624271/197961151-470c263a-36c5-42ed-bd0c-50d9b4c9b479.png">

**Comment by DonJayamanne** [comment]
> it effects not just tqdm but everything that uses ipywidgets to render in notebooks

can you provide another sample of other ipywidgets (that you've mentioned)

**Comment by cceyda** [comment]
yes `rich` library uses ipywidgets' `Output()` behind the scenes.[[code](https://github.com/Textualize/rich/blob/master/rich/live.py#L232)]

```py
# !pip install -q rich
from rich.progress import track
from time import sleep
for x in track(range(5)):
    sleep(0.1)
```

**Comment by NChechulin** [comment]
Currently, `tqdm.notebook` progress bar is not displayed at all (VSCode 1.72.2)

**Comment by sdesrozis** [comment]
Any update on this ?

**Comment by UFO-101** [comment]
Opened a PR in tqdm to work around this: https://github.com/tqdm/tqdm/pull/1504
In the meantime you can use https://github.com/UFO-101/tqdm.git as a depedency.
